### ISSUE TITLE
Add ability to upgrade velero version via CLI

### ISSUE THREAD

**Issue by ncdc** [vmware-tanzu/velero#1087]
- check for missing CRDs and add them
- ideally preserve upgrade logic for each version, to support upgrading from _n_ to _n+2_ without having to do _n+1_ first.

**Comment by skriss** [comment]
xref #2034 #2028

**Comment by skriss** [comment]
xref #2508

**Comment by skriss** [comment]
cc @yogeek. I've updated this issue title to be more general so we don't presume that upgrade should be a separate command from install. Please see #2508 for more context on @yogeek's preference for this to function more like `kubectl apply` rather than having a separate command for install vs. upgrade.

**Comment by eleanor-millman** [comment]
Closing because will rely on Carvel to do this (should be in 1.7 release).
