### ISSUE TITLE
Replace the in-process restic repository lock management with restic’s built-in lock

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#1540]

**Comment by skriss** [comment]
Restic has a concept of repository locks.  All restic operations create either an exclusive or non-exclusive lock on the repository they're operating on. A non-exclusive lock can be created *only* if there are no **exclusive** locks that currently exist; an exclusive lock can be created *only* if there are **no** locks that currently exist.  If a restic CLI command is run and the necessary lock cannot be acquired, the restic CLI exits with an error.

Velero currently has an in-process lock manager that provides a coordination layer on top of restic's locks. It uses a `sync.RWMutex` since the semantics are the same as restic's exclusive/non-exclusive locks.  The benefit of this component is that Velero code will **wait** to run restic operations until the necessary lock can be acquired, rather than just running the command,  potentially getting an error back, and having to retry over and over.

The problem with Velero's lock manager is that it's in-process, i.e. in the Velero deployment pod.  If/when we move to running backups/restores in separate pods, they won't have any way to interact with this lock manager.  It could potentially be moved out-of-process (e.g. by using a Kubernetes ConfigMap to maintain the state of the locks) but implementing a distributed read-write lock is non-trivial.

I propose that we eliminate the Velero lock manager, and modify our code that makes restic CLI calls to check for returned errors that indicate a lock could not be acquired, and to retry with backoff if that happens.  This way we're only using restic's built-in lock management.

**Comment by skriss** [comment]
As we look at #1511, let's consider whether there's any overlap between this issue and that one. If not, then we'll move this issue in v1.2.

**Comment by skriss** [comment]
Moved out of the v1.1 backlog.

**Comment by skriss** [comment]
I've been thinking that maybe we should defer this until we tackle #1653, which may not be in the next release or two given all the other priorities. Otherwise, implementing a fix for this issue is fairly disruptive and doesn't buy us much.

**Comment by skriss** [comment]
@carlisia @nrb @prydonius @VMmore interested in your thoughts on deferring this until we tackle #1653.

**Comment by prydonius** [comment]
@skriss from the description of this, it sounds like this would be a pre-requisite if backups/restores were to be moved out to separate pods? Or did you just mean to defer until we want to tackle #1653 in the same release, but still implement before?

**Comment by carlisia** [comment]
> The problem with Velero's lock manager is that it's in-process, i.e. in the Velero deployment pod. If/when we move to running backups/restores in separate pods, they won't have any way to interact with this lock manager. 

From that ^ statement, sounds like it would be needed before, like @prydonius pointed out. Even if for some reason this is not the case, I wonder if it wouldn't be easier to make this change and test it while we are not yet running on multiple workers.

**Comment by skriss** [comment]
Yeah, sorry, my wording was unclear. This issue remains a prereq for #1653. I'm just proposing bundling it with #1653 (which isn't yet scheduled), since doing this issue itself doesn't really provide benefit until we go to tackle #1653. So, e.g., if #1653 gets scheduled for 2.0, then we do this issue in 2.0 as well (or just prior).

**Comment by carlisia** [comment]
Yes, it makes sense to bundle those two since there's no gain to be had in doing it now other than removing code, which can wait.

**Comment by carlisia** [comment]
Un-assigning myself since I'm not actively working on this.

**Comment by eleanor-millman** [comment]
Closing because we are avoiding restic-exclusive work
