### ISSUE TITLE
GKE Workload Identity Support

### ISSUE THREAD

**Issue by eduartua** [vmware-tanzu/velero#1657]
**Describe the problem/challenge you have**
Installing Velero in a cluster that supports GKE Workload Identity is not possible right now. Workload Identity is the recommended way to access Google Cloud services from within GKE due to its improved security properties and manageability. With WI there is no need to pass a secrets key file for the service account. In the latest velero version if you don't pass a secrets content or the secrets does not exist in the namespace, you'll get a failing POD with an error like this one:
```
"Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:431"
An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = open /credentials/cloud: no such file or directory 
```

**Describe the solution you'd like**

The next words are based on a Velero installation via Helm, but it could be applied with kubectl.
One possible solution could be to add a workload identity option in the values file. Based on that value, we may decide how the GCP plugin authenticates the velero-server.

Workload Identity works matching a GCP Service Account with a  Kubernetes Service Account. To achieve this we only need to add an annotation to that velero service account.
Once the K8s SA receives all the GCP SA roles and permissions, there is no need of passing any other type of credentials via secrets.

I have tested the Velero SA after assigning it the GCP SA permissions and works beautifully.

**Anything else you would like to add:**

Annotation to add to the Velero SA:
```
serviceAccountAnnotations:
  iam.gke.io/gcp-service-account: GCP_SA_NAME@[GCP_PROJECT_ID].iam.gserviceaccount.com
```

**Environment:**

- Velero version (use `velero version`): 2.1.1
- Kubernetes version (use `kubectl version`): 1.12.9-gke.7
- Kubernetes installer & version:
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`): Container-Optimized OS (cos)

**Comment by eduartua** [comment]
Cloud/GCP
Enhancement/User

**Comment by eduartua** [comment]
@skriss

**Comment by skriss** [comment]
ref. https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

Looking into this some more, it looks like the main issue we need to figure out is how to generate pre-signed URLs when we're using this approach to identity. Velero uses pre-signed URLs to enable users to access backup/restore artifacts from object storage (e.g. `velero backup logs`, etc). This currently relies on having a private key for the service account that is used to sign requests.  It's not clear to me how this would be done while using Workload Identity.

There are a couple other code changes that would need to be made to Velero in `pkg/cloudprovider/gcp` but those should be straight-forward.

**Comment by victortrac** [comment]
@skriss I spoke with @salrashid123 (googler) about this, and this is the basic process to use workload identity (or more generally, an assumed GCE instance role without requiring a service account JSON key file):

1. Grant the service account iam.serviceAccountTokenCreator role to itself
1. Follow the V4 signing process to generate a URL string to sign (https://cloud.google.com/storage/docs/access-control/signing-urls-manually)
1. Make an HTTP request to the GCE metadata service for an access token: 
`curl -s -H 'Metadata-Flavor: Google' http://metadata/computeMetadata/v1/instance/service-accounts/default/token`
1. Using the access token, use the iam signBlob method (https://cloud.google.com/iam/credentials/reference/rest/v1/projects.serviceAccounts/signBlob) to get the Signed URL

It's a bit convoluted and requires requesting multiple GCP API endpoints directly, but it should allow velero to generate signed GCS URLs without requiring a service account key file.  

If I get some time over the next few weeks, I'll put in a PR.

**Comment by salrashid123** [comment]
he'res some moe docs on the flow...its a bit awkward

- https://github.com/salrashid123/gcpsamples/tree/master/gcs_keyless_signedurl   (i  should update it for v4 signing)

i got a token via Application Defaults (`GoogleCredentials()`).  in your case, it'd be `ComputeEngineCredentials` since that'll help bootstrap the iamcredentials api call.   Or you can just get  token manually from metadata server and pipe it into 
- https://godoc.org/golang.org/x/oauth2#StaticTokenSource
- https://oauth2client.readthedocs.io/en/latest/source/oauth2client.client.html#oauth2client.client.AccessTokenCredentials

---
i'd suggest trying computetokensource since that'll manage refreshing the creds for you..

**Comment by skriss** [comment]
@victortrac @salrashid123 thanks for the info!

**Comment by dhulihan** [comment]
Thanks for the example code @salrashid123 ! I used your example in golang to make a request to `signBlob` via [SignBytes](https://github.com/googleapis/google-cloud-go/blob/716684cb381189346f058d73c66b814c938fb5de/storage/storage.go#L182), which lets you perform custom signing logic:

```go
func GenerateSignedURLOptions(psa *iamcredentials.*ProjectsServiceAccountsService, serviceAccount string) (*&storage.SignedURLOptions, error) {
	return &storage.SignedURLOptions{
		GoogleAccessID: serviceAccount,
		Method:         "GET",
		Expires:        time.Now().Add(time.Minute * 10)
		SignBytes: func(b []byte) ([]byte, error) {
			name := fmt.Sprintf("projects/-/serviceAccounts/%s", serviceAccount)

			payload := base64.StdEncoding.EncodeToString(b)

			req := iamcredentials.SignBlobRequest{
				Payload: payload,
			}
			call := psa.SignBlob(name, &req)

			resp, err := call.Do()
			if err != nil {
				return nil, err
			}

			if resp.HTTPStatusCode != 200 {
				return nil, fmt.Errorf("response contained unexpected status code: %d", resp.HTTPStatusCode)
			}

			decoded, err := base64.StdEncoding.DecodeString(resp.SignedBlob)
			if err != nil {
				return nil, err
			}

			return decoded, nil
		},
	}, nil
}
```

**Comment by salrashid123** [comment]
nice!. (i didn't realize you could override the signer like that in our google-storage-go library).

i don't know velero but if it ever needs to execute using a `Signer` or credentials derived from a `TPM` module where keys sealed...i've got _experimental_ support for google credentials usng tpm-sealed keys (which you can also use to sign since it implements a `Signer`):

(this is just as FYI, unrelated to this issu; if there's interest in that, LMK 

* https://github.com/salrashid123/misc/tree/master/tpm
* https://github.com/salrashid123/oauth2#usage-tpmtokensource
* https://github.com/salrashid123/tpm2_evp_sign_decrypt
*  and a real impractial sideshow:  https://github.com/salrashid123/kms_golang_signer

@dhulihan

**Comment by dhulihan** [comment]
very cool @salrashid123 ! It's nice to see TPM support in Go 😸
