### ISSUE TITLE
velero_backup_last_successful_timestamp metric vanishes when velero pod is restarted

### ISSUE THREAD

**Issue by awwithro** [vmware-tanzu/velero#1777]
**Describe the problem/challenge you have**
I'd like to be able to monitor the state of backups in a cluster. Instead of worrying about successful/failed backups I'd like to have a monitor that only alerts if the last successful backup is older than some arbitrary amount of time. The metric velero_backup_last_successful_timestamp should allow for this. However, when velero is restarted/rescheduled, this metric is no longer emitted until another successful backup happens. This makes it difficult to build a backup-age based alert. 

**Describe the solution you'd like**
Velero should make a best effort attempt to recover this metric by examining the backup objects in the cluster and setting velero_backup_last_successful_timestamp to the completion timestamp of the most recent successful backup

**Environment:**

- Velero version (use `velero version`): v1.0.0
- Kubernetes version (use `kubectl version`): v1.14.6
- Kubernetes installer & version: N/A
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Ubuntu

**Comment by nrb** [comment]
@skriss I think this is a good candidate for v1.2. I'm thinking that changing the sync controller to update this metric seems reasonable.

**Comment by skriss** [comment]
@nrb I'll move this into the release for now as a P2 item.

Food for thought: should we have a separate "controller" that handles periodically re-syncing these kinds of gauge metrics, rather than scattering them throughout other controllers? I'm not sure yet, but worth considering.

**Comment by nrb** [comment]
@skriss yeah, that's worth exploring at the very least.

**Comment by skriss** [comment]
Couple thoughts from looking at this so far:
- in general, I'd say that "gauge" metrics make sense to recover on server restart, since they aren't just monotonically increasing counters. This includes the following:
    - `backup_last_successful_timestamp`
    - `backup_total`
    - `restore_total`
    - `backup_tarball_size_bytes`
- I think it *could* make sense to reconstruct "counter" metrics too, but it really just depends on what users expect them to represent - are they counters for the currently-running process, or counters across restarts of the process? For now, I'd propose not recovering these on server restart.
- For the "gauge" metrics, `backup_total` and `restore_total` could be implemented as `GaugeFunc` metrics, meaning their value is computed on-demand, by providing a function that uses a velero lister to list/count the number of CRs that exist.
- `backup_tarball_size_bytes` is difficult to reconstruct after a server restart, without either (1) downloading all the tarballs from object storage, or (2) having the tarball size as a field in the backup CR's status. I'd propose *not* reconstructing this one on server startup for now, until the need arises from a user.
- `backup_last_successful_timestamp` can be reconstructed after server startup by looking at the most recent successful backup for each Schedule, and using its `status.completionTimestamp`. 
    - The main question is where to put this code. Right now, this metric is set (indirectly) from the backup controller each time a backup is successfully completed. We could put the reconstruction logic in that controller, to be executed when the controller starts up, which would keep all uses of the metric close. Alternately, it could go in `server.go`, the backup sync controller, or a new "metrics controller".  I don't really see a lot of value to putting it in one of those places, so I'd lean towards keeping it close to the other code that sets it, in the backup controller, but open to differing opinions here.

**Comment by nrb** [comment]
I agree with repopulating gauge metrics on restart; they're useful for the overall deployment, not just a single process's lifespan.

For `backup_total` and `restore_total`, `GaugeFunc` makes sense to compute on demand, so long as we're sure to use the Informers and cache in order to be performant.

As far as code location, for now I think keeping it where it's at makes the most sense. However, if and when backups start happening in worker pods versus the same pod, it may make sense to move that code. I'm not really sure what the best answer is for aggregating stats on ephemeral pods, but that's also not something we need to solve for immediately.

**Comment by skriss** [comment]
> For `backup_total` and `restore_total`, `GaugeFunc` makes sense to compute on demand, so long as we're sure to use the Informers and cache in order to be performant.

It turns out these are already being re-computed during a controller's resync function, so I didn't bother changing them as they already have the desired behavior.
