### ISSUE TITLE
errors creating custom resources in v1.13.7 cluster using master version of velero

### ISSUE THREAD

**Issue by skriss** [vmware-tanzu/velero#1935]
I'm using a locally-built version of the `velero` CLI built from the latest code in `master`. After installing into a `v1.13.7` cluster, I'm getting various errors when trying to create CRs via the CLI.

kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

Install command used:
```
./velero install --provider gcp --bucket <my-bucket> --prefix <my-prefix> --secret-file <my-credentials-file>
```

Backup error:
```
./velero backup create foo
An error occurred: Backup.velero.io "foo" is invalid: []: Invalid value: map[string]interface {}{"kind":"Backup", "apiVersion":"velero.io/v1", "metadata":map[string]interface {}{"name":"foo", "namespace":"velero", "creationTimestamp":"2019-10-03T19:13:26Z", "generation":1, "uid":"e08fcd1a-e611-11e9-a4bc-42010a8a0fc6"}, "spec":map[string]interface {}{"includedNamespaces":[]interface {}{"*"}, "ttl":"720h0m0s", "hooks":map[string]interface {}{}}, "status":map[string]interface {}{"expiration":interface {}(nil), "startTimestamp":interface {}(nil), "completionTimestamp":interface {}(nil)}}: validation failure list:
status.completionTimestamp in body must be of type string: "null"
status.startTimestamp in body must be of type string: "null"
status.expiration in body must be of type string: "null"
```

`velero version` error:
```
./velero version
Client:
	Version:
	Git commit: -
<error getting server version: ServerStatusRequest.velero.io "velero-cli-bxzmn" is invalid: []: Invalid value: map[string]interface {}{"metadata":map[string]interface {}{"namespace":"velero", "creationTimestamp":"2019-10-03T19:13:57Z", "generation":1, "uid":"f3252c72-e611-11e9-a4bc-42010a8a0fc6", "name":"velero-cli-bxzmn", "generateName":"velero-cli-"}, "spec":map[string]interface {}{}, "status":map[string]interface {}{"serverVersion":"", "plugins":interface {}(nil), "phase":"", "processedTimestamp":interface {}(nil)}, "kind":"ServerStatusRequest", "apiVersion":"velero.io/v1"}: validation failure list:
status.plugins in body must be of type array: "null"
status.processedTimestamp in body must be of type string: "null"
status.phase in body should be one of [New Processed]>
```

cc @prydonius

**Comment by prydonius** [comment]
I'm able to reproduce this as well on 1.13. It seems older versions of Kubernetes don't handle null values in the same way, or `nullable` in the schema is not supported. I'll look into this more.

At a quick glance, one solution might be to remove the validations for `status` (or figure out if we can get the velero client to omit it when creating objects, since it's not needed). That said, this might also affect some spec fields also.

**Comment by prydonius** [comment]
r.e. the `velero version` error, I've accidentally missed out the `omitempty` tags for all the status fields, that's why the client is sending null values for these. Also, as per https://github.com/jetstack/cert-manager/pull/1628/files, if we make all `metav1.Time` types pointers, then the `omitempty` works as expected and timestamp fields aren't set to null.

**Comment by prydonius** [comment]
Changing metav1.Time types to pointers introduces some challenges, we'll have to update any code that tries to set or use the timestamps to handle the pointer being nil, otherwise we will get nil pointer panics at runtime. For example: https://github.com/vmware-tanzu/velero/blob/aa9ca9a69d4367ea7604b49118c2143f519dde86/pkg/serverstatusrequest/process.go#L50.

This seems like the right way to go to have the client respect `omitempty` and omit these fields on creation, though it will require some manual testing to ensure we don't break the controllers. It doesn't look like there is any standard way of doing this upstream, `metav1.Time` types are sometimes pointers and sometimes not. 

https://github.com/kubernetes/api/search?p=2&q=metav1.Time&unscoped_q=metav1.Time.
