### ISSUE TITLE
Can not delete job before it starts

### ISSUE THREAD

**Issue by dns2utf8** [vmware-tanzu/velero#2114]
**What steps did you take and what happened:**
Create two backups A and B one after the other:
```bash
velero backup create A 
velero backup create B
```

Get the jobs:
```bash
velero backup get
# ...
# A                            InProgress
# B                            New
```

While A is running, delete B:
```bash
velero backup delete B
```

After A is finished B gets executed.

**What did you expect to happen:**
I expected the B job to not get executed or an error message like "one can only delete completed or failed jobs".

**Anything else you would like to add:**

**Environment:**

* velero version 1.2.0
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.3 LTS

**Comment by skriss** [comment]
As far as I can tell, this is because backup B doesn't have a `spec.storageLocation` assigned when it's created, so the backup deletion controller errors out.  The backup controller assigns the default location to the backup once it starts processing.

We should change something in the deletion controller to either (a) not bother trying to get the BackupStorageLocation for new backups (since there's no need to access them), or (b) assume the default BSL if none is assigned to the backup when trying to delete.

**Comment by skriss** [comment]
A viable workaround would be to `kubectl -n velero delete backup B` for a `New` backup since that wouldn't go through the deletion controller.

**Comment by MadhavJivrajani** [comment]
Hi! I'm a beginner, I was hoping to try this if possible, any advice on how I can get started?
