### ISSUE TITLE
When backing up PV, is there a way to store them in blob storage instead of a Resource Group

### ISSUE THREAD

**Issue by jyee021** [vmware-tanzu/velero#2160]
Running in AKS environment, noticed Velero allows backups of PVs to be in the existing Resource Group or a separate Resource Group.  Is there a way to configure it to write it in a storage account container within Azure?

**Comment by nrb** [comment]
Hi @jyee021!

You can store the contents of your PVs on blob via Velero's [restic integration](https://velero.io/docs/v1.2.0/restic/). This will operate at the file system level, rather than taking PV snapshots, and will be slower, but will store the file data alongside the Kubernetes metadata.

I'm going to close this issue because I believe this answers your question, but feel free to re-open it if that's not the case.
