### ISSUE TITLE
Velero installation in kubernetes server using azure provider

### ISSUE THREAD

**Issue by rohans-mehta** [vmware-tanzu/velero#2282]
While installation of Velero on kubernetes using helm charts as below

helm install --namespace velero \
--set configuration.provider="Microsoft Azure" \
--set-file credentials.secretContents.cloud=<FULL PATH TO FILE> \
--set configuration.backupStorageLocation.name=azure \
--set configuration.backupStorageLocation.bucket=<BUCKET NAME> \
--set configuration.volumeSnapshotLocation.name=<PROVIDER NAME> \
--set configuration.volumeSnapshotLocation.config.region=<REGION> \
--set image.repository=velero/velero \
--set image.tag=v1.2.0 \
--set image.pullPolicy=IfNotPresent \
--set initContainers[0].name=velero-plugin-for-microsoft-azure:v1.0.0 \
--set initContainers[0].image=velero/velero-plugin-for-microsoft-azure:v1.0.0 \
--set initContainers[0].volumeMounts[0].mountPath=/target \
--set initContainers[0].volumeMounts[0].name=plugins \
stable/velero

I have configured the below environment variables in credential-velero file and path has been provided in above command.

credentials-velero file -
AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
AZURE_TENANT_ID=${AZURE_TENANT_ID}
AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
AZURE_CLOUD_NAME=AzurePublicCloud

I am getting below error -
an error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = unable to get all required environment variables: the following keys do not have values: AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, AZURE_SUBSCRIPTION_ID

Could you please help with resolution of above error?

**Comment by jenting** [comment]
This [PR](https://github.com/vmware-tanzu/helm-charts/pull/46) address this issue.

**Comment by skriss** [comment]
This could also be similar to #2272 - my first recommendation would be to inspect the `cloud-credentials` secret in the velero namespace, and ensure that there's a secret key called `cloud` and that the value, when base64-decoded, is properly formed and contains all of the env vars.

Also - does your deployment have the `AZURE_CREDENTIALS_FILE` env var set? (You could paste the full YAML for the deployment here, if you're not sure).

**Comment by jenting** [comment]
> This could also be similar to #2272 - my first recommendation would be to inspect the `cloud-credentials` secret in the velero namespace

Note that, Velero installed with `helm`, the credentials secret name is `velero`.

**Comment by skriss** [comment]
@rohans-mehta were you able to resolve this?

**Comment by rohans-mehta** [comment]
@skriss - Could you please provide detail steps for velero installation using helm command?
I have set the credential-velero file using path -  https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#create-service-principal  and https://github.com/helm/charts/tree/master/stable/velero (new repo - https://vmware-tanzu.github.io/helm-charts/ and helm chart - https://github.com/vmware-tanzu/helm-charts)

Do I need to set anything else or any steps I am missing?

**Comment by ashish-amarnath** [comment]
@rohans-mehta 
Can you please try using our new helm repo at https://vmware-tanzu.github.io/helm-charts/
This is where you will be able to find updates wrt helm3 migration. 

Also, based on your description, it looks like you are not providing a credentials file
`--set-file credentials.secretContents.cloud=`
Can you please follow the steps here https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#create-service-principal to create the credentials file and pass it to the helm install command.

Here are a few other things you may want to try.
1. Inspect, without installing velero into your cluster, the generated yaml by using `template` instead of `install` in the `helm install` command. The whole command as-is, just substituting `template` for `install`. Specifically, you will want to inspect the yaml generated for the credentials secret.
2. To troubleshoot an active failure, please follow the steps below:

- Get a list of all secrets in the namespace where you've deployed `velero`. Per your issue description, this is `velero`
```
kubectl -n velero get secrets
```
- From the above list, identify the secret that has your cloud credentials, and inspect it using the command
```
kubectl get secrets <your secret here> -ojsonpath="{.data['cloud']}" | base64 --decode
```
to confirm that the credentials you have supplied is correct. You may also try to use these credentials locally, to confirm that they are valid.

**Comment by ashish-amarnath** [comment]
@rohans-mehta Checking in to see if you were able to troubleshoot your installation?

**Comment by skriss** [comment]
closing this out as inactive. feel free to reach out again as needed.
