### ISSUE TITLE
Restoring nodePort service that has nodePort preservation always fails if service already exists in the namespace

### ISSUE THREAD

**Issue by betta1** [vmware-tanzu/velero#2308]
**What steps did you take and what happened:**
During restore Velero skips restoring a service if the service already exists in the namespace. However for nodePort services that require node ports to be preserved on restore, restores always fail if the same nodePort service already exists in the target namespace. It seems during the restore Velero tries to create the service on the target namespace but the API server rejects the operation since the node port to be restored is already allocated to the preexisting service. Below steps should help in reproducing this issue:

```
$ kubectl create ns nginx

$ cat <<EOF | kubectl apply -n nginx -f -
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      nodePort: 32555
  selector:
    app: nginx
  type: NodePort
EOF

$ kubectl create deployment nginx --image=nginx -n nginx
$ velero backup create nginx-backup --include-namespaces nginx
$ kubectl delete deployment nginx -n nginx
$ velero restore create --from-backup nginx-backup

```
Restores fail consistently with the error "**provided port is already allocated**":

{"errors":{"namespaces":{"**nginx":["error restoring services/nginx/nginx: Service \"nginx\" is invalid: spec.ports[0].nodePort: Invalid value: 32555: provided port is already allocated"**]}},"warnings":{"namespaces":{"nginx":["could not restore, endpoints \"nginx\" already exists. Warning: the in-cluster version is different than the backed-up version."]}}}

**What did you expect to happen:**
Velero to skip restore of the nodePort service if the service already exists in the target namespace. This maintains restore behavior consistent with how Velero handles restore of other objects it finds in the namespace.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
This issue is closely related to #1950 .

**Environment:**

- Velero version (use `velero version`): v1.2.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by nrb** [comment]
I think the issue is at [this line](https://github.com/vmware-tanzu/velero/blob/master/pkg/restore/restore.go#L1197-L1198). We expect the API server to say that the object already exists if it looks the same, but in the case of NodePorts that are re-using the same port, it gives us a different error - that it's invalid.

I confirmed this by printing out the error, and this is what I saw:

```go
restoreErr was: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"Status", APIVersion:"v1"}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"Service \"nginx\" is invalid: spec.ports[0].nodePort: Invalid value: 32555: provided port is already allocated", Reason:"Invalid", Details:(*v1.StatusDetails)(0xc0007c1680), Code:422}}time="2020-03-04T20:50:34-05:00" level=info msg="error restoring nginx: Service \"nginx\" is invalid: spec.ports[0].nodePort: Invalid value: 32555: provided port is already allocated" logSource="pkg/restore/restore.go:1200" restore=velero/nginx-backup-20200304205033
```

Digging into the `StatusDetails` a little more with the following patch:

```go
		if apierrors.IsInvalid(restoreErr) {
			statusErr := restoreErr.(*apierrors.StatusError)
			fmt.Printf("Err Reason: %#v: ", statusErr.Status().Reason)
			fmt.Printf("Err Details:   %#v", statusErr.Status().Details)
		}
```

```
Err Reason: "Invalid": Err Details:   &v1.StatusDetails{Name:"nginx", Group:"", Kind:"Service", UID:"", Causes:[]v1.StatusCause{v1.StatusCause{Type:"FieldValueInvalid", Message:"Invalid value: 32555: provided port is already allocated", Field:"spec.ports[0].nodePort"}}, RetryAfterSeconds:0}time="2020-03-04T20:57:21-05:00" level=info msg="error restoring nginx: Service \"nginx\" is invalid: spec.ports[0].nodePort: Invalid value: 32555: provided port is already allocated" logSource="pkg/restore/restore.go:1204" restore=velero/nginx-backup-20200304205719
```

So, to fix this for nodePort services, I think we could do the following, which I have not yet tested.

1. After checking for `apierrors.AlreadyExists`, check for `apierrors.IsInvalid`
1. If it is invalid, check the `restoreError.Status().Details.Causes` slice for `nodePort` in `Field` and `already allocated` in `Message`.
1. If all `Causes` match this case, then the `Service` is the same and log it as such instead of erroring.

I'm not 100% happy with this as it relies on a text string in the error message that could change, but I haven't yet checked on the API server side to see what exactly it generates, so maybe there's a better solution.

More generally, chasing down each case like Service Accounts and now Services in the core restore code doesn't seem sustainable. I'm wondering if some sort of `RestoreConflict` plugin type might make sense, which would allow us to specify criteria by which instances of a given type would be considered the same. That's a very rough idea at the moment and would require some more design work.

@skriss and @ashish-amarnath does my rough algorithm seem workable to you? I'll try to track down what the API server does to return the invalid error to see if there's something more reliable than string matching that we can do.

@ajohnstone and @jenting I'm tagging you too as you both commented on the other issue, and I'm able to reproduce, with detailed error structs.

**Comment by nrb** [comment]
Ok, so the error seems to originate [in the port allocator](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/service/portallocator/allocator.go#L128), which is pretty core to Kubernetes. The error is passed directly through the REST API if the port is already allocated, which is why this doesn't show up as `AlreadyExists`.

Looking [around here](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/rest/storage_core.go#L243), I see it uses a `RangeRegistry`, which is similar to how IP address fields are exposed. My guess is that objects that have IPs for allocation will get similar errors when retained, although those have been more dynamic in my experience.

NodePorts have been a far more recurring problem for users of Velero.

**Comment by skriss** [comment]
@nrb that approach sounds reasonable, though I agree that adding lots of special cases here is not going to be sustainable.

Another option we could consider is trying to `Get` the resource before trying to restore it, and use that to determine if the resource exists already. That means an additional API call per resource we're restoring, though, so potentially has some runtime impact.

**Comment by betta1** [comment]
@nrb @skriss How about trying a GET only on the services iff we find the last-applied-config annotation on the service during restore? This way we only make the API call if we're restoring a service that needs node port preservation. If a service does not have the last-applied-config annotation, we simply delete the node ports as we're doing currently and let the API server auto-assign the node ports.

**Comment by nrb** [comment]
> How about trying a GET only on the services iff we find the last-applied-config annotation on the service during restore?

That works for Services applied by Kubectl, but I think it still has the problem of adding special cases as they come up.

Reworking the entire logic to be based on a `Get` vs doing a `Create` and expecting an `AlreadyExists` error may be more useful in more cases, and may also serve us better for doing things like trying to overwrite items that differ from an existing backup, because then we'll have a lot more information about the exact differences versus just information that it already exists.

**Comment by SVronskiy** [comment]
Problem is actual in 1.5.2

**Comment by aireddy73** [comment]
apiVersion: apps/v1 #version of the API to use
kind: Deployment #What kind of object we're deploying
metadata: #information about our object we're deploying
  name: nginx-deployment #Name of the deployment
  labels: #A tag on the deployments created
    app: nginx
spec: #specifications for our object
  replicas: 2 #The number of pods that should always be running
  selector: #which pods the replica set should be responsible for
    matchLabels:
      app: nginx #any pods with labels matching this I'm responsible for.
  template: #The pod template that gets deployed
    metadata:
      labels: #A tag on the replica sets created
        app: nginx
    spec:
      containers:
      - name: nginx-container #the name of the container within the pod
        image: nginx #which container image should be pulled
        ports:
        - containerPort: 80 #the port of the container within the pod
---
apiVersion: v1 #version of the API to use
kind: Service #What kind of object we're deploying
metadata: #information about our object we're deploying
  name: ingress-nginx #Name of the service
spec: #specifications for our object
  type: NodePort #Ignore for now discussed in a future post
  ports: #Ignore for now discussed in a future post
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30001 
    protocol: TCP
  selector: #Label selector used to identify pods
    app: nginx

I am getting 
cloud_user@ControlPlane:~$ k create -f ep.yaml 
deployment.apps/nginx-deployment created
The Service "ingress-nginx" is invalid: spec.ports[0].nodePort: Invalid value: 30001: provided port is already allocated

when I changed to default port 30000 everything works as expected, where 30001 being used, I am not able to use any port other than 30000 in my Kubernetes cluster.

**Comment by ywk253100** [comment]
> Reworking the entire logic to be based on a `Get` vs doing a `Create` and expecting an `AlreadyExists` error may be more useful in more cases, and may also serve us better for doing things like trying to overwrite items that differ from an existing backup, because then we'll have a lot more information about the exact differences versus just information that it already exists.

There are still issues even though we do `Get` first: 
-  If the `Get` returns nil, we'll `Create` the resource, but there is a chance that the resource is created by others between we do the `Get` and `Create`, it is a very low chance but it is possible.
- We also need to handle the corner case for `NodePort` service specifically. 
Imagine that `Get` returns an already existing `NodePort` service named `in-cluster-service` and then we need to do the deep equal [here](https://github.com/vmware-tanzu/velero/blob/v1.7.0/pkg/restore/restore.go#L1255) between the `in-cluster-service` and the `restore-service`. 
  - If we don't preserve the `nodePort` when doing the backup, we should remove the `nodePort` from the `in-cluster-service` before doing the deep equal.
  - If we preserve the `nodePort` when doing the backup, we don't need to do the removal. 

So the following solution proposed by @nrb may be more reasonable:
> So, to fix this for nodePort services, I think we could do the following, which I have not yet tested.
> 
> 1. After checking for `apierrors.AlreadyExists`, check for `apierrors.IsInvalid`
> 2. If it is invalid, check the `restoreError.Status().Details.Causes` slice for `nodePort` in `Field` and `already allocated` in `Message`.
> 3. If all `Causes` match this case, then the `Service` is the same and log it as such instead of erroring.
>

**Comment by ywk253100** [comment]
A similar error may happen for `LoadBalancer`(healthCheckNodePort) as well, but the returning error isn't an invalid value error, it's an internal error: ` error restoring services/default/loadbalancer-service: Internal error occurred: failed to allocate requested HealthCheck NodePort 30092: provided port is already allocated`.

Submit PR https://github.com/vmware-tanzu/velero/pull/4462 to fix this

**Comment by ywk253100** [comment]
https://github.com/vmware-tanzu/velero/pull/4336 didn't make sure the `invalid value/internal` error comes from the same name service. So if there is another service with the same `NodePort`, the restore should fail rather than ignoring the error
