### ISSUE TITLE
Restore is failing when trying to backup from a cluster in one region to a cluster in another region.

### ISSUE THREAD

**Issue by rashmigspai** [vmware-tanzu/velero#2334]
I am trying to use Velero for DR solution. Taken backup from a cluster which is in a region say Dallas. There are PVC to backup as well. PVC's are having the region dallas against them , when trying to restore the back in another cluster say which is in Washington DC, restore is failing. Restore creates the PVC but then they are against the region Dallas , and pods are trying to get created in Washington DC which causes pods to fail to initialize. Please guide on how can i change the region in PVC when restoring in new cluster.

Velero version:

Client:
        Version: v1.3.0
        Git commit: 8fec8ed7fb8b4776b191753497eafeb47f2f9136
Server:
        Version: v1.3.0

Using Velero with restic

**Comment by skriss** [comment]
@rashmigspai Velero doesn't generally support cross-region backup & restore, primarily because volume snapshots are typically bound to a single cloud provider region, and to restore into another region requires first copying the snapshot into the target region.

We already have some enhancement requests in the backlog related to this - primarily #103. Please add any further information that you have to that issue. I'll be closing this one out since we don't currently support this within Velero.
