### ISSUE TITLE
Velero site missing vSphere installation and configuration instructions

### ISSUE THREAD

**Issue by jedsalazar** [vmware-tanzu/velero#2356]
**Describe the problem/challenge you have**
The Velero website site doesn't include installation and configuration instructions for the vShpere provider

**Describe the solution you'd like**
A link in the provider page to install and configuration instructions for vSphere

**Anything else you would like to add:**
Referencing the latest Velero page here
https://velero.io/docs/v1.3.1/supported-providers/

**Environment:**
N/A
- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
@jedsalazar the vSphere VolumeSnapshotter plugin hasn't quite been released yet, which is why we don't have it listed. You can find the in-development code and docs for it here, though: https://github.com/vmware-tanzu/velero-plugin-for-vsphere

This blog post also goes through using Velero with its restic integration on vSphere: https://velero.io/blog/velero-v1-1-on-vsphere/ (note that there's not really anything vSphere-specific about this setup).
