### ISSUE TITLE
Restic restores original PV rather than dynamically reprovisioning empty volume (restic)

### ISSUE THREAD

**Issue by sseago** [vmware-tanzu/velero#2366]
**What steps did you take and what happened:**
Create an application with a pod that has a mounted volume
Set the "backup.velero.io/backup-volumes" annotation, naming the volume for restic
The volume is empty (basically make sure there are no files or directories in the volume)
Run a backup
The PodVolumeBackup has the following:
```
status:
  completionTimestamp: 2020-03-25T18:48:29Z
  message: volume was empty so no snapshot was taken
```
Next I ran a restore. We happen to have a plugin which changed the storageclass, so the restic-related behavior of not restoring the PV to allow dynamic reprovisioning is important here.
What I observed was that the PV was restored rather than dynamically reprovisioned.

More specifically, at this point:
https://github.com/vmware-tanzu/velero/blob/master/pkg/restore/restore.go#L916
`case hasResticBackup(obj, ctx)` would have matched if there had been data on the volume and restic had created a snapshot, but instead if did not match. Instead, the following block was executed:
https://github.com/vmware-tanzu/velero/blob/master/pkg/restore/restore.go#L930-L940
`Restoring persistent volume as-is because it doesn't have a snapshot and its reclaim policy is not Delete`

**What did you expect to happen:**
I would expect the block under `hasResticBackup` to have executed, forcing reprovisioning of the volume. It's probably OK that there's no restic snapshot, since reprovisioning (and not restoring) would be equivalent to reprovisioning and restoring an empty volume, although if there were a way to allow restic to create and restore snapshots that happen to have no files in them, that would probably be cleaner.

**The output of the following commands will help us better understand what's going on**:
(unfortunately I no longer have the logs -- I should have kept them, but I think this will be reasonably easy to reproduce with an empty mounted volume in a pod)

**Environment:**

- Velero version (use `velero version`): A custom build of velero based on the 1.3.1 release with some local changes
- Velero features (use `velero client config get features`): "<NOT SET>"
- Kubernetes version (use `kubectl version`): 1.11 for the backup, 1.14 for the restore
- Cloud provider or hardware configuration: aws
- OS (e.g. from `/etc/os-release`): Client on Fedora 29

**Comment by skriss** [comment]
it looks like what's happening is that during backup, https://github.com/vmware-tanzu/velero/blob/master/pkg/restic/backupper.go#L176-L179 does not return the PodVolumeBackup if the volume was empty, so it doesn't get persisted with the backup. As a result, on restore, it goes through the code path you're seeing.

We can look at removing that code, persisting the empty PVBs, and then excluding them on restore since there's no snapshot to restore. It actually looks like they should already be excluded on restore (see https://github.com/vmware-tanzu/velero/blob/master/pkg/restic/common.go#L96-L100, which is in a function used at https://github.com/vmware-tanzu/velero/blob/master/pkg/restic/restorer.go#L95) so it's possible that just deleting that code from backupper.go will solve it.

**Comment by skriss** [comment]
@sseago it also appears that this is only an issue when the restore is on a different cluster than the backup - does that match what you were seeing?

Currently testing out the change mentioned above, namely deleting https://github.com/vmware-tanzu/velero/blob/master/pkg/restic/backupper.go#L176-L179. So far it seems to fix the issue and work as expected, but I need to do some more testing.

**Comment by sseago** [comment]
@skriss I was restoring to a different cluster when I observed it, but I'm not sure if the cluster change is all that relevant. What made it obvious to me that something was off was the storageclass change. The backup was from an NFS volume with statically-generaed PVs, so it had a name like "vol95". I was restoring it as an ebs/gp2 volume, so I expected to see a PV name post-restore that looked like "pvc-037725c9-6f9a-11ea-866f-02e5ce94b826" -- i.e. newly provisioned upon restoring the PVC, but instead "vol95" was restored (following the "default" code path, as it didn't meet the criteria for discarding the PV).

**Comment by skriss** [comment]
Makes sense. 

It looks to me like the issue only comes up when restoring to a different cluster because, if restoring in the same cluster, there *is* a PodVolumeBackup in the cluster representing the empty restic backup, which signals to the restore that the volume was backed up with restic. However, that PVB is not currently persisted to object storage, so when the backup is synced into another cluster, the PVB no longer exists, which is why the restore is unaware that the volume was "backed up" (empty) with restic.

**Comment by sseago** [comment]
Oh. Right, I missed that. Well, it's also possible that this would still happen if the PodVolumeBackup was deleted on the cluster, but yes, if the PodVolumeBackup is still there, this won't happen.
