### ISSUE TITLE
Improve the `velero backup-location` command

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#2425]
- [x] --cacert [set|create] https://github.com/vmware-tanzu/velero/pull/3167
- [x] --default [set|create|get] https://github.com/vmware-tanzu/velero/pull/3092
- [ ] --credentials [set|create] https://github.com/vmware-tanzu/velero/pull/3190

**Comment by nrb** [comment]
@carlisia Can you detail what improvements are required, as someone else is taking up this work?

**Comment by carlisia** [comment]
Yes, so, the specs for all of the new commands are linked in the epic (https://github.com/vmware-tanzu/velero/issues/2419). I didn't want to copy/paste that into every single one.

**Comment by jenting** [comment]
> * [ ]  --credentials [set|create] WIP

For the credentials part, I think it related to how Velero enhances the multiple credential secrets #2403.

**Comment by carlisia** [comment]
@jenting absolutely. I have started looking into this as part of reviewing the multiple secrets design. I am running some tests so I can understand what is possible. For example, it seems that it is possible to have multiple entries for the same provider, example:

```
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/cloud4
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/cloud5
```

**It seems* to me that as long as either `cloud4` OR `cloud5` contains a valid credentials, the plugin will work. I want to run more tests to confirm this conclusively. If this is true, then my question is: does the BSL need to specify which credential? Seems that only configuring the BSL for the provider would be enough, meaning, no change needed to the BSL. Unless, we want a BSL to ONLY work with credential X (valid), but not with credentialY (also valid). 

I don't fully understand what needs to be done yet but yes, they are coupled.

**Comment by carlisia** [comment]
@jenting let me know if you have any idea how to handle this or if you want to work on implementing this change.

**Comment by jenting** [comment]
🤔  I read the CLI change design doc https://github.com/vmware-tanzu/velero/blob/master/design/cli-install-changes.md and I found that there is another command to configure the plugin credential `velero plugin set --credentials-file`. I don't know what's the difference against `velero backup-location set --credentials` because currently, I don't know will the plugins other than AWS/GCP/Azure/CSI have to configure credentials? If not, then I don't know why we have to keep the `velero plugin set --credentials-file`.

Anyway, from our use case, we have a scenario that at on-premise K8s cluster, we'd like to have 2 BSLs: one back up to local Minio server; the other one back up to AWS S3. Then, each BSL would have a different credential but the problem is how to enhance the Velero server could differentiate passing different credential file with the same key `AWS_SHARED_CREDENTIALS_FILE`?

**Comment by carlisia** [comment]
I understand your questions. I'm running some experiments to help figure out both what we want to do and what we can do.

The idea with the `velero plugin set --credentials-file` is this cmd will add 1.* credentials for a given plugin. Right now the plugins already use the credential. We are aiming to not have to modify the plugins to do this change. The `velero backup-location set --credentials` would specify which credential the BSL would need.
