### ISSUE TITLE
Custom service account token not restore

### ISSUE THREAD

**Issue by myazid** [vmware-tanzu/velero#2524]
**What steps did you take and what happened:**
We had set "automountServiceAccountToken: false" in our deployment file and manually create a service account user secret token e.g call "app-user-token" and volumemount the token manually in the deployment file. After the restore, it creates a secret token "app-user-token-xxxxx" and the deployment could not start because the volume expect "app-user-token"

**What did you expect to happen:**
We expect the restore to create the secret name as we had define a secret "app-user-token".

```
apiVersion: v1
kind: Secret
metadata:
  name: app-user-token
  namespace: app
  annotations:
    kubernetes.io/service-account.name: app-user
type: kubernetes.io/service-account-token
```

in the deployment
```
          volumeMounts:
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: app-user-token 
```

secret before backup
`app-user-token           kubernetes.io/service-account-token   3      4m37s`

secret after backup
`app-user-token-8zms6     kubernetes.io/service-account-token   3      23m`

**The output of the following commands will help us better understand what's going on**:
`Warning  FailedMount  40s (x4 over 7m28s)   kubelet, kind-worker3  Unable to attach or mount volumes: unmounted volumes=[app-user-token], unattached volumes=[app-user-token]: timed out waiting for the condition`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v1.3.2
	Git commit: 55a9914a3e4719fb1578529c45430a8c11c28145
Server:
	Version: v1.3.2
```
- Velero features (use `velero client config get features`): 
`features: <NOT SET>`
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-25T06:32:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
Kind 0.7.0
- OS (e.g. from `/etc/os-release`):
Mac OSX

**Comment by ashish-amarnath** [comment]
@myazid Thanks for opening this issue.
Just so I understand the problem correctly. During restore, you found that the `app-user-token` secret wasn't restored?

Could you please confirm that the secret was present in the backup that was restored? You can do this by:
1. Downloading the backup tarball
```
velero backup download <backupName> -o <filepath.tar.gz>
tar xvzf <filepath.tar.gz>
```
2. Inspecting the contents of the resources directory.

Can you also please confirm that the backup and restore both completed without failures?

**Comment by myazid** [comment]
@ashish-amarnath Thanks.

1. Secret file exists
I've checked the backup files have the secrets app-user-token.json

2. Restore completed
velero time="2020-05-11T23:57:03Z" level=info msg="restore completed" logSource="pkg/controller/restore_controller.go:473" restore=velero/backup-manual-2020-05-12-07-46-32-20200512075559

3. Logs - grep app-user-token
time="2020-05-11T23:56:11Z" level=info msg="Attempting to restore Secret: app-user-token-c82lr" logSource="pkg/restore/restore.go:1136" restore=velero/backup-manual-2020-05-12-07-46-32-20200512075559
time="2020-05-11T23:56:11Z" level=info msg="Attempting to restore Secret: app-user-token" logSource="pkg/restore/restore.go:1136" restore=velero/backup-manual-2020-05-12-07-46-32-20200512075559

4. No secret "app-user-token" created
⇒  kubectl get secrets
NAME                       TYPE                                  DATA   AGE
default-token-7msvd        kubernetes.io/service-account-token   3      10m
app-docker-credentials   kubernetes.io/dockerconfigjson        1      10m
app-user-token-r8rb5     kubernetes.io/service-account-token   3      10m

**Comment by ashish-amarnath** [comment]
So, service account tokens are usually not portable across clusters because, IIRC, the cluster's CA cert is used in the process of generating these tokens. (Not entirely sure how they are used though)
For this reason, when velero detects that a service account already has a token generated for it in the cluster, it will skip restoring the secret that was in the backup. Here is the code that does this:
https://github.com/vmware-tanzu/velero/blob/48792ece1f6b10d732b57477059a6b32dd10e25d/pkg/restore/service_account_action.go#L46-L79 

So because you already have 
>```
>app-user-token-r8rb5 kubernetes.io/service-account-token 3 10m
>```
secret in your cluster restoring of `Secret: app-user-token-c82lr` is skipped.

**Comment by ashish-amarnath** [comment]
@myazid I am going to close out this issue. If you still have questions, please feel free to re-open and comment.

**Comment by akhila260** [comment]
@myazid  Do you still have this issue? If not, could you please share the steps for the fix. Thanks!

**Comment by nyarly** [comment]
We encountered this, which I think explains https://github.com/vmware-tanzu/velero/discussions/4051. Our solution has been to manually recreate the secret resource and let Kubernetes repopulate the secrets.

**Comment by kasabov** [comment]
Another solution is to create the service account and the service-account-token secret in another namespace (I use "kube-system" but afaik any other namespace should work) so that it's retained across backup restores. Only the rolebinding should be present in the restored namespace.

**Comment by blackpiglet** [comment]
Regarding the original issue, as [Ashish](https://github.com/ashish-amarnath) pointed out, Velero skips the default service account token by design.
I agree this is inconvenient in some scenarios where users want to have their token instead of the default ones, but that should be the correct behavior.

@kasabov 
Thanks for your input.
It's nice to know the RoleBinding supports binding a ServiceAccount in a different namespace.
But it seems that it cannot help in the customized ServiceAccount Token secret issue.
Because your proposal is moving the Role and RoleBinding into a namespace not included in the backup namespace, that will avoid the Role and RoleBinding conflicts, but the issue here is the ServiceAccount referenced Token secret is not restored.

**Comment by kasabov** [comment]
> moving the Role and RoleBinding into a namespace not included in the backup namespace

No, RoleBinding remains in the backed up namespace. The rest (Role?, SA and Token secret) remain in non-backed up namespace. This allows them to retain across restores. 

Of course, this only works for restores in the same cluster. Migrating to another cluster (and/or cloud) is still an issue but not a big one for us because we normally want to provision new clusters with new services accounts anyway.

**Comment by blackpiglet** [comment]
```
	// RoleRef can reference a Role in the current namespace or a ClusterRole in the global namespace.
	// If the RoleRef cannot be resolved, the Authorizer must return an error.
	// This field is immutable.
	RoleRef RoleRef `json:"roleRef" protobuf:"bytes,3,opt,name=roleRef"`
```

I'm curious about how you do that. The `RoleRef` doesn't support cross-namespace referencing.
Do you mean you bind the `RoleBinding` to a `ClusterRole`?

**Comment by kasabov** [comment]
Correct. Here's the code I use:
```
#!/usr/bin/env bash
set -euo pipefail

# The service account and secret are created in kube-system namespace.
# The rolebinding is in the target namespace.
# This way the service account token is retained across
# namespace deletion during backup restores.

NS=${1:-${NS:-rnd-devops1}}
USER=${2:-${USER:-kasabov}}

kubectl -n kube-system create serviceaccount $NS-$USER
kubectl -n kube-system apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: $NS-$USER
  annotations:
    kubernetes.io/service-account.name: $NS-$USER
type: kubernetes.io/service-account-token
EOF
kubectl -n $NS create rolebinding $NS-$USER --clusterrole=admin --serviceaccount=kube-system:$NS-$USER

echo "Created account '$USER' for namespace '$NS' with token: "
kubectl -n kube-system get secret $NS-$USER -o jsonpath='{.data.token}' | base64 -d
```

**Comment by blackpiglet** [comment]
Ah, thanks a lot for the detailed information.
That is a useful workaround in this scenario.
