### ISSUE TITLE
Help: Validation error on ambigious volume snapshot location for non-volume-snapshot backups

### ISSUE THREAD

**Issue by henkypunky** [vmware-tanzu/velero#2549]
Not sure if this is the right way for opening kind of a "Help Wanted" issue, please forgive if not..
I am facing the issue that a backup fails with this validation error:

_Validation errors:  provider openebs.io/cstor-blockstore has more than one possible volume snapshot location, and none were specified explicitly or as a default_

This is irritating as the command used for creating this backup had the option --snapshot-volumes=false so I think this validation check is actually unnecessary in this case. I am enforced to specify an explicit volume snapshot location --volume-snapshot-locations openebs.io/cstor-blockstore:openebs-cstor in order to overcome this error. Is this works as designed? If so, what is the rational behind the validation check in this context?

I am on Velero v1.3.0

Thanks!

**Comment by skriss** [comment]
hey @henkypunky, this has actually been fixed in `master` by Mayank from OpenEBS and will be released shortly in v1.4 (we're currently planning to release next week). See https://github.com/vmware-tanzu/velero/pull/2450.

I'm going to close this out since we've got a fix in; keep an eye out for the new release next week!

**Comment by henkypunky** [comment]
hi @skriss , great, thanks!
