### ISSUE TITLE
Run Velero as standalone app outside of k8s cluster

### ISSUE THREAD

**Issue by mazzy89** [vmware-tanzu/velero#2571]
**Describe the problem/challenge you have**

Running Velero out of k8s. It seems not documented.

**Describe the solution you'd like**

Running Velero as a Docker container in an EC2 instance and backup EBS volumes attached to it.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by mazzy89** [comment]
Thank you @nrb to react on this. I meant however if Velero could be used outside the scope of kubernetes. Like running it as a standalone docker container on an ec2 instance on AWS and backing up volumes. But as far as I understand seems not the case because it requires to be pointed to a running kubernetes cluster.

**Comment by nrb** [comment]
Ah I see now. I’m sorry, I misunderstood your question.

Yes, right now Velero’s targeted only at Kubernetes. It’s not a general backup tool, or even a container backup tool - it is specific to Kubernetes.

That may change in the future, but that’s not in the roadmap and hasn’t been how we’ve designed it so far.

Since we’re unlikely to change direction on this any time soon, I’m going to close the issue, but it may be re-opened in the future.
