### ISSUE TITLE
full backup for aks cluster is partially failing

### ISSUE THREAD

**Issue by NMark02** [vmware-tanzu/velero#2591]
**What steps did you take and what happened:**
command:
velero backup create full-cluster-backup --wait

**What did you expect to happen:**
backup ending successfully

velero backup get
NAME                  STATUS                      CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
full-cluster-backup   PartiallyFailed (1 error)   2020-05-29 13:49:49 +0000 UTC   29d       default            <none>

- `kubectl logs deployment/velero -n velero | grep "error"
time="2020-05-29T13:50:09Z" level=info msg="1 errors encountered backup up item" backup=velero/full-cluster-backup logSource="pkg/backup/backup.go:444" name=metrics-server
time="2020-05-29T13:50:09Z" level=error msg="Error backing up item" backup=velero/full-cluster-backup error="clusterroles.rbac.authorization.k8s.io \"system:auth-delegator\" not found" error.file="/github.com/vmware-tanzu/velero/pkg/backup/item_backupper.go:344" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*itemBackupper).executeActions" logSource="pkg/backup/backup.go:448" name=metrics-server

- kubectl logs deployment/velero -n velero | grep "fail"
time="2020-05-29T13:49:52Z" level=info msg="label \"failure-domain.beta.kubernetes.io/zone\" is not present on PersistentVolume" backup=velero/full-cluster-backup logSource="pkg/backup/item_backupper.go:423" name=pvc-2e448a21-21ae-4591-81e0-cd3113954402 namespace= persistentVolume=pvc-2e448a21-21ae-4591-81e0-cd3113954402 resource=persistentvolumes
time="2020-05-29T15:01:44Z" level=info msg="label \"failure-domain.beta.kubernetes.io/zone\" is not present on PersistentVolume" backup=velero/bk-ingress-05 logSource="pkg/backup/item_backupper.go:423" name=pvc-2e448a21-21ae-4591-81e0-cd3113954402 namespace= persistentVolume=pvc-2e448a21-21ae-4591-81e0-cd3113954402 resource=persistentvolumes

**Environment:**
- Velero version (use `velero version`): 
Client and server :
	Version: v1.4.0

- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"059c666b8d0cce7219d2958e6ecc3198072de9bc", GitTreeState:"clean", BuildDate:"2020-04-03T15:17:29Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"

- Kubernetes installer & version:
- Cloud provider : Azure (AKS)

**Comment by skriss** [comment]
@NMark02 when Velero backs up a RoleBinding or ClusterRoleBinding that references a non-existent Role or ClusterRole, it reports an error like this. We're going to change this behavior to warn rather than error in the next release (see #1878).

In the meantime, it looks like you have a `ClusterRoleBinding` referencing the `system:auth-delegator` `ClusterRole`, which doesn't exist. The following should help you find that `ClusterRoleBinding`. You should probably either delete it, or update it to reference a valid `ClusterRole`.

```bash
kubectl get clusterrolebindings -o custom-columns=name:.metadata.name,clusterrole:.roleRef.name | grep system:auth-delegator
```

**Comment by NMark02** [comment]
@skriss thanks for the command. I ran it and this is the output I get:

kubectl get clusterrolebindings -o custom-columns=name:.metadata.name,clusterrole:.roleRef.name | grep system:auth-delegator
metrics-server:system:auth-delegator   system:auth-delegator

**Comment by skriss** [comment]
Yep so the `metrics-server:system:auth-delegator` ClusterRoleBinding is invalid since it's referencing a non-existent ClusterRole. I'd suggest either deleting it if it's not needed, or fixing it to reference a ClusterRole that exists. Once you do that, the velero backup should succeed.

I'm going to close this out, but feel free to reach out again as needed!

**Comment by NMark02** [comment]
@skriss thanks so much!
