### ISSUE TITLE
Support retrieving chunked lists of items when backing up

### ISSUE THREAD

**Issue by ncdc** [vmware-tanzu/velero#262]
Kuberentes 1.9 adds support for chunked lists. We should do this. See https://github.com/kubernetes/website/pull/6540/files#diff-dd99945fd91d7ea569799a45d59669f0R90.

**Comment by ncdc** [comment]
Need to use `k8s.io/client-go/tools/pager` from client-go v6. I am doing the work to upgrade us to v6, so this can come afterwards.

**Comment by nrb** [comment]
Will this force the minimum required version up?

**Comment by ncdc** [comment]
No, I believe the helper in client-go retrieves the full list of paging isn't supported by the server.

**Comment by rosskukulinski** [comment]
This falls under the performance improvement category.  Until we have better metrics (#531) to understand the performance of Ark on larger clusters, I recommend reprioritizing this effort.

That said, it could be interesting to test Ark against some of the large Gimbal clusters that are being used for performance testing. [cc: @alexbrand ]

**Comment by eleanor-millman** [comment]
What: Say I want to grab a list of all CRDs in the cluster and there are a ton of them (10k) because there are a lot of apps installed. This would let me set the number of results I get back from the k8s API server at one time. Note that all of this metadata would still go into the same backup.

Currently, Velero just asks for all k8s resources. The k8s API server has a limit of how many resources it returns at a time. If a cluster is at this size, then Velero will not receive all the resources needed for the backup (or may get an error). Both of these things are bad.

Why: we have been seeing bugs related to lots of k8s resources being backed up at once. Implementing this feature may resolve many of those bugs.

**Comment by afcollins** [comment]
Pitching in my support for this feature, as I found velero-backup to be fetching 26k secrets in one go, which is a 2.6s etcd query, as opposed to 300ms per fetch for chunks of even 10k secrets.

**Comment by eleanor-millman** [comment]
@afcollins Just to clarify, are you saying that you want to help make a PR, or just that you think it is worthwhile to do? We are hoping to get this done in 2021, but because we are stretched quite thin, it's not a certainty. So if you do have any interest in working on this, please let us know!

**Comment by dharmab** [comment]
We've seen this cause consistent backup failure at certain large scales.

@eleanor-millman can you or another Tanzu dev provide guidance on what parts of the code would need to be changed for a contributor to implement pagination? Specifically, 

- what parts of the code govern the LIST queries?
- Are there any metrics or logging that would need to be updated with new behavior?
- At a minimum, I think we'd want to add a flag to control the page size, as well as a `0` value to disable paging. Any other foreseeable configuration that would be needed?

**Comment by eleanor-millman** [comment]
@dharmab Sorry to hear that this is causing failure for you, but it is helpful to have the data point.

I'm afraid I don't have the technical knowledge to answer your question (I'm the PM), but one of the engineers can hopefully point you in the right direction. I'll post this in #velero-dev slack channel in case they don't see it here. Be warned that we have a number of people on vacation this week and the next few weeks, so you might see a bit of a delay in answering.

**Comment by nrb** [comment]
@dharmab This work would mostly reside inside `pkg/backup`, and primarily [`item_collector.go`](https://github.com/vmware-tanzu/velero/blob/main/pkg/backup/item_collector.go). These calls are using generic `List` calls without pagination. The majority of the work happens [when doing a List for the given resource](https://github.com/vmware-tanzu/velero/blob/main/pkg/backup/item_collector.go#L292). There may be other spots we call List too, most of them being within `pkg/backup`.

In terms of metrics, this is a part of the backup that's not instrumented to my knowledge. All of our metrics are defined via the [`metrics` package](https://github.com/vmware-tanzu/velero/blob/main/pkg/metrics/metrics.go), and we'd certainly be open to adding ones that make sense for Kubernetes resources.

**Comment by dharmab** [comment]
I did a little poking around. The main issue I ran into is that the resource clients used by item_collector return [unstructured lists](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured#UnstructuredList) instead of [the native List type](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#List). Unstructured lists don't provide metadata, so the Continue value needed to split the List() request is unavailable. The client interfaces are defined in `pkg/client/dynamic.go`. They seem to also be used in the restore package, so modifying them would require substantial changes to Velero as I understand it.

Perhaps a special case client could be used in item_collector which returns the List with metadata, instead of using the dynamic client.

What are your thoughts here?

**Comment by dharmab** [comment]
I'm work-in-progress on the patch. Some of the commands in the contributing docs don't work on my machine (macOS, bash 5, Docker for Mac):

```
[velero]$ make update
make: realpath: Command not found
make[1]: realpath: Command not found
Trying to pull build-image: velero/build-image:3fb57c6b
docker pull -q velero/build-image:3fb57c6b || /Library/Developer/CommandLineTools/usr/bin/make build-image
Error response from daemon: manifest for velero/build-image:3fb57c6b not found: manifest unknown: manifest unknown
make[2]: realpath: Command not found
error: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -

Start a build
make[2]: *** [build-image] Error 1
make[1]: *** [build-env] Error 2
make: *** [update] Error 2
[velero]$ make lint
make: realpath: Command not found
make[1]: realpath: Command not found
Trying to pull build-image: velero/build-image:3fb57c6b
docker pull -q velero/build-image:3fb57c6b || /Library/Developer/CommandLineTools/usr/bin/make build-image
Error response from daemon: manifest for velero/build-image:3fb57c6b not found: manifest unknown: manifest unknown
make[2]: realpath: Command not found
error: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -

Start a build
make[2]: *** [build-image] Error 1
make[1]: *** [build-env] Error 2
make: *** [lint] Error 2
```

**Comment by dharmab** [comment]
Draft PR is created. I tested on a cluster where I created thousands of Secrets, then tested creating backups with `--client-list-limit` of `0` and `500`. In both cases I had successful backups.
