### ISSUE TITLE
Procedure for Migrating the Kubernetes cluster from one DC to Another DC with New IP change 

### ISSUE THREAD

**Issue by ganesan-cmd** [vmware-tanzu/velero#2681]
Hi Team , 
We are Planing to Migrate the 3 node Kubernetes cluster from One On-prem DC to another On-perm DC,. In that we will be changing the IP address of All the 3 Nodes. Kindly help ,is there standard procedure for migrating the Kuberetes cluster from one DC to another DC with New IP and to resume my container services back to work as like in the Old DC IP .

**Comment by nrb** [comment]
Hi @ganesan-cmd, Velero explicitly omits `Nodes` from the restore process since these resources are highly environment specific. As such, the IPs of the nodes are also not restored or migrated.

The recommended procedure is to take a backup on the original cluster (cluster A), create a new cluster (cluster B), install Velero on cluster B, then run the restore. All pods, deployments, statefulsets, services, etc will be recreated.

I'm going to close this issue out, but feel free to respond if I haven't fully answered your question.
