### ISSUE TITLE
Create a way to do only cluster-scoped resource backup

### ISSUE THREAD

**Issue by henkypunky** [vmware-tanzu/velero#2794]
I am about to create a backup of all cluster-scoped resources only using these options:

--incl_namespaces="" --incl_clusterresources=True

Seems to work except for the fact that the namespace resources which are actually cluster-scoped resources are excluded from the backup. Is there an alternative way to get a backup of cluster-scoped resources including the namespaces (w/o its content)? 
I guess you can't omit the incl_namespaces="" clause as it defaults to include all namespaces (and its resources).

Thanks!

**Comment by ashish-amarnath** [comment]
@henkypunky I don't see a straightforward way to do this.
The best I could come up with was to use the `--exclude-resources` and `--include-resources` options for the `velero backup create` command.
I am going to mark this as an enhancement request rather than a question so that there is a more straightforward way to do this.

**Comment by henkypunky** [comment]
@ashish-amarnath Thanks for quick response and action!

**Comment by eleanor-millman** [comment]
Closing because a workaround exists.
