### ISSUE TITLE
Document why restic must backup pod volumes instead of PersistentVolumes/PVCs

### ISSUE THREAD

**Issue by s405121** [vmware-tanzu/velero#2887]
Hi There,

Am working on a requirement to backup volumes and a couple kubernetes objects on an OpenShift cluster. So I went ahead and setup velero on that cluster. But now when am trying to run backup command like below, I do see kubernetes objects for PersistentVolume are backed up but no backups are running for restic components. Are there any options available providing the flexibility to backup few kubernetes objects and also trigger volume backups through restic. 

velero backup create velero.2020.08.31 --include-namespaces automation-test --include-resources PersistentVolume -n velero

Thanks,

Chaitanya Kosaraju

**Comment by nrb** [comment]
@s405121 Currently, a limitation of Velero's restic support is that it must back up the data through a pod volume rather than a PersistentVolume directly.

It does this because Velero cannot mount the PersistentVolume into its own pod while it's mounted to its workload, so it uses the node's host file path to access the data, and that information is obtained from the Pod.

I'm going to mark this as a documentation issue, since we should add this to https://velero.io/docs/v1.4/restic/#limitations
