### ISSUE TITLE
General Guidance

### ISSUE THREAD

**Issue by kaviarasan-ex2** [vmware-tanzu/velero#2907]
Hi,
We wanted to understand how does the support mechanism works with SLA defined.

Does Velero has any support mechanism in place like enterprise / support model with the cost? Or it's purely on open source?

**Comment by stephbman** [comment]
Hi @kaviarasan-ex2 Velero does offer an enterprise level support option for users who are using the signed VMware binary and who have purchased the VMware Tanzu Kubernetes Grid (TKG) Plus support entitlement. You must have both in order to receive enterprise support with SLA. 

Outside of this, the support model continues to be open source. 

You can learn more about the TKG Plus technology ecosystem here:  https://kb.vmware.com/s/article/78173

**Comment by ashish-amarnath** [comment]
@kaviarasan-ex2 I am going to close this issue as your question has been answered.
You may also find the information at https://velero.io/community/ useful.
