### ISSUE TITLE
General timeline for a release

### ISSUE THREAD

**Issue by ashish-amarnath** [vmware-tanzu/velero#2935]
Following up on the discussion on the community meeting on 9/15.

Asking the below questions:
1. What is the general timeline for a release, from a pre-release to a GA release
1. Should we continue shipping pre-release beta (one or more as needed) followed by a GA release or should we ship pre-release versions, followed by a release candidate, and eventually a GA release?
1. As a Velero user, can I deduce the release date for a GA release from the release date of the pre-release, or the release candidate release?
1. Will this cadence and process be applicable to the plugins as well? In the past, there have not been pre-releases or release candidates for plugins.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment]
I'd like to timebox the decision for v1.6 to Friday, September 25th so we have something and go with it. That's not to say it will be perfect or can't change in the future, I just would like to see things decided by then.

My thoughts:

1. Generally, releases will be on a 3 month cycle. Pre-releases will start coming out when features are roughly complete, and are largely discretionary, but probably 1-2 months in.
2. We should release betas (and if the team deems necessary, alphas) to get early feedback from the community about features and how they work. Release candidates offer a "feature complete" package and would be used primarily to look for bugs. In my opinion, release candidates should not be used in production.
3. I don't think there should be only 1 pre-release, which the wording the question suggests. Pre-releases should be tools, and limiting ourselves to one is too restrictive; it becomes much harder to respond to feedback that way. However, I think our main goal for release candidates should be 1-2 weeks from RC to GA, in order to provide both time to test/react and for people to accurately predict when GA will happen.
4. Yes, I think the process should also apply to plugins to be consistent.

So my proposed timelines:

Betas when features are roughly complete, and 1 week between them.
Once an RC is created, 1-2 weeks (open to discussion here) until cutting the GA release.

**Comment by dsu-igeek** [comment]
I think this is good.  Our goal should be for beta builds to be passing all of our existing tests and to add tests for new functionality prior to RC.  By the time we get to RC we should be very confident it will pass final test.  Having bugs found in the RC should not be expected, so we don't build slack into the schedule for bug fixes post-RC, but we leave ourselves the option of postponing the release if bugs are found in the RC build.  I think 1 week RC->GA is reasonable.

**Comment by carlisia** [comment]
> Betas when features are roughly complete, and 1 week between them.
Once an RC is created, 1-2 weeks (open to discussion here) until cutting the GA release.

I think this is a good cadence.

**Comment by nrb** [comment]
Decision (to be documented):

* Betas will be cut at feature completeness, with 1 week between releases for bug fixes.
* After RC, 1 week til GA.
* This applies to the plugins we maintain too.
