### ISSUE TITLE
How to restore K8S and PVCs using scheduled/incremental backups

### ISSUE THREAD

**Issue by jbmassicotte** [vmware-tanzu/velero#2960]
I am using velero with restic enabled to schedule backups of an Azure cluster, which has Managed Disk  PVCs, and Azure File PVCs. Let’s say I have 30 days worth of nightly backups/snapshots. 

My understanding is that the snapshots of the volumes, both Managed Disk and Azure File, are incremental, **right**?

And how am I supposed to restore the cluster & volumes given the snapshots are incremental? Do I have to restore 1 backup at a time, starting with older backups? And how far back to go?

**Comment by jbmassicotte** [comment]
Now it appears incremental snapshots of Azure Disks is available in v1.5, as discussed here https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/52. 
That is good news. However, I am still unclear on how to restore from incremental snapshots.

**Comment by nrb** [comment]
@jbmassicotte We need to release a version of the plugin that includes that PR still; I will get that out by the end of this week and update this issue.

For restores, there is no special flags or commands to add to `velero restore` for Azure Managed Disks - the Azure API figures it out underneath the covers.

Similarly, restic makes its own filesystem snapshots incrementally. Velero does not expose controls for this currently. Upon restore, Velero lets restic determine what data needs to be pulled in from the restic repository in order to restore all the data.

**Comment by jbmassicotte** [comment]
@nrb Ok thank you, I look forward to this release. BTW, I see v1.5.1 is the current release. Should I be looking for v1.5.2 then?

And regarding my question about restoring from scheduled backup, now I understand that one can restore using the '--from-schedule \<schedule-name\>' option, in one command. Simple enough.

I saw a couple of sites (eg https://github.com/openebs/velero-plugin, bottom of page) with examples where they use --from-backup multiple times to restore from scheduled backups. That's what confused me. I'll just ignore those.

**Comment by jbmassicotte** [comment]
@nrb Any update regarding the availability of the incremental snapshots of Azure Disks?

**Comment by dsu-igeek** [comment]
Incremental snapshots are part of the 1.1.1 release for the Velero Plugin for Microsoft Azure, released last week.

**Comment by jbmassicotte** [comment]
@dsu-igeek Good news! And thanks for letting me know.

**Comment by badalk** [comment]
@nrb any idea why you say Azure file snapshot is not supported by Azure yet? Why can't velero native snapshot support this https://docs.microsoft.com/en-us/azure/storage/files/storage-snapshots-files
