### ISSUE TITLE
Does restic have challenges with multiple PV's in single app?

### ISSUE THREAD

**Issue by cloudcafetech** [vmware-tanzu/velero#3001]
In my NS  I have two SS with NFS backed up PV, each SS has 3 replica.

Backup no issue but abnormal behave in restoring. As per my observation it restore on-time successfully.

Does restic have challenges with multiple PV's in single app?

**Comment by carlisia** [comment]
Hey @cloudcafetech, the general answer here is no, people are using Velero/restic to backup and restore these types of apps all the time. 

We'd need to know more specific information about your restore challenges. Please provide answers to the report below.

---
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)


**What did you expect to happen:**


**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`


**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]


**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by ashish-amarnath** [comment]
@cloudcafetech I am going to close this issue. Please re-open if you have a specific question or seeing errors on either backup or restore using Velero.
