### ISSUE TITLE
Delete snapshot-location or set a default one

### ISSUE THREAD

**Issue by jastabile** [vmware-tanzu/velero#3036]
**Describe the problem/challenge you have**
Set default snapshot-location or delete it.

**Describe the solution you'd like**
Should have a command ```velero snapshot-location delete ...``` and ```velero snapshot-location edit ...```

**Anything else you would like to add:**
I dont know how to set a default snapshot-location from two I have

**Environment:**

- Velero version (use `velero version`): v1.5.1
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version:
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment]
Hi @jastabile,

To set a default snapshot location, you'll have to edit the velero deployment and set the appropriate server command line flag:

From `velero server --help`, which you can see from the client since they're the same binary:

`--default-volume-snapshot-locations mapStringString   List of unique volume providers and default volume snapshot location (provider1:location-01,provider2:location-02,...)`

So you would set this to be something like the following inside the deployment.yaml:

```yaml
...top omitted...
   spec:
      containers:
      - args:
        - server
        - --features=
        command:
        - /velero
        - --default-volume-snapshot-locations
        - aws:my-snapshot-location2
...bottom omitted...
```

You are right, however, that we are missing the relevant deletion commands for locations. We're planning on addressing this in our v1.6.0 release.

For now, you could delete them with `kubectl delete volumesnapshotlocation.velero.io -n velero <location name>`

**Comment by danil-smirnov** [comment]
Still not addressed, `velero snapshot-location delete` does not exist... Please reopen
