### ISSUE TITLE
 Velero Restore is failing for ServiceInstances.

### ISSUE THREAD

**Issue by Shilpa418** [vmware-tanzu/velero#3049]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
We tried backup of one of our Namespace which has Kafka ServiceBroker.
Backup completed with no issues.

Now when i am trying to restore the backup I am facing issue.
I see below error in ./velero restore describe care-cd-sb-fnd-20201026091059

Phase:  PartiallyFailed (run 'velero restore logs care-cd-sb-fnd-20201026091059' for more information)
Warnings:   <error getting warnings: Get "http://velero-minio-lb-velero.apps.ilocpde409.ocpd.corp.amdocs.com:9000/velero/restores/care-cd-sb-fnd-20201026091059/restore-care-cd-sb-fnd-20201026091059-results.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20201026%2Fminio%2Fs3%2Faws4_request&X-Amz-Date=20201026T071222Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=a7c488a1996901356fc2d6f7f195d496c4d6e855073b9f90683203c1b412dec0": dial tcp 10.237.117.64:9000: connect: connection refused>

Errors:  <error getting errors: Get "http://velero-minio-lb-velero.apps.ilocpde409.ocpd.corp.amdocs.com:9000/velero/restores/care-cd-sb-fnd-20201026091059/restore-care-cd-sb-fnd-20201026091059-results.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20201026%2Fminio%2Fs3%2Faws4_request&X-Amz-Date=20201026T071222Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=a7c488a1996901356fc2d6f7f195d496c4d6e855073b9f90683203c1b412dec0": dial tcp 10.237.117.64:9000: connect: connection refused>

When i checked logs, i see below:

time="2020-10-23T14:05:38Z" level=info msg="error restoring kafka-d1-error-scheduletasktopic-scheduler-task: ServiceInstance.servicecatalog.k8s.io \"kafka-d1-error-scheduletasktopic-scheduler-task\" is invalid: [spec.serviceClassRef: Forbidden: serviceClassRef must not be present on create, spec.servicePlanRef: Forbidden: servicePlanRef must not be present on create]" logSource="pkg/restore/restore.go:1152" restore=velero/care-cd-sb-fnd-20201023170453
time="2020-10-23T14:05:38Z" level=info msg="Attempting to restore ServiceInstance: kafka-d1-executetasktopic" logSource="pkg/restore/restore.go:1089" restore=velero/care-cd-sb-fnd-20201023170453
time="2020-10-23T14:05:38Z" level=info msg="error restoring kafka-d1-executetasktopic: ServiceInstance.servicecatalog.k8s.io \"kafka-d1-executetasktopic\" is invalid: [spec.serviceClassRef: Forbidden: serviceClassRef must not be present on create, spec.servicePlanRef: Forbidden: servicePlanRef must not be present on create]" logSource="pkg/restore/restore.go:1152" restore=velero/care-cd-sb-fnd-20201023170453
time="2020-10-23T14:05:38Z" level=info msg="Attempting to restore ServiceInstance: kafka-d1-fndsec-osm-cdr" logSource="pkg/restore/restore.go:1089" restore=velero/care-cd-sb-fnd-20201023170453
time="2020-10-23T14:05:38Z" level=info msg="error restoring kafka-d1-fndsec-osm-cdr: ServiceInstance.servicecatalog.k8s.io \"kafka-d1-fndsec-osm-cdr\" is invalid: [spec.serviceClassRef: Forbidden: serviceClassRef must not be present on create, spec.servicePlanRef: Forbidden: servicePlanRef must not be present on create]" logSource="pkg/restore/restore.go:1152" restore=velero/care-cd-sb-fnd-20201023170453
time="2020-10-23T14:05:38Z" level=info msg="Attempting to restore ServiceInstance: kafka-d1-fndsec-osm" logSource="pkg/restore/restore.go:1089" restore=velero/care-cd-sb-fnd-20201023170453
time="2020-10-23T14:05:38Z" level=info msg="error restoring kafka-d1-fndsec-osm: ServiceInstance.servicecatalog.k8s.io \"kafka-d1-fndsec-osm\" is invalid: [spec.serviceClassRef: Forbidden: serviceClassRef must not be present on create, spec.servicePlanRef: Forbidden: servicePlanRef must not be present on create]" logSource="pkg/restore/restore.go:1152" restore=velero/care-cd-sb-fnd-20201023170453
time="2020-10-23T14:05:38Z" level=info msg="Attempting to restore ServiceInstance: kafka-d1-scheduletasktopic" logSource="pkg/restore/restore.go:1089" restore=velero/care-cd-sb-fnd-20201023170453
time="2020-10-23T14:05:38Z" level=info msg="error restoring kafka-d1-scheduletasktopic: ServiceInstance.servicecatalog.k8s.io \"kafka-d1-scheduletasktopic\" is invalid: [spec.serviceClassRef: Forbidden: serviceClassRef must not be present on create, spec.servicePlanRef: Forbidden: servicePlanRef must not be present on create]" logSource="pkg/restore/restore.go:1152" restore=velero/care-cd-sb-fnd-20201023170453
time="2020-10-23T14:05:38Z" level=info msg="Attempting to restore ServiceInstance: kafka-d1" logSource="pkg/restore/restore.go:1089" restore=velero/care-cd-sb-fnd-20201023170453
time="2020-10-23T14:05:38Z" level=info msg="error restoring kafka-d1: ServiceInstance.servicecatalog.k8s.io \"kafka-d1\" is invalid: [spec.serviceClassRef: Forbidden: serviceClassRef must not be present on create, spec.servicePlanRef: Forbidden: servicePlanRef must not be present on create]" logSource="pkg/restore/restore.go:1152" restore=velero/care-cd-sb-fnd-20201023170453

**What did you expect to happen:**

Restore should be successfull. 

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ashish-amarnath** [comment]
@Shilpa418 
> I see below error in ./velero restore describe care-cd-sb-fnd-20201026091059
Phase: PartiallyFailed (run 'velero restore logs care-cd-sb-fnd-20201026091059' for more information)
Warnings: <error getting warnings: Get "http://velero-minio-lb-velero.apps.ilocpde409.ocpd.corp.amdocs.com:9000/velero/restores/care-cd-sb-fnd-20201026091059/restore-care-cd-sb-fnd-20201026091059-results.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20201026%2Fminio%2Fs3%2Faws4_request&X-Amz-Date=20201026T071222Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=a7c488a1996901356fc2d6f7f195d496c4d6e855073b9f90683203c1b412dec0": dial tcp 10.237.117.64:9000: connect: connection refused>
Errors: <error getting errors: Get "http://velero-minio-lb-velero.apps.ilocpde409.ocpd.corp.amdocs.com:9000/velero/restores/care-cd-sb-fnd-20201026091059/restore-care-cd-sb-fnd-20201026091059-results.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20201026%2Fminio%2Fs3%2Faws4_request&X-Amz-Date=20201026T071222Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=a7c488a1996901356fc2d6f7f195d496c4d6e855073b9f90683203c1b412dec0": dial tcp 10.237.117.64:9000: connect: connection refused>

On running the velcro restore describe` is because Velero connects to the object store, which in your case is MinIO, to retrieve restore information to print as part of the output of the command. In this case, Velero is not able to connect to the MinIO endpoint `velero-minio-lb-velero.apps.ilocpde409.ocpd.corp.amdocs.com:9000`.
Can you please confirm that the endpoint `velero-minio-lb-velero.apps.ilocpde409.ocpd.corp.amdocs.com:9000`is hosting the MinIO service?

As for the error
> time="2020-10-23T14:05:38Z" level=info msg="error restoring kafka-d1-error-scheduletasktopic-scheduler-task: ServiceInstance.servicecatalog.k8s.io "kafka-d1-error-scheduletasktopic-scheduler-task" is invalid: [spec.serviceClassRef: Forbidden: serviceClassRef must not be present on create, spec.servicePlanRef: Forbidden: servicePlanRef must not be present on create]" logSource="pkg/restore/restore.go:1152" restore=velero/care-cd-sb-fnd-20201023170453

This is because the ServiceInstance type disallows the `serviceClassRef` field from being set when creating the object. This will require a RestoreItemAction plugin that applies just to serviceInstance objects that clears out the`serviceClassRef` field.

I am going to close this issue as resolved as this is not actionable for the Velero team.
Please re-open or reach out if you have more questions or need further assistance.

**Comment by Shilpa418** [comment]
Hi,

Do we have instructions on how can we create such a plugin and use it for velero?
As we are new to this we are unable to find the procedure.
Please help.

Thank You!

**Comment by ashish-amarnath** [comment]
This info is available on our website at https://velero.io/docs/v1.5/custom-plugins/ and there are plugin examples available at https://github.com/vmware-tanzu/velero-plugin-example

________________________________
