### ISSUE TITLE
Update migration documentation to point out the feature flag isn't required.

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#3452]
Migrating between kubernetes versions doesn't strictly require this feature flag, so long as there were no incompatible changes to the core types. This is a little tricky to provide guidance on, because while I know v1.15.->1.16 did this, not all versions do, and I don't really want to maintain an exhaustive list of version jumps that this is relevant to. 

Could we maybe add some wording to this about Kubernetes upgrades containing incompatible or removed API groups?

_Originally posted by @nrb in https://github.com/vmware-tanzu/velero/pull/3133#discussion_r573971114_

**Comment by a-mccarthy** [comment]
The feature flag being referred to in this issue is the EnableAPIGroupVersions, https://velero.io/docs/main/enable-api-group-versions-feature/. 

I'd think the best place to point folks to are the Kubernetes release notes for the cluster versions they are migrating between to see if there are any changes in api versions, https://github.com/kubernetes/kubernetes/tree/master/CHANGELOG.

Also, are there any potentially negative affects of having this flag enabled when you are migrating between clusters where the api group doesn't change? Other than the (i assume) small lift of enabling this flag when maybe you dont need to, would it cause other problems? 

cc: @nrb
