### ISSUE TITLE
Include list of accepted resources in resource-filtering documentation

### ISSUE THREAD

**Issue by deefdragon** [vmware-tanzu/velero#3806]
**Describe the problem/challenge you have**
It is difficult to determine what the names of the resources that would be recognized by include-resources are.

**Describe the solution you'd like**
To include somewhere on the page the list of resource names that will be recognized when using the include/exclude resources commands.

**Anything else you would like to add:**
This is likely a problem elsewhere in the documentation, where the list of possible options is not included in the documentation. I have not had time to check for specific other instances, but it is likely.

**Environment:**
Master & 1.6 lack this. 
NA Otherwise. Documentation Issue.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by deefdragon** [comment]
Please also include some explicit mention of the fact that the data _in_ a PV is backed up via restic on the about page, and ideally in the overview section. It could also do to be mentioned in the quickstart. 

That bit me and I had to resort to a VM level snapshot restoration to restore my data.

I know its my fault and that I should have caught it during testing, but I read "back up [...]Kubernetes cluster resources and persistent volumes" as _including_ the data therein. Otherwise why would you have mentioned them separate from resources?

**Comment by zubron** [comment]
Thanks for the feedback here, @deefdragon!

The resources that can be included in the include/exclude list are Kubernetes resource types that are available in your cluster: the same resource names that you would interact with when using tools like `kubectl`. We can't provide an exhaustive list of these in our documenations as this will vary from cluster to cluster (especially when CRDs are being used). We can definitely add more clarity though and state that the arguments should be the name of Kubernetes resources. The help text for flag in the CLI is a bit more descriptive:

> Resources to include in the backup, formatted as resource.group, such as storageclasses.storage.k8s.io (use '*' for all resources).

With regard to your second point, you can choose to take volume snapshots or use restic. Both will provide backup of the contents of your PVs. We don't explicitly mention restic as we recommend users use Volume snapshotting capabilities where available (see our [storage providers documentation](https://velero.io/docs/v1.6/supported-providers/). We can certainly improve the getting started documentation to make it clearer that you must configure either a volume snapshotter or restic in order to backup PV contents.
