### ISSUE TITLE
Allow image pull secrets to be configured for the restic-restore-helper image

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#3813]
**Describe the problem/challenge you have**

When restoring a pod from a backup, restic uses an [init container](https://velero.io/docs/v1.6/restic/#customize-restore-helper-container) to check that the data in the volume is restored prior to the other containers in the pod starting.

It is possible to configure the image that is used however it is not possible to configure image pull secrets for this image in the case where the user wants to use a private registry that requires authentication.

**Describe the solution you'd like**
The solution for this will require some thought as the image is being pulled by the pod being restored. In order to have access to the image pull secret, it will need to exist in the namespace where the pod is being restored. If the entire namespace is being restored, the secret necessary for pulling the image will likely not exist.

It may be necessary to require that service accounts for namespaces being restored have permissions to pull images.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by danielnbalasoiu** [comment]
Please take into consideration that some private registries require authentication so need a way to pass the name of the secret to use.

**Comment by jenting** [comment]
The Velero helm chart uses configMaps to change the restic repo path https://github.com/vmware-tanzu/helm-charts/blob/daa10dd/charts/velero/values.yaml#L365-L374.

**Comment by zubron** [comment]
To add to @jenting's comment above, here is the documentation for how to configure and customize the restic restore helper: https://velero.io/docs/v1.6/restic/#customize-restore-helper-container

I'm going to modify this issue to cover @danielnbalasoiu's point above that Velero does not provide a way to provide image pull secrets for this image. Providing image pull secrets is something that can be configured on the Velero and Restic deployments directly however the restic restore helper is dynamically added as an init container to the pod being restored.

This will require more thought as the image is being pulled by the pod being restored. In order to have access to the image pull secret, it will need to exist in the namespace where the pod is being restored. If the entire namespace is being restored, the secret necessary for pulling the image will likely not exist.

**Comment by barryboubakar** [comment]
Thank you @zubron for pointing out  [this documentation](https://velero.io/docs/v1.6/restic/#customize-restore-helper-container). @eleanor-millman this helped us (at Orange) to restore our k8s workloads using restic, the init-container image is now pulled from our private registry.

**Comment by codegold79** [comment]
Since this issue is no longer in our Velero 1.7.0 milestone, I'll un-assign myself and work on issues that are in the milestone.

**Comment by m44soroush** [comment]
In the newer version of velero  (v1.11.1),  you can use these values in your helm chart:
```
configMaps:
  fs-restore-action-config:
    labels:
      velero.io/plugin-config: ""
      velero.io/pod-volume-restore: RestoreItemAction
    data:
      image: docker.mofid.dev/velero/velero-restore-helper:v1.10.2
```

**Comment by rosieks** [comment]
What about pull secret? Is there a way to define it?

**Comment by sseago** [comment]
Note that we no longer have a separate restore-helper image. That has been rolled into the regular velero image as of Velero 1.16.
