### ISSUE TITLE
Allow customizing Velero image at build time

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#3831]
**Describe the problem/challenge you have**
Currently, [Velero hard-codes](https://github.com/vmware-tanzu/velero/blob/ccac3d41301c8883b62e2d3d3429711a5f8088d6/pkg/install/resources.go#L45) the image being pulled for cluster installation. This presents a challenge when trying to install from other repositories, despite the existence of the `--image` argument.

**Describe the solution you'd like**
Allow for customizing the repository to be used at build time, defaulting to `velero/velero` (DockerHub)

**Environment:**

- Velero version (use `velero version`): All current versions

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
If we do it at the build time, there should be a way to display these default image repos using CLI?

If we do not support displaying the images via CLI, I wish to suggest the default images be configured via a configuration file.

**Comment by zubron** [comment]
@reasonerjt If configured at build time, the help text for the `--image` flag will show the image that it will attempt to pull by default. I think with this approach as well, each build would only ever try to use one image repo so it wouldn't display multiple image repos.

I was thinking a bit more about this and realised that there is additional complexity due to the image that is used for the [init container during restic restores](https://velero.io/docs/v1.6/restic/#customize-restore-helper-container). As this is happening on the cluster, we can't rely on local configuration files. Currently, users can create a config map to state which image should be used during restic restore. This config map needs to be created _post_ installation in the Velero namespace.

By embedding the repo to use at build time, these steps could be avoided by the user. However I agree with your point that it would introduce more complexities in supporting the project.
