### ISSUE TITLE
Instrumentation for internal performance monitoring

### ISSUE THREAD

**Issue by dsu-igeek** [vmware-tanzu/velero#3841]
**Describe the problem/challenge you have**
Instrumentation of key areas would be very helpful when analyzing performance problems. For example, keeping track of
how long it takes to execute plug-ins, how much time is spent reading/writing with the API server, and time spent in 
key areas would make it easier.

**Describe the solution you'd like**

- Select an instrumentation package.  https://www.jaegertracing.io/docs/1.22/ was mentioned, others may be appropriate.
- Identify areas to instrument
- Inject instrumentation

**Anything else you would like to add:**
@phuongatemc raised this in the community meeting 6/1/2021
@sseago will look at work done inside RH with Velero plug-ins and instrumentation

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by sseago** [comment]
For the konveyor/crane project, we integrated jaeger tracing to help us identify possible performance bottlenecks. The basic idea is to enable jaeger tracing within the application, and whether the tracing is actually done is controlled by an environment variable that you would set on the application(velero) pod/deployment. At the same time, when you ran the application enabling tracing, you'd need to have a jaeger collector running within the cluster. Here is the PR which includes the initial jaeger support within crane as an example. The PR description/comments also give some information as to how to set up the jaeger collector. In the crane example, jaeger is running locally rather than in-cluster, since we're making use of the dev mode `make run` for the migration controller which runs it locally referencing the cluster in KUBECONFIG. I'm assuming that with the velero pod running in the cluster, the jaeger collector would also need to be running as a pod in the same cluster:
https://github.com/konveyor/mig-controller/pull/967
