### ISSUE TITLE
Velero pod restarted due to OOMKill when backup a namespace with thousands of resources

### ISSUE THREAD

**Issue by phuongatemc** [vmware-tanzu/velero#3851]
Reproduce steps:
- Velero pod memory is anywhere from 128MB to 512MB
- Create a namespace with 10,000 Sercets, ServiceAccount etc. (to simulate the case when user creates a lot of CR in a namespace).
- Run Velero Backup of that namespace
- Within a minute, the Velero pod got killed and restarted (See pod status below after it restarted)
...
terminated:
containerID: cri-o://33fa5091a84d47658d50ea3712deea5910a3e0a990d072e9ffdb4966fc0dd087
exitCode: 137
finishedAt: "2021-06-07T22:09:47Z"
reason: OOMKilled
startedAt: "2021-06-07T17:22:05Z"
...

**Comment by codegold79** [comment]
Regarding @phuongatemc's first bullet point item, 
> Velero pod memory is anywhere from 128MB to 512MB

these memory values come from the default resource limits and requests.

After installing Velero, I ran `kubectl describe deploy/velero` and here is the relevant resource section:

```yaml
    Limits:
      cpu:     1
      memory:  512Mi
    Requests:
      cpu:     500m
      memory:  128Mi
```

I believe these are good default limits for Velero to have provided. 

The solution to this issue is to increase the default requests and limits values for memory. I haven't changed the defaults myself, but in the `Velero install` command help, these flag options were provided:

```bash
--velero-pod-cpu-limit string                CPU limit for Velero pod. A value of "0" is treated as unbounded. Optional. (default "1000m")
--velero-pod-cpu-request string              CPU request for Velero pod. A value of "0" is treated as unbounded. Optional. (default "500m")
--velero-pod-mem-limit string                Memory limit for Velero pod. A value of "0" is treated as unbounded. Optional. (default "512Mi")
--velero-pod-mem-request string              Memory request for Velero pod. A value of "0" is treated as unbounded. Optional. (default "128Mi")
```

cc: @brito-rafa

**Comment by phuongatemc** [comment]
We resolved this problem by increase memory.  Look like we won't have a long term solution until there is a real need to scale up the number of resources being backed up.
