### ISSUE TITLE
Unable to restore on Kubernetes 1.21 using restic due to service account volume projection

### ISSUE THREAD

**Issue by vivekwalia28** [vmware-tanzu/velero#3863]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I ran velero backup on my cluster which was successful but when restore getting partiallyfailed because pod is stuck in restic-wait condition.

**What did you expect to happen:**
Velero restore run successfully.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
https://gist.github.com/vivekwalia28/a20635628d6304fd72e398946591d86b

- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
https://gist.github.com/vivekwalia28/c339543bac03932bec878e9022c2aecd

- `velero backup logs <backupname>`
https://gist.github.com/vivekwalia28/36aed006f40921e8599d66308841708c

- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
https://gist.github.com/vivekwalia28/4f3e21424ad2df16b9589d189292c714

- `velero restore logs <restorename>`
https://gist.github.com/vivekwalia28/b966c5a106d2960f8d3d3f24051f7dc5

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):  1.6.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.21
- Kubernetes installer & version:
- Cloud provider or hardware configuration: On VM
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by zubron** [comment]
Hi @vivekwalia28 :wave: 

We're sorry you're experiencing this. This is an issue that we have identified on another PR. Restic restores are currently failing on Kubernetes 1.21 clusters due to a change in behaviour to mount Service Accounts using a projected volume (https://github.com/vmware-tanzu/velero/pull/3764#issuecomment-858237896) which triggers a known bug in restic (https://github.com/vmware-tanzu/velero/pull/3764#issuecomment-857923546).

Usually, Velero will [not attempt to backup volumes that have a secret or config map as the source](https://github.com/vmware-tanzu/velero/blob/main/pkg/restic/common.go#L178-L185) as these are backed up separately. With the change to use volume projection, Velero will attempt to back these volumes up and upon restore they trigger the issue in restic.

As a workaround, I'd recommend switching from backing up all volumes using restic to using the [opt-in approach](https://velero.io/docs/main/restic/#using-opt-in-pod-volume-backup) so that the projected service account volumes are not backed up using restic.

**Comment by zubron** [comment]
@alaypatel07 I know you had a [PR for this on the konveyor fork](https://github.com/konveyor/velero/pull/101). Please let me know if you want to submit it back upstream as we'll definitely need to incorporate that fix.

**Comment by alaypatel07** [comment]
@zubron I'll post the fix later tonight or early tomorrow morning if that's okay. Thanks

**Comment by vivekwalia28** [comment]
Hi @zubron Neither the workaround nor the fix worked for me!
Could you please see what I am doing wrong?

**Comment by zubron** [comment]
Hi @vivekwalia28! We haven't provided a release yet which includes this fix (we hope to do that this week). Are you using a Velero image that you have built yourself? As for the workaround, this will not fix existing backups but will only help with new backups that are taken.

**Comment by vivekwalia28** [comment]
Hi @zubron I have not built the velero image myself.
And I tested it for new backups only but that also didn't worked for me.
Other than this do you have something else?
Thanks

**Comment by zubron** [comment]
Hi @vivekwalia28 - I don't know if you've seen but we released [v1.6.1](https://github.com/vmware-tanzu/velero/releases/tag/v1.6.1) which fixes this issue. You can find instructions on how to upgrade [here](https://velero.io/docs/v1.6/upgrade-to-1.6/).

**Comment by vivekwalia28** [comment]
@zubron Thanks,it worked perfectly fine after I upgraded my velero to new release and the issue got fixed.

**Comment by wcochran53** [comment]
Does this issue fix the same problem seen with DownwardApi volumes where projected Volume wasn't indicated.
