### ISSUE TITLE
Add E2E test case for backing up pods using Downward API

### ISSUE THREAD

**Issue by zubron** [vmware-tanzu/velero#3872]
While investigating #3863, it was noticed that Velero will skip backing up volumes that have [secrets or config maps](https://github.com/vmware-tanzu/velero/blob/main/pkg/restic/common.go#L178-L185) as the source when using restic. We now also skip backing up projected volumes as these will only contain state from the Kubernetes API server.

[Downward API](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/) is used to expose pod information to containers. Velero doesn't skip this volume type and we don't know what the current behaviour of Velero is when interacting with this type. We should add an E2E test case to cover this.

**Comment by zubron** [comment]
This is still required.

**Comment by eleanor-millman** [comment]
@danfengliu I assume I should leave the 1.8 milestone since you just added it yesterday?

**Comment by qiuming-best** [comment]
since the later pr #4076  merged,  restic backup/restore of DownwardAPI volumes will be skipped, so the current behavior of Velero will skip of backup/restore with restic using DownwardAPI. the unit test may have covered the scenarios, maybe e2e test is not needed. I'll close it, If it is needed an e2e test, please reopen it.
