### ISSUE TITLE
The commit ID of final RC should be the same as the GA release.

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#3901]
I noticed there are code changes between the RC and final release.  
Ideally, we should make sure that the commit of the final RC is the one we tag for GA.  The package we ship for GA release should be the one of the final RC which passes all the tests.

I noticed that the reason for the situation is we need to update the doc for the website between RC and GA.  We should revisit the flow and try to make sure the final RC and GA tag point to the identical commit.  

One possible solution may be to spin out the website to another repo?

**Comment by zubron** [comment]
Another option with regard to the docs would be to only generate one set of docs at the point when the release candidate is made but ensure that it is _not_ set as the [latest version](https://github.com/vmware-tanzu/velero/blob/main/hack/release-tools/gen-docs.sh#L106-L107). This would mean that the RC docs would be on the website with a GA version number (e.g. 1.7) but would have the "Development version" warning like we currently have on the main branch docs: https://velero.io/docs/main/

This would allow us to use the same commit for RC and GA, and we could create a PR post-release to update the website once all the assets are published. With the current release process, there is a gap of time where the website has the new version but the new release assets may not be available for use yet. This is because the image build takes longer than the deploying the website.

**Comment by zubron** [comment]
Related issue: #3802
