### ISSUE TITLE
Restic restore with 1.5.4 fails to pull image "velero/velero-restic-restore-helper:v1.5.4_vmware.1"

### ISSUE THREAD

**Issue by longwa** [vmware-tanzu/velero#3917]
After installing the Mac CLI for velero 1.5.4 via the `velero install` command line.

When I try to do a restore of a restic volume, it fails with:
```
Failed to pull image "velero/velero-restic-restore-helper:v1.5.4_vmware.1": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/velero/vele │
│ ro-restic-restore-helper:v1.5.4_vmware.1": failed to resolve reference "docker.io/velero/velero-restic-restore-helper:v1.5.4_vmware.1": docker.io/velero/velero-restic-restore-helper:v1.5.4_vmware.1: not found
```

I don't see a _vmware.1 tagged version of the restore-helper image in the docker hub repo. Reverting to 1.5.3 works fine. 

It seems as if not all the artifacts are published or the 1.5.4.vmware.1 tag of Velero should not be looking for a _vmware.1 specific version of the restore helper.

**Comment by ywk253100** [comment]
Which Kubernetes provider are you using?

**Comment by longwa** [comment]
Sorry, I'm using TKG 1.3.1 with the 1.20.5 Ubuntu images running on vSphere 6.7U3 infrastructure.

**Comment by zubron** [comment]
Hi @longwa - Sorry for the issue here. Yes, some of the artifacts were not pushed for the 1.5.4 release. This has now been [remedied](https://hub.docker.com/layers/velero/velero-restic-restore-helper/v1.5.4_vmware.1/images/sha256-266f1c446d18a6bb6fe0924f6b841cb61fa2876ccc7447dc2f17fb6d68ea3ca9?context=explore) and we will be including changes to fix this in upcoming TKG releases.

I am going to close this issue, but if you have problems with this, or need further assistance, please feel free to reopen. Thanks!
