### ISSUE TITLE
Azure storage account shows phase and last validated as unknown

### ISSUE THREAD

**Issue by RichardDuaneWolford** [vmware-tanzu/velero#3923]
I'm deploying Velero using the CLI with this command:

`helm install velero vmware-tanzu/velero --namespace velero --set-file credentials.secretContents.cloud=./credentials-velero --set configuration.provider=azure --set configuration.backupStorageLocation.name=azure --set configuration.backupStorageLocation.bucket='velero' --set configuration.backupStorageLocation.config.resourceGroup=aks-testing-prod-003 --set configuration.backupStorageLocation.config.storageAccount=aks-testing-prod-003 --set snapshotsEnabled=true --set deployRestic=true --set configuration.volumeSnapshotLocation.name=azure --set image.repository=velero/velero --set image.pullPolicy=Always --set initContainers[0].name=velero-plugin-for-microsoft-azure --set initContainers[0].image=velero/velero-plugin-for-microsoft-azure:master --set initContainers[0].volumeMounts[0].mountPath=/target --set initContainers[0].volumeMounts[0].name=plugins`

The pods come up just fine, velero and restic.  But when I try to create a backup, it submits successfully but then fails with this error.  Any help would be appreciated.

```
Name:         mybackup
Namespace:    velero
Labels:       velero.io/storage-location=azure
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.19.11
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=19

Phase:  Failed (run `velero backup logs mybackup` for more information)

Errors:    0
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  azure

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-06-10 16:32:58 +0000 UTC
Completed:  <n/a>

Expiration:  2021-07-10 16:32:58 +0000 UTC

Velero-Native Snapshots: <none included>
```

**Comment by zubron** [comment]
Hi @RichardDuaneWolford - Could you please provide the following:

(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup-locations get`

I suspect this is being caused by an incorrect version of the Azure plugin being used: `velero/velero-plugin-for-microsoft-azure:master`. This tag is no longer updated and is a year old. Please select a [tag based on the version of Velero you are using](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#compatibility). If you are using a recent version of the helm chart, the image should probably be `velero/velero-plugin-for-microsoft-azure:v1.2.0`.
