### ISSUE TITLE
Adding s390x arch support

### ISSUE THREAD

**Issue by rposts** [vmware-tanzu/velero#4047]
**Describe the problem/challenge you have**
Velero currently supports multiple architectures including `arm64` and `ppc64le`.  It will be helpful to have `s390x` arch support added to prevent build from source on `s390x` arch.

**Describe the solution you'd like**
Add support for `s390x` architecture.

**Anything else you would like to add:**
I have already successfully built Velero on `s390x` and able to push the images to private docker registry. Following the steps mentioned [here](https://velero.io/docs/v1.6/build-from-source/#image-building) I can produce working velero binaries.
```
REGISTRY=myregistry VERSION=foo BUILDX_PLATFORMS=linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,**linux/s390x** BUILDX_OUTPUT_TYPE=registry RESTIC_VERSION=0.12.1 make all-containers
```

I have noted that `kubebuilder` and `goreleaser` are used during build phase which are downloaded directly from the appropriate repos. I have separate issues opened against these repos to enable `s390x` support as well.

I would also like to understand how `s390x` arch can be integrated into Velero CI pipeline to make this transparent for `s390x` users.

Thanks for your consideration.

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by zubron** [comment]
I don't think we need specific support from the kubebuilder and goreleaser projects as we rely on Go's cross compiling capabilities and Docker buildx to produce builds for other targets. s390x support for those projects would only be required if we were building _on_ that architecture during release which we are not doing.

The only additional binary that we include in our builds is Restic and they introduced support for s390x in the [0.12.1 release](https://github.com/restic/restic/releases/tag/v0.12.1). Velero is currently using v0.12.0 so in order to support this architecture we would need to upgrade the version of restic we are using. Then we would need to update the [goreleaser config](https://github.com/vmware-tanzu/velero/blob/main/.goreleaser.yml#L20-L42) to include that architecture, our [Makefile](https://github.com/vmware-tanzu/velero/blob/main/Makefile#L87), and the script used to when [building/pushing images to Dockerhub](https://github.com/vmware-tanzu/velero/blob/main/Makefile#L87)

**Comment by zubron** [comment]
Ah, I just realised that we already have an issue open for this: #2622. I am going to close this issue in favour of the original one. Thanks!
