### ISSUE TITLE
Provide guidance on Velero performance and resource limits

### ISSUE THREAD

**Issue by pradeepkchaturvedi** [vmware-tanzu/velero#4116]
Users want to know, how much cluster resource should be reserved during Velero backup.  User wants guidance on setting CPU and Memory resource limits for Velero and Restic based on cluster size. Cluster size can be in term of number of objects, namespaces etc.

User wants guidance of backup of PVs using Restic? Up to which size of PVs good to backup using Restic and how they can estimate transfer time. It would great to have ability to throttle network bandwidth for backup data transfer?

**Comment by felixbuenemann** [comment]
I had a problem in our production cluster where backups never completed.

After investigating it turned out that the default 256 MiB memory limit was exhausted while listing replicasets. That was with around 4500 replicasets. With the default GOGC setting, peak usage for a successful backup was around 450 MiB RSS, after adding GOGC=10 to the environment variables, peak usage dropped to around 270 MiB.

If I remember correctly, the default GOGC setting causes GC to run, when memory usage doubles, which doesn't work very well for apps that do large memory allocations, so shipping the velero deployment with a more aggressive GOGC by default couldn't hurt. In the end you trade memory usage for cpu time, so eg. GOGC=1 would not be advisable.

I think it is hard to give an exact estimation, since it appears to be dependent on the number of resources in the cluster at the moment. I haven't read through the code, so not sure if this could be fixed by fetching resources in smaller batches.

What would be helpful for users would be to have a section on the troubleshooting page in the docs that advises to check memory limits if backups don't complete or the velero pod has a high number of restarts.

**Comment by eleanor-millman** [comment]
Sorry, can't comment on the GOGC. But in general, this issue is slated to be done by mid-June when we finish our 1.9 release.

**Comment by a-mccarthy** [comment]
We currently document the default resource limits in the velero docs, https://velero.io/docs/main/customize-installation/#customize-resource-requests-and-limits, and note that backing up large files via restic requires higher resource requirements, https://velero.io/docs/v1.8/restic/#limitations.

@qiuming-best in your testing of resource consumption, where there any definitive recommendations of what folks should update their resource limits too if they have larger environments? 

I think it makes sense to include a better note recommending folks may need to increase the default CPU and memory limits if they have a large number of resources to back up here, ttps://velero.io/docs/main/customize-installation/#customize-resource-requests-and-limits. But im not sure if there are any hard numbers we can put because everyones set up is different. 

cc: @eleanor-millman in case you have thoughts here

**Comment by eleanor-millman** [comment]
Thanks for tagging me @a-mccarthy , I am happy to go with what you think best since I don't have opinions on this for now.

**Comment by qiuming-best** [comment]
> We currently document the default resource limits in the velero docs, https://velero.io/docs/main/customize-installation/#customize-resource-requests-and-limits, and note that backing up large files via restic requires higher resource requirements, https://velero.io/docs/v1.8/restic/#limitations.
> 
> @qiuming-best in your testing of resource consumption, where there any definitive recommendations of what folks should update their resource limits too if they have larger environments?
> 
> I think it makes sense to include a better note recommending folks may need to increase the default CPU and memory limits if they have a large number of resources to back up here, ttps://velero.io/docs/main/customize-installation/#customize-resource-requests-and-limits. But im not sure if there are any hard numbers we can put because everyones set up is different.
> 
> cc: @eleanor-millman in case you have thoughts here

@a-mccarthy, Through our test, the numbers of targes below 1000 and total size of files is below 100GB are working with velero default resource limits. 

If the backup resources exceed the above specifications, it is needed to add more CPU or memory resources, the resource limits depend on the scale of files and directories, and hardware.

Compared with restoring the same scale of data, backup needs more CPU & memory resources but is less time-consuming

Restic pod will consume huge numbers of memory, especially, with millions of tiny files and directories to be back up, [this](https://github.com/restic/restic/issues/2446) phenomenon exist for a long time and still not resolved by restic
