### ISSUE TITLE
Unable to restore pod voulmes using restic in istio enabled namespace

### ISSUE THREAD

**Issue by forumsheth15** [vmware-tanzu/velero#4133]
Hi I have deployed Velero v1.6.3 on AKS cluster, Kubernetes v1.20.9 and Istio v1.10.0
I am able to take backups of persistent volumes and restore them properly for non istio enabled namespace.
But when I restore a backup of istio enabled namespace the restore is partially failed and I get the following error:
![image](https://user-images.githubusercontent.com/51082137/133067203-a4387e9a-a572-4b3e-80ed-8faee340d226.png)

Can anyone kindly help me with this?

**Comment by zubron** [comment]
Hi @forumsheth15 - Sorry you're having issues with this. This is a known issue due to the restic behavior when interacting with DownwardAPI volumes (#4053) and was fixed in #4076. The fix for this will be included in our upcoming 1.7.0 release (RC available here: https://github.com/vmware-tanzu/velero/releases/tag/v1.7.0-rc.1). To work around this in the meantime, you should skip the backup of these volumes. You can use either the [opt in approach](https://velero.io/docs/v1.6/restic/#using-opt-in-pod-volume-backup) and not annotate the DownwardAPI volumes, or you can continue to use restic as the default but [exclude the DownwardAPI volumes](https://velero.io/docs/v1.6/restic/#using-the-opt-out-approach).

I am going to close this issue, but let us know if you have any problems with the approaches above. Thanks!

**Comment by forumsheth15** [comment]
Thank you for your response @zubron
