### ISSUE TITLE
[Question] Could not find requested resource (post.backups.velero.io) in GKE

### ISSUE THREAD

**Issue by scheung38** [vmware-tanzu/velero#4326]
**What steps did you take and what happened:**
Have an existing Jenkins in GKE

[A clear and concise description of what the bug is, and what commands you ran.)

$ gsutil mb gs://my-storage

$ velero backup create jenkins --include-namespaces jenkins --wait
An error occurred: the server could not find the requested resource (post backups.velero.io)

**What did you expect to happen:**
Backup completed with status: Completed. You may check for more information 

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
Error from server (NotFound): namespaces "velero" not found

- `velero backup describe jenkins` or `kubectl get backup/<backupname> -n velero -o yaml`
An error occurred: the server could not find the requested resource (get backups.velero.io jenkins)

- `velero backup logs jenkins`
Backup "jenkins" does not exist.

- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`

- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
Client:
        Version: v1.7.0

- Velero features (use `velero client config get features`): 
features:  NOT SET

$ kubectl get namespaces          
NAME              STATUS   AGE
cert-manager      Active   5h59m
default           Active   174d
jenkins           Active   174d
kube-node-lease   Active   174d
kube-public       Active   174d
kube-system       Active   174d
nginx-ingress     Active   5h59m

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10-gke.1600", GitCommit:"ef8e9f64449d73f9824ff5838cea80e21ec6c127", GitTreeState:"clean", BuildDate:"2021-09-06T09:24:20Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1

- Kubernetes installer & version:

brew install velero

which velero
/usr/local/bin/velero

- Cloud provider or hardware configuration:
GKE

- OS (e.g. from `/etc/os-release`):
Mac OS Monterey

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

Didn't see any examples directory, is this related to how brew was installed as opposed to zip download?

i.e 
examples/minio
examples/nginx-app

**Comment by zubron** [comment]
Hi @scheung38 :wave: The error you are seeing is usually because the Velero CRDs are not installed. Also, given that you don't have a velero namespace, it seems like velero is not installed in your cluster. You will need to install the velero server and configure it to use your GS bucket prior to running any backups. Please see our [installation instructions](https://velero.io/docs/v1.7/basic-install/) and then follow the instructions for setting up Velero to run on GCP here: https://github.com/vmware-tanzu/velero-plugin-for-gcp

I'm going to close this, but feel free to let us know if you have further issues. Thanks!

**Comment by scheung38** [comment]
Thanks @zubron working now, even though it is in Google Storage, would like to use MinIO instead, so was wondering how much work needed to move from Google Storage to MinIO

**Comment by zubron** [comment]
In order to use MinIO, you would need to use our [AWS plugin](https://github.com/vmware-tanzu/velero-plugin-for-aws) instead which can store the backups to an S3 compatible store. If you have an existing Velero installation, you can add a new Backup Storage Location to send your backups to the S3 bucket: https://github.com/vmware-tanzu/velero-plugin-for-aws#Create-an-additional-Backup-Storage-Location

Velero does not support migration of backups however so any backups that are in your GS bucket will remain there and will not be copied over to the new storage location.

**Comment by scheung38** [comment]
No GKE plugins?

**Comment by zubron** [comment]
As MinIO is an S3 compatible store, it is necessary to use the AWS plugin which enables to Velero to interact with it using the S3 APIs. You can still run this plugin on GKE.

**Comment by utkarshn-veritas** [comment]
Try running install command with -v7.
v1beta1 apis are deprecated in K8s 1.22 https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-22
