### ISSUE TITLE
Velero backs up K8S data

### ISSUE THREAD

**Issue by houzhx759** [vmware-tanzu/velero#4445]
How long does it take velero to back up about 100G of data? Why am I running the backup for 4 hours now and it is not finished yet? I suspect it has failed, but there is no log.

**Comment by houzhx759** [comment]
![image](https://user-images.githubusercontent.com/86034885/145779845-8e02732d-1215-4986-9d94-c50ed21b369a.png)
I started at 12.44 noon and I haven't finished till 16.45. I don't think this is normal

**Comment by chrislinan** [comment]
Hi @houzhx759 
If your 100G data is stored in persistent volume and you are using correct velero plugin, the backup will finish very soon. 
Because the backup process is actually take a snapshot of your volume on IaaS. 
You can check if there is a snapshot created on your IaaS to verify the backup success.

For this case, your backup stuck in the status "InProgress", this is probably because your velero pod has been recreated in the backup process. And you need to create a new backup request for it.
If your velero pod always recreate in the backup process, please check the request CPU and Memory for this pod. The pod might be kill by OOM issue.

**Comment by houzhx759** [comment]
This is my backup command, I tried small files can be successful, but the 100G state is always InProgress


velero backup create xxl-job-namespace --include-namespaces xxl-job  --default-volumes-to-restic

**Comment by houzhx759** [comment]
Do you have any good suggestions? thank you

**Comment by houzhx759** [comment]
> 嗨@houzhx759 如果您的 100G 数据存储在持久卷中并且您使用的是正确的 velero 插件，备份将很快完成。 因为备份过程实际上是对 IaaS 上的卷进行快照。 您可以检查 IaaS 上是否创建了快照以验证备份成功。
> 
> 对于这种情况，您的备份停留在“InProgress”状态，这可能是因为您的 velero pod 已在备份过程中重新创建。您需要为它创建一个新的备份请求。 如果您的 velero pod 总是在备份过程中重新创建，请检查此 pod 的请求 CPU 和内存。pod 可能被 OOM 问题杀死。
This is my backup command, I tried small files can be successful, but the 100G state is always InProgress

velero backup create xxl-job-namespace --include-namespaces xxl-job --default-volumes-to-restic

Do you have any good suggestions? thank you

**Comment by chrislinan** [comment]
OK, I noticed you are using restic for PV backup. 
This will back up your PV to object store, and actually it will copy your data and upload to object store, it will not take a volume snapshot on your IaaS. So the time required for the backup depends on the amount of your data and your network situation.It might take a long time if you have 100G data.
But, if velero pod is recreated in this process the backup will stuck in "InProgress" forever.

**Comment by blackpiglet** [comment]
@houzhx759 
How about your last test result? Can it complete at last?
