### ISSUE TITLE
Convert Restic Repository resource/controller to the Kubebuilder framework

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#4670]
**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by blackpiglet** [comment]
Talked with Ming, found there's another piece of code also watches ResticRepository CRD.
https://github.com/vmware-tanzu/velero/blob/main/pkg/restic/repository_ensurer.go#L58-L99

I think this issue is good enough to not include that part, but may need to refactor repository ensurer's list-watch code in another issue.

**Comment by blackpiglet** [comment]
ResticRepositoryEnsurer related converting to kubebuilder work is traced by #5024
