### ISSUE TITLE
Velero in Azure - Is it possible to store the backups with redundancy between two different AZs?

### ISSUE THREAD

**Issue by BCMBCM** [vmware-tanzu/velero#4735]
I am aware Velero is not able to backup Azure ZRS managed disks, but I would like to know if it is possible to store the pvc backup snapshots in ZRS target locations and how to do configure it (using velero plugin for Microsoft Azure)

Regarding the backups stored in the Blob STA, I understand it would just be a matter of deploying the Blob STA as ZRS. Is this right?

PS: Please can you label this issue as a question?

Thank you

**Comment by blackpiglet** [comment]
You can change the StorageClass used in restore process. This is the document link: https://velero.io/docs/v1.8/restore-reference/#changing-pvpvc-storage-classes

**Comment by BCMBCM** [comment]
@blackpiglet the question is not related to the restore process, it is about having more resilience of the backups stored in Azure
@ywk253100  Do you know if it is possible to configure velero to store the snapshots with Zone Redundant Storage?

Thank you

**Comment by ywk253100** [comment]
@BCMBCM 
Backing up ZRS managed disks should already be fixed by https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/131

Azure Velero plugin should support storing the backup in ZRS location, but we didn't test on it. It will be great if you have the chance to try that and see if it works as expected

**Comment by BCMBCM** [comment]
@ywk253100 Sorry If i haven´t explained it well. I am not trying to backup ZRS disks. What I would like to do is to be able to store my backup snapshots in a ZRS storage , to provide more resilence to those images.
Is it possible or are plans to add it to velero?

Thank you

**Comment by chreichert** [comment]
@ywk253100 Is there anything happening here? I would even declare this as feature request.
For redundancy reasons it would be very much appreciated, when full disk snapshots would be stored in ZRS mode instead of LRS as it is current behaviour.
Thanks.

**Comment by reasonerjt** [comment]
@anshulahuja98 Could you answer this question?

**Comment by anshulahuja98** [comment]
https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/85299d0088599b1b134d46776fe8faa2d50ae470/velero-plugin-for-microsoft-azure/volume_snapshotter.go#L251C1-L263C1

I also checked the code, doesn't seem like anything explicit is being set and hence snapshots must be ZRS by default, let us know if you see behaviour otherwise.

**Comment by anshulahuja98** [comment]
Would request @chreichert to share some actual snapshots they have seen as part of backup in zonal regions as LRS as datapoint for investigation.
I would pick up POC post that.

**Comment by anshulahuja98** [comment]
Yes perfect. Incremental is the recommendation.
Will resolve the issue for now.

**Comment by chreichert** [comment]
Maybe some addition in the Azure Plugin docs would be helpful, that one should use incremental mode if ZRS snapshots are desired.

**Comment by anshulahuja98** [comment]
Valid suggestion. I'll do that.
