### ISSUE TITLE
Avoid leaving additional resources after taking csi snapshot

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#4761]
As a follow up to comment https://github.com/vmware-tanzu/velero/issues/4649#issuecomment-1040580012

Currently if we backup user's workload with CSI plugin it well leaves `volumesnapshots` and `volumesnapshotcontents` on user's cluster.
We should investigate if it's possible to mitigate this situation, for example set the deletion policy to retain and remove the CSI snapshot resources.  

Note this may impact the restore and deletion flow.  
If later we discover that the resources can't be deleted to ensure the successful B/R process, we may leave it as-is for the CSI plugin.

**Comment by blackpiglet** [comment]
After investigation, the VolumeSnapshotContent is still needed for backup deletion, because during backup deletion, the VolumeSnapshotContent is needed to delete snapshot resource on cloud provider.
VolumeSnapshot and VolumeSnapshotContent have relation. If VolumeSnapshot is deleted and VolumeSnapshotContent is kept. CSI snapshot controller cannot handle the deletion of VolumeSnapshotContent correctly.
After PR #4832, the relation between VolumeSnapshot and VolumeSnapshotContent is untied, then it will be safe to delete VolumeSnapshot and keep VolumeSnapshotContent.
