### ISSUE TITLE
Make sure the backup sync controller will create the volumesnapshotcontent if it's removed manually.

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#4764]
When the volumesnapshotcontent is removed by user via kubectl (not deletebackuprequest in velero), the backup is in an incomplete status.

To avoid leaving orphan snapshot in the cloud:
1) We should make sure the backup will not be deleted if the volumesnapshotcontent does not exist in the cluster
2) We need to make sure the backup sync controller will create the missing volumesnapshotcontent even the backup exists.

**Comment by blackpiglet** [comment]
After discussion, we found there is a smart chance that Velero cannot handle it when the VolumeSnapshotContent is removed manually. Even if Velero restores the VolumeSnapshotContent, CSI snapshot controller may not delete it correctly due to the snapshot represented by VolumeSnapshotContent is already deleted in manually deletion.

Therefore, we think just put a warning to indicate that there is potential of orphan Snapshot as a warning will do.
