### ISSUE TITLE
Fail the backup with restic annotated volumes if restic servers is not up and running

### ISSUE THREAD

**Issue by lintongj** [vmware-tanzu/velero#4874]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]

If a backup includes restic annotated volumes while restic servers is not up and running, the backup will hang there for upto 4 hours by default. 

The original issue was reported by a user of velero-plugin-for-vsphere. But, there is nothing that vsphere plugin can do, as it should be general to velero running on any cloud provider. Need help from velero core team. 

**Expectation**: velero can fail fast the backup with restic annotated volumes if restic servers is not up and running.

cc: @xing-yang @cormachogan 

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

N/A

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

N/A

**Environment:**

- Velero version (use `velero version`): v1.5.1
- Kubernetes version (use `kubectl version`): unknown
- Kubernetes installer & version: unknown
- Cloud provider or hardware configuration: vSphere
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ywk253100** [comment]
@lintongj I'm wondering why the backup contains restic annotated volumes while the restic server isn't running? Is the restic server isn't installed or it got errors when starting? Just want to make sure this is caused by incorrect configuration or not?

**Comment by ywk253100** [comment]
Currently, Velero creates two separated CRs `PodVolumeBackup`/`PodVolumeRestore` to do the backup/restore with Restic
and watches the status change of the CRs to do the next work. So I don't think there is an easy way for Velero to improve in this case.

**Comment by Lyndon-Li** [comment]
Here share the investigation result:
**[Cause]** 
For each pod to be backed up by Restic, Velero creates a PodVolumeBackup CR
Velero then waits for the completion of processing the CR until a timeout of 4 hours
The CR is handled by PodVolumeBackup operator in the Restic server
If Restic is not installed, no one will handle the CR
As a result, the wait always reaches to the timeout

**[Analysis]**
Velero is using the normal way of communication between different modules in Kubernetes, that is, create CR->watch CR's status and wait. As soon as the CR is handled by the operator, its status is changed from New to InProgress
Therefore, as a straightforward solution, we can make a shorter timeout to wait until the status is changed to InProgress, for example, 1 or 2 min, to assure the operator is functioning
This works for one CR, but this doesn't work for a backup with hundreds/thousands of Pods (then there will be hundreds/thousands of CRs)
Velero has another drawback in this case - Velero current process the pods one by one in sequence. This means, even though the shorter timeout is fine for one pod, if we handle the pods in sequence, multiple shorter timeout come to a much longer timeout, possibly longer than the 4 hours timeout

**[Conclusion]**
We also have the requirement for backup parallelism
If we can back up pods in parallel, we will be able to take the aforementioned shorter timeout solution, because when the pods are handled in parallel, if we have every handling wait 1 or 2 min, the total handling time won't much larger than several minutes

Therefore, we can take this issue as part of the backup parallelism requirement and fix it

**Comment by Lyndon-Li** [comment]
**[Cause]**
Velero is using the normal way to handle communication between modules, that is, create a CR->wait on status of the CR. Specifically, for PodVolumeBackup, Velero creates the PodVolumeBackup CR then wait on the CR's status for the PodVolume Operator to handle the CR
When the operator handles the CR, it first set the CR's status from New to InProgress, then on completion, it sets the status to Finish or Fail
The PodVolume Operator runs inside the Restic server(daemonset). If Restic server is not installed, no one will handle the CR, as a result, Velero always waits until the timeout of the backup, 4 hours

**[Analysis]**
As a straightforward solution, Velero could check the CR's InProgress status within a shorter timeout, for example, 1 min. If no one handles the CR, Velero fails the backup after 1 min.
However, due to another drawback, this doesn't work for multiple pods. Velero submits/creates the CRs in sequence, it always waits for the finish of the current CR before creating the next one. This means, even though we use a shorter timeout for the InProgress status change, when there are 100 pods in one backup, Velero handles 100 CRs in sequence, which finally involves 1 min * 100 = 100 min time of wait. 

Moreover, in the next release, we will use Kopia for PodVolumeBackup, and we call Kopia code directly, users don't need to install Kopia, so from this point, the current problem doesn't happen for the new PodVolumeBackup.

**[Conclusion]**
Solution 1: We will create an all-in-one requirement: handling the pods in parallel in one backup, because this also brings other benefits, and we will fix this problem when implement the requirement.
Solution 2: When we have the new PodVolumeBackup backed by Kopia, the current problem could also be fixed

**Comment by Lyndon-Li** [comment]
[Cause]
For PodVolumeBackup, Velero creates the PodVolumeBackup CR then waits on the CR's status for the PodVolumeBackup controller to handle the CR
When the controller handles the CR, it first set the CR's status from New to InProgress, then on completion, it sets the status to Finish or Fail
The PodVolumeBackup controller runs inside the Restic server(daemonset). If Restic server is not installed, no one will handle the CR, as a result, Velero always waits until the timeout of the backup, 4 hours

[Solution]
The Restic daemonset pods have a label - "name"="restic", we will use this label to do some pre-flight check:
- As the existing logic, PodVolume backup always associates with a pod. PodVolume backup for this pod must run on the same node.
- Then we can check if there is a restic daemonset pod on that node
- If the restic daemonset pod is not present, it means the restic backup has no way to succeed, so we fail it immediately for the pod, and finally the overall backup status is PartiallyFailed

[More Info]
- This solution could solve this problem in the cases that Restic Daemonset pod is missing on a related node, for example:
-- Restic is not installed, as for the current issue
-- Restic daemonset pod is not scheduled on the node because of node taint
- PodVolume Restore has the same problem, we will fix it in the same way
- This solution only checks the existence of restic daemonset pods, it doesn't check the healthy of controllers running inside the pods, if they are not healthy, we still face the same problem - the backup/restore waits for 4 hours. But this is not in the scope of the fix
