### ISSUE TITLE
design for data-only restores

### ISSUE THREAD

**Issue by ncdc** [vmware-tanzu/velero#504]
If you have pods running in a cluster and you're using Ark to take backups of their PVCs, it would be nice to be able to do a data-only restore. In other words, for pods owned by deployments, replica sets, etc., create a new PV from a backup snapshot, associate it with a PVC, and update the deployment to use the new volume.

**Comment by ncdc** [comment]
cc @jbeda @dhanmm @emuetzel for input

**Comment by rosskukulinski** [comment]
This feature would be a great-use case for Ark.  We will need to spend some time thinking about the CLI UX & data models that would enable this capability.  I think this is a strong contender for new functionality for 1.0.0 or earlier.

**Comment by skriss** [comment]
Tentatively moving this into v1.3 - at a minimum, we should try to do the design work.

**Comment by nrb** [comment]
For anyone doing the design, consider differences between Velero-native snapshots and CSI volume snapshots

**Comment by onedr0p** [comment]
I am just chiming in to say this would be great from a GitOps perspective, all I care about is backing up and restoring the PVCs to my deployments.

**Comment by dejwsz** [comment]
I need it too! I think it is a must-have functionality. I described something similar here: https://github.com/vmware-tanzu/velero/issues/2598
My case relates to a restic daemon which is used to get volumes' content backup. What I need is to have an ability to restore old content of some volume leaving other project's objects in place. I think this is a quite common use case. I was not aware it is missing in Velero, I assumed it must be there but it turned out it isn't.

**Comment by pPanda-beta** [comment]
This is open for almost 2 yrs now, any workarounds to at least restore data to new PVs assigned with same PVC?

**Comment by stepan111** [comment]
As opposite to @dejwsz  I though of using restic snapshots to migrate PVCs in another k8s cluster. 
I have a bunch of stateful applications deployed with helm and miscellaneous operators. In common I expect that in new cluster  helm deployed application will use restored PVCs as it's own made. That feature can simplify management of stateful applications in declarative way.

**Comment by eleanor-millman** [comment]
Closing because it is gnarly to solve and we don't have enough interest yet to justify the development.

**Comment by dsu-igeek** [comment]
Closing again, first time didn't take

**Comment by yunusemrecatalcam** [comment]
when using velero native snapshots we can actually use selectors to just select pv,pvc to do that. But when we're using restic mode, I couldn't find a solution. And I couldn't find a solution for that, anyone facing this?
When I use selectors, it automatically uses snapshot mode I guess, even though I pass the flag --default-volumes-to-restic
Any help appreciated.
Here's my issue explaining a little more
https://github.com/vmware-tanzu/velero/issues/3832

**Comment by hofq** [comment]
This issue currently has more upvotes than all other open issues. Has your perspective on the problem changed in the meantime?
@Lyndon-Li (I think the other Guys aren't Affiliated with the Project anymore)

**Comment by Lyndon-Li** [comment]
Sorry, this is the first time I see this issue, but this indeed surprises me with so many votes on this issue.
At least for now after the first glance, my thoughts are similar to the previous conclusion --- I don't quite understand what prevents us from restoring the volume data together with the resources (the resource data are not large and are easy to dispose after restore). I see several use cases in the previous discussions, but I have to say that they are not general nor focused.

Since the requirements may not be general or focused, what about we create a full list of the use cases? We can make a start from here on and add them gradually. After we have the full list, we will be able to come out the best fit solution accordingly.

**Comment by hofq** [comment]
For our Current Situation, this would be our Use-Case:

**Easier Cluster Migrations**
We are currently in the process of migrating cluster A to Cluster B. In our Cluster we mainly operate 3rd Party Applications with Helm Charts and, more importantly, the OLM from ArgoCD
With the OLM it can get quite tricky to let the OLM Accept already existant pods, and tweaking it to do this without manual Changes to the Cluster.

If we clould just re-create the volumes, we can just add the Subscription to the OLM, and it will use the PVCs with the Attached PVs already present.

**Comment by draghuram** [comment]
I think the requirement can be summarized as the ability to be able to restore PVCs alone without including pods. Note that this is possible even today from snapshots (CSI and cloud provider) but FSB and snapshot data mover require Pod to be restored because that is how they access the PVC to write data. I don't think this restriction can be removed for FSB but it should be possible for snapshot data mover path to support it.

Since this issue is closed, it may be better to create a new one with clear user cases.
