### ISSUE TITLE
Restic PVC backup may break when a prior backup containing parent restic snapshotID is deleted or expired.

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#5130]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Inspected Velero and Restic code

We are forgetting snapshots in a backup being deleted (maybe TTL expired backup.) in backupDeletionReconciler
https://github.com/vmware-tanzu/velero/blob/9a5c3aceffdabbbd321ad0dd2a2501d061c366f1/pkg/controller/backup_deletion_controller.go#L437-L457

We are specifying forget command by snapshot ID
https://github.com/vmware-tanzu/velero/blob/8064421e83314c564aed4f804d3295f4ab68ee3f/pkg/restic/command_factory.go#L102-L108

Currently forget commands proceed to delete any snapshot ID specified without checking if the snapshot ID is a parent to another snapshot which maybe for another Velero backup that is expected to work.
https://github.com/restic/restic/blob/dba47d29d58813c9d3f523b9e3dd5ece111f1c57/cmd/restic/cmd_forget.go#L143-L146

**What did you expect to happen:**

We check first if snapshot ID being deleted is used in any other backup as a parent snapshot.

**The following information will help us better understand what's going on**:

Either do checks on our side or request restic repo forget <snapshotID> --keep-parents flag and implement them in velero.

https://github.com/restic/restic/issues/3832

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
I remember there are similar issues.
Snapshots related to backup will be deleted after backup expires. If related data has no reference after snapshot deleted, data will be pruned after a specific period. This may happen in scheduled backup cases.

**Comment by Lyndon-Li** [comment]
It sounds to me that there is no problem with deleting a parent snapshot for Restic. The reason is, the incremental mechanism that is used by Restic is file level instead of block level. Here file level incremental means:

- Restic checks the file's ctime, mtime, inode, etc. to decide whether a file has no change from its parent snapshots
- If the file is not changed, Restic creates a new entry referring to the same object that is referred by the entry in the parent snapshot
- After that, there will be one new reference to the object
- When the parent snapshot is deleted, only the snapshot information is deleted. The deletion of the objects is the work of prune
- When a prune happens, since there is at least one reference to the object, the object is not deleted either

In this way, the new backup/snapshot could still find its data.

**Comment by kaovilai** [comment]
Looking a little further into the code. This is called 
```
err := DeleteFilesChecked(gopts, repo, removeSnIDs, restic.SnapshotFile)
```
https://github.dev/restic/restic/blob/dba47d29d58813c9d3f523b9e3dd5ece111f1c57/cmd/restic/cmd_forget.go#L227
which calls 
```
deleteFiles(gopts, false, repo, fileList, fileType)
```
https://github.dev/restic/restic/blob/dba47d29d58813c9d3f523b9e3dd5ece111f1c57/cmd/restic/delete.go#L25

which just calls repo.Backend().Remove()

Looking at s3 backend, it call storage backend [minio.Client.RemoveObject()](https://github.dev/restic/restic/blob/dba47d29d58813c9d3f523b9e3dd5ece111f1c57/internal/backend/s3/s3.go#L411) immediately.

Nothing in this code path assures me that "only the snapshot information is deleted." Could you help me understand more @Lyndon-Li ?

**Comment by Lyndon-Li** [comment]
If we check what are the files to be deleted in the same function a little before calling DeleteFilesChecked, we will see that the files are snapshot files instead of object files.

Code that fill the files to be deleted is [here](https://github.dev/restic/restic/blob/dba47d29d58813c9d3f523b9e3dd5ece111f1c57/cmd/restic/cmd_forget.go#L145):
```
	for sn := range FindFilteredSnapshots(ctx, repo.Backend(), repo, opts.Hosts, opts.Tags, opts.Paths, args) {
		snapshots = append(snapshots, sn)
	}

	var jsonGroups []*ForgetGroup

	if len(args) > 0 {
		// When explicit snapshots args are given, remove them immediately.
		for _, sn := range snapshots {
			removeSnIDs.Insert(*sn.ID())
		}
	} 
```

The `snapshots` slice comes from [FindFilteredSnapshots](https://github.dev/restic/restic/blob/dba47d29d58813c9d3f523b9e3dd5ece111f1c57/cmd/restic/find.go#L11). Inside the function it calls [LoadSnapshot](https://github.dev/restic/restic/blob/dba47d29d58813c9d3f523b9e3dd5ece111f1c57/internal/restic/snapshot.go#L64) and there you will see how the snapshot file is loaded, the `FileType` parameter is specified as `SnapshotFile`:

`err := loader.LoadJSONUnpacked(ctx, SnapshotFile, id, sn)`

And [here](https://restic.readthedocs.io/en/v0.2.0/Design/#:~:text=A%20snapshot%20is%20a%20JSON%20document%20that%20is%20stored%20in%20an%20encrypted%20file%20below%20the%20directory%20snapshots%20in%20the%20repository) in the Restic doc explains what a snapshot file is.
