### ISSUE TITLE
Restic repository can become stale after bsl update

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#5226]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

create BackupStorageLocation to point to _**bucketABC**_
Create backup A with `defaultVolumeToRestic: true`

update BackupStorageLocation to point to _**bucketDEF**_ keeping the **same BSL name**
Create backup B with `defaultVolumeToRestic: true`

Object manifests for backup B are in _**bucketDEF**_
Restic backup data for backup B are in _**bucketABC**_

**What did you expect to happen:**
Object manifests, and restic backup data for backup B are in _**bucketDEF**_

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 
yes.

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
This issue was discussed when we were designing for kopia integration.  For kopia path, we decided that we are going to use the reference to BSL so that the change in the BSL will be reflected to the CR `backuprepository`.

For Restic path, b/c this was not a newly introduced issue, we decided we won't fix it.

@Lyndon-Li please double-check to make sure that this issue is fixed in the e2e flow of kopia.

**Comment by reasonerjt** [comment]
As for the restic path, we'll check the PR #5227, but IMO it exists since the resticIdentifer was introduced, so may not be a high priority for us.

**Comment by kaovilai** [comment]
Just something I noticed and decided to give a go fixing in #5227 but haven't received reports of people experiencing this issue (maybe they don't know?) yet. So until then you could say it's not high priority.

**Comment by Lyndon-Li** [comment]
Double checked Kopia's workflow, for each connecting try, Velero acquires the latest configuration from BSL and then use them for the connection that finally calls Kopia's Connect function. Kopia's Connect first tries to connect to the remote storage, then update its config file so as to make it up-to-date.

As the current design, for each PodVolume Backup/Restore, we make this connecting try one time. This is for multiple reasons. This means, we will not have this problem, because the configuration is updated to Kopia before each PodVolume Backup/Restore runs.

@qiuming-best Please make sure ensureRepoConnect is called by the uploader for each PodVolume Backup/Restore.

**Comment by Lyndon-Li** [comment]
Remove the `kopia-integration` label from this issue as an equivalent issue for Kopia has been opened.

**Comment by Lyndon-Li** [comment]
I reconsidered the related workflow, my understanding is as below:
1. As per my understanding, even restic path doesn't result in the result - "Restic backup data for backup B are in bucketABC". When a new backup is created after the BSL update, Velero retrieve the new config from BSL and create a repoIdentifier in PVB. Then PVB uses the new repoIdentifier to do the backup.
2. However, there indeed a problem in backuprepository. When BSL is updated, the existing backuprepository resource is not invalidated, as a result, the controller will not initialize/connect to the new location in the object storage. As a result:
The PVB will fail if the repo has never been initialized in the new bucket
Or the PVB will fail late if the new config has some problem; on the other hand, it is the backuprepository's task to do this validation during its connection procedure but backuprepository doesn't work
Or PVB will succeed if the repo has been initialized once previously and the configs are correct. Merely, the backuprepository doesn't do its work

**Comment by Lyndon-Li** [comment]
@kaovilai For point 1, if my statements are wrong, please correct me. Thanks.

**Comment by Lyndon-Li** [comment]
Let me add this to 1.11 candidates and we can discuss more during 1.11 plan.

**Comment by Lyndon-Li** [comment]
To solve this problem, we need to watch the BSL's storage information fields change only and if changes happen, invalidate the related backupRepositories. We don't want to invalidate the backupRepositories when BSL is changed for any other fields or invalidate the backupRepositories periodically, because that will invoke frequent unnecessary storage access and bring the risk that the frequent repo initialization/connect operation corrupts the backup repository data.

However, to fulfill "watch the BSL's storage information fields change only" is not easy under the current kubuilder controllers, because kubuilder doesn't tell us the changed parts or the old object in the reconciler. The only way to do this is as follows:

- Create a new BSL controller
- Use the [predicate mechanism](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/predicate) to filter the fields we want to monitor
- Invalidate the related backupRepositories in the reconciler

This change is not too complex but it is annoying because we need to add a new controller

**Comment by Lyndon-Li** [comment]
Fixed by #5768
