### ISSUE TITLE
Velero is validating BSL every 10 seconds even though validation frequency is in hours in v1.9.1

### ISSUE THREAD

**Issue by sgatdell** [vmware-tanzu/velero#5250]
**What steps did you take and what happened:**

Velero is validating BSL every 10 seconds
We see these messages every ~10 seconds in v1.9.1 and every minute in v1.9.0

time="2022-08-26T01:46:50Z" level=info msg="BackupStorageLocations is valid, marking as available" backup-storage-location=velero-ppdm/k8s081722-ir-fc1873badb0392fffdc4a3e36828755e15e96d326471e79fe1861ad0bbae395a.stagings controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:115"
time="2022-08-26T01:46:50Z" level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/0/4)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:172"

**What did you expect to happen:**

The validation frequency has been disabled effectively by specifying validationFrequency: 8760h0m0s in Velero BSL
The validation frequency in BSL is not being honored. Although v1.9.1  has fix for this per release notes, it is not working.

**The following information will help us better understand what's going on**:

Velero debug logs are attached.
[velerodebuglog.txt](https://github.com/vmware-tanzu/velero/files/9429871/velerodebuglog.txt)

**Environment:**

- Velero v1.9.1 and v1.9.0
- Kubernetes version 1.21

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
@sgatdell 
Sorry for the inconvenience of using Velero, per my understanding, I think this error is not caused by BackupStorageLocation controller bug. It seems there is a mismatch between Velero binary and Velero CRDs.
In Velero v1.9.0 Release, all Velero CRDs' status sub-resource section is deleted.
As a result, if Velero image is updated to v1.9.1, but the CRDs are still using v1.8 version. Velero will constantly write Velero CRD status into the non-existing place. That will cause error.

Please try with installing Velero from scratch by commands `velero uninstall` and `velero install`.
