### ISSUE TITLE
velero 1.9.1 unable to create lock in backend: repository is already locked exclusively by PID

### ISSUE THREAD

**Issue by andy108369** [vmware-tanzu/velero#5268]
Velero 1.9.1 is unable to create lock in backend: repository is already locked exclusively by PID - no matter if I scaled the entire restic daemonset to 0 and then back to 1.

1st attempt:

```
time="2022-08-30T21:21:40Z" level=error msg="Error backing up item" backup=velero/velero-default-20220830212127 error="pod volume backup failed: running Restic backup, stderr=unable to create lock in backend: repository is already locked exclusively by PID 93344 on velero-6df6454fb-xzfw7 by nonroot (UID 65532, GID 65532)\nlock was created at 2022-08-30 21:19:42 (1m57.784874958s ago)\nstorage ID 515be1ea\nthe `unlock` command can be used to remove stale locks\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:199" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:417" name=fiohistory-0
```

2nd attempt:

```
time="2022-08-31T08:22:16Z" level=error msg="Error backing up item" backup=velero/velero-default-20220831082202 error="pod volume backup failed: running Restic backup, stderr=unable to create lock in backend: repository is already locked exclusively by PID 188273 on velero-6df6454fb-xzfw7 by nonroot (UID 65532, GID 65532)\nlock was created at 2022-08-31 08:19:53 (2m22.428282514s ago)\nstorage ID b189c185\nthe `unlock` command can be used to remove stale locks\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:199" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:417" name=fiohistory-0
```

This seem to be limited only to the same Pod I've mentioned in https://github.com/vmware-tanzu/velero/issues/5251

Checked the node running `fiohistory` pod -> there are no stale `velero` / `restic` processes there.

Any ideas why would it constantly unable to create the lock? I'd understand if the PID was the same, then it must be some stuck lock file which needs to be cleared, but, it appears, not this case.

**Comment by Lyndon-Li** [comment]
This lock doesn't exist in the local file system but in the Restic repository in the remote object store.
Nearly all Restic operations acquire this lock, some acquire share locks, for example, backup, snapshot list, etc.; some acquire exclusive locks, for example, snapshot delete, prune, etc.
These operations will be invoked by Velero during backup/restore routinely or specially in some cases. 

Velero has a mechanism to check the orphan Restic locks every 30min, however, if this problem happens frequently, the orphan locks may not be the cause.
Another possibility is, the Prune has been invoked by Velero, since the Restic Repository is very large, it is possible that the Prune cannot finish its work and so block all other backups, because Prune acquires exclusive locks.

Therefore, to troubleshoot this, please check which process the PID `188273` or `93344` stands for, what is the command line of this process. We get the command line, we get the Restic operation Velero is doing.

**Comment by andy108369** [comment]
>Another possibility is, the Prune has been invoked by Velero

I think this is the case now that I've just reinstalled the Velero (am using helm chart based installation).
The PID from the lock file relates to `restic prune` process which is still running.

I also had to manually remove the stale lock file off of the GCP repo because `Running maintenance on restic repository` was hitting the old PID throwing an error every ~ 2 seconds -- I think the timeout for this operation should probably have exponential back-off with the limit of 5 mins in total or so instead of hitting the S3 compatible server every 2 seconds.

The `restic prune` is now downloading lots of data, probably verifying the backup location as am seeing some messages like `Validating BackupStorageLocation` are appearing after I've reinstalled the Velero.

**Comment by Lyndon-Li** [comment]
> The PID from the lock file relates to restic prune process which is still running
You need to uninstall Velero then reinstall it, so that the Velero namespace could be deleted by Kubernetes and Velero pods could be killed.
Without uninstall first, it equals to doing nothing since all objects in Velero namespace exist.

> exponential back-off with the limit of 5 mins
Not quite understand what this means. Let me explain what happens first. 
Velero indeed has a prune cycle which is much longer than 2 seconds or 5 mins. The current problem is, every time the prune try fails because of the lock, so it keeps trying to finish the prune for the current cycle. Therefore, adjust the cycle doesn't help.
On the other hand, is the Restic repo still usable if prune fails? I guess so, though it is harder and harder to be used since in the repo, there is more and more fragment and unused data. 
Therefore, we might be able to do an enhancement here -- if the prune keeps fail, skip the prune run for the current cycle. Is this what you mean?

> probably verifying the backup location as am seeing some messages like Validating BackupStorageLocation
Not actually. Prune is purely a Restic operation, whereas, BackupStorageLocation is a Velero object. Restic has no knowledge of Velero objects and Velero doesn't know what Prune does either.

> The restic prune is now downloading lots of data
This is because Restic needs to download the data and then checks the status, i.e., how many orphan blocks, what is the status of fragment, etc. Totally speaking, Restic prune needs to download lots of data from the remote storage, there is nothing abnormal for Restic prune behave like this.

**Comment by andy108369** [comment]
>> The PID from the lock file relates to restic prune process which is still running
> You need to uninstall Velero then reinstall it, so that the Velero namespace could be deleted by Kubernetes and Velero pods could be killed.

That's exactly what I did an hour ago and have then seen the lock file was still there, preventing `Running maintenance on restic repository`.


>> exponential back-off with the limit of 5 mins
> Not quite understand what this means

Please check this one https://gist.github.com/andy108369/5d8088296c5cd10facf5c1384e0dc392 -- it checks for the lock every 2 seconds based in that log, until I've removed the lock file manually. (That happened after I've reinstalled the Velero, that lock file must have came from the previous Velero installation or so.)
But the idea is that it is running that check every 2 seconds which does not look right.


> Prune is purely a Restic operation, whereas, BackupStorageLocation is a Velero object.

This is clear to me, the issue is that Velero seem to be re-starting Restic every 2 seconds. (I haven't mentioned the `prune` operation in the 2nd paragraph so I was not implying it there.)

> there is nothing abnormal for Restic prune behave like this.

Yeah, I did not mean to imply its behavior is abnormal, but thanks for the explanation! :)

**Comment by Lyndon-Li** [comment]
> Please check this one https://gist.github.com/andy108369/5d8088296c5cd10facf5c1384e0dc392 

The problem shown in the log is exactly what I meant, it keeps trying to finish the prune for the current cycle but it always fails. So I proposed this enhancement -- if the prune keeps fail, skip the prune run for the current cycle.

If this is what you meant, please open a new issue (since we have discussed many things in the current issue) -- Velero prune keep retires every 2 second when one prune fails. Please also attach the log to the issue.

**Comment by Lyndon-Li** [comment]
> That's exactly what I did an hour ago and have then seen the lock file was still there
Sorry, I missed one thing. 
First of all, uninstall then reinstall, this operation is required. 
Secondly, when you uninstall Velero, Velero's pods are killed, so the Restic prune process is killed. However, the lock is left over in the Restic repo remotely.
Therefore, either you need to manually remove the stale lock or you need to wait for 30 seconds for Velero's stale lock recycle mechanism to remove it.

**Comment by andy108369** [comment]
=> https://github.com/vmware-tanzu/velero/issues/5276
