### ISSUE TITLE
mutil-pod use same pvc not backup

### ISSUE THREAD

**Issue by BAMSHK** [vmware-tanzu/velero#5458]
case:  A and B pod use same pvc， but A pod unmount pvc，B pod mounted pvc.    backup A pod skip pvc (because pvc not mount), backup B pod skip pvc(because pvc in podVolumeSnapshotTracker)

![image](https://user-images.githubusercontent.com/40750078/196404790-162d1b74-c4fd-43a3-b433-64d0478e8edb.png)
![image](https://user-images.githubusercontent.com/40750078/196404969-234e71e2-5261-40a6-acb6-6f7273962b24.png)

**Comment by qiuming-best** [comment]
@BAMSHK thanks for your report, Indeed, it's one bug, we will fix later

**Comment by Lyndon-Li** [comment]
The both issues mentioned here indicate two fundamental problems:
1. Velero's resource backup is not from something like a "snapshot" but by dynamically calling the api server, so the resource backup itself is not consistent
2. Velero's resource backup is not consistent with its data/pv backup

We will try to address them in future releases, before we finish it, there will be more or less similar issues.

**Comment by Lyndon-Li** [comment]
First of all, this is a problem in a transitional scenario.
Secondly, an ultimate way to fix this kind of problem is like below:
1. Take a snapshot of the object to be backed up, in this case, it is the kubernetes resource
2. Backup from the snapshot

Since we back up from the snapshot, the transition will not happen, the PVC is either mounted to pod A or pod B during the entire backup process.

**Comment by Lyndon-Li** [comment]
@BAMSHK Could you double confirm how the mount/unmount happened:
1. When did the mount/unmount happen? Did it happen during the backup
2. How did the mount/unmount happen? Is this a normal behavior of your workload? Or did you do this manually?

**Comment by Lyndon-Li** [comment]
Fixed by #5769
