### ISSUE TITLE
Support for vmware

### ISSUE THREAD

**Issue by domcar** [vmware-tanzu/velero#560]
Hello,

i was wondering if there is the possibility to use Ark with a local K8S cluster (vmware) or if you guys are planning to add this possibility in the future. It would be especially interesting the possibility to make snapshots of k8s volumes.

Thanks
Domenico

**Comment by rosskukulinski** [comment]
Hi @domcar.  Ark is not restricted to only cloud providers - it also works on local/on-prem clusters, though it depends on the storage provider for Persistent Volume snapshots.

What storage system are you using with vmware?

**Comment by domcar** [comment]
Hi @rosskukulinski Can you help me understand how ark works on-prem? Unfortunately I can't see any documentation about it. 
For example for `backupStorageProvider/name` the doc says `Ark natively supports aws, gcp, and azure. Other providers may be available via external plugins.` (Regardless of PV snapshots)

**Comment by rosskukulinski** [comment]
hi @domcar.  Ark's backup & restore model covers two types of data:

* Kubernetes API Objects (e.g. what's running in your cluster -- Pods, Services, Secrets, etc.)
* Block Storage (e.g. Persistent Volume) data

The Kubernetes API Objects are stored in a an Object Storage system (like Amazon S3, or Minio for on-prem).

As for block storage, Ark supports Amazon EBS, Azure Managed Disks, and Google Persistent disks, and since v0.6.0, Ark has had a plugin model for developers to build additional storage backends.

While no one has created vSphere backend for Ark, you can use the new restic integration, which can support backing up and restoring data from _any_ Kubernetes volume or persistent volume.

For more information, please see our announcement blog post: https://blog.heptio.com/ark-v0-9-alpha-now-with-restic-14ad6b402ab3

**Comment by domcar** [comment]
Thanks, i'll have a look at the 0.9 version of ark. I'll close this issue

**Comment by rosskukulinski** [comment]
Re-Opening as we should revisit what a vSAN plugin for vSphere might look like.

**Comment by skriss** [comment]
https://github.com/vmware-tanzu/velero-plugin-for-vsphere

I'm going to close this issue out as the vSphere plugin has been created; feel free to open any new issues related to it in that repo!
