### ISSUE TITLE
No docker manifest for v1.10.1

### ISSUE THREAD

**Issue by mimek** [vmware-tanzu/velero#5845]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I'm trying to get docker manifest for latest version: v1.10.1 with command
` docker manifest inspect velero/velero:v1.10.1`

**What did you expect to happen:**
docker manifest should be returned in output. It works for previous version: v1.10.0 but for the latest one response is:
`no such manifest: docker.io/velero/velero:v1.10.1`

Is it some issue with releasing method or with dockerhub itself?

**Comment by chri4774** [comment]
We have the same issue here with tag v1.10.1 while v1.10.0 still works.
When trying to download the manifest with curl I get the following error message:
```
$ curl -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/velero/velero/manifests/v1.10.1
{"errors":[{"code":"MANIFEST_UNKNOWN","message":"OCI index found, but accept header does not support OCI indexes"}]}
```
Doing the same with v1.10.0 I get a valid json response
```
curl -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/velero/velero/manifests/v1.10.0
{
   "schemaVersion": 1,
   "name": "velero/velero",
   "tag": "v1.10.0",
   "architecture": "amd64",
   "fsLayers": [
      {
         "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "blobSum": "sha256:96561b69016245ae5352ccf1dc45b293cb662610979de3859ead0e2b9d8cfe19"
      },
      {
         "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "blobSum": "sha256:fda4ba87f6fbeebb651625814b981d4100a98c224fef80d562fb33853500f40e"
      },
      {
         "blobSum": "sha256:8fdb1fc20e240e9cae976518305db9f9486caa155fd5fc53e7b3a3285fe8a990"
      }
...
```

**Comment by reasonerjt** [comment]
The difference is that in v1.10.1 the pushed artifact is an OCI index 
` "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json"`
And in v1.10.0 the it is a docker manifest list
`"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json"`

The reason for this change seems to be due to an upgrade of docker Buildx, the older (~3 months) releases were built with Buildx v0.9.x, like  
https://github.com/vmware-tanzu/velero/actions/runs/3730003360/jobs/6326549587
and since velero v1.10.1 and v1.9.6 the Buildx was bumped to v0.10.x like 
https://github.com/vmware-tanzu/velero/actions/runs/4099803314/jobs/7070388593
