### ISSUE TITLE
Kopia uploader do not work with service account that assume an IAM role

### ISSUE THREAD

**Issue by stephanDesj** [vmware-tanzu/velero#5875]
### Discussed in https://github.com/vmware-tanzu/velero/discussions/5874

<div type='discussions-op-text'>

<sup>Originally posted by **stephanDesj** February 17, 2023</sup>
Hi, him evaluating Velero 1.10 with kopia uploader in an EKS Cluster.
The velero server and the node-agent pod is configured with a service account that mount the AWS credentials on the pod. This was working fine with restic, but when I test with Kopia, I have this error:

time="..." level=error msg="Error backing up item" backup=... error="backup repository is not ready: error to get repo options: error to get repo credentials: **error get s3 credentials: missing credential file**" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/repository/backup_repo_op.go:83" error.function=github.com/vmware-tanzu/velero/pkg/repository.GetBackupRepository logSource="pkg/backup/backup.go:425" name=main-velero-76f5b7d6cf-5n2lw

Looks like with Kopia integration is not able to pickup the mounted credential and ask for a credential file instead.
</div>

Error is in the Kopia provider when executing GetStoreOptions,
it's calling
funcTable.getStorageCredentials that call getS3Credentials that is implemented in /pkg/repository/config/aws.go line 57.
and if you look the code, it's forcing the use of a shared credential file.

Possible solution will be to change that part and check that if credentialsFile == "", try to create a session without it and only if the session is not created, throws the errors.New("missing credential file").

**Comment by Lyndon-Li** [comment]
Velero 1.10 is integrating with Kopia 0.10.7 which support static file credentials only.
Checked Kopia release notes, IAM credentials are not supported until Kopia 0.12.0, as you can see [here](https://github.com/kopia/kopia/releases#:~:text=New%20Feature%20add%20AWS%20IAM%20as%20a%20credential%20provider%20for%20s3%20storage%20(%232213)%20(%232222)%20by%20Jarek%20Kowalski).

It means even though we let Velero go with an empty credentialsFile in the function `GetS3Credentials`, Kopia will still fail since it doesn't set credentials.IAM in the `newStorage` function.

**Comment by reasonerjt** [comment]
This will be fixed by bumping up kopia to 0.13

**Comment by rshiva777** [comment]
@reasonerjt / @Lyndon-Li ,

i am facing the same credential issue.

could you please let me know how can we bump up kopia to 0.13 on the velero setup installed with 1.11.0 Version

**Comment by Lyndon-Li** [comment]
@rshiva777 
For some compatible reasons, we cannot back port this, please wait for v1.12.
