### ISSUE TITLE
GKE Upgrade to v1.22 is blocked due to Velero using V1beta1 apiextensions in CRD

### ISSUE THREAD

**Issue by study-2023** [vmware-tanzu/velero#5895]
**What steps did you take and what happened:**
Currently, our servers are GKE Version 1.21 and we are due for Upgrading them to version 1.22. To prep for the Upgrade, we Upgraded  our current Velero version to v1.10 as 1.10 uis suppose to use only v1 api's and we should not have a problem in the v1.22 GKE version due to non supported v1beta1 Version.

**What did you expect to happen:**
Expected the warnings on the cluster for v1beta1 CRD for Velero are gone with the v1.10 upgrade but they are still shown.

**The following information will help us better understand what's going on**:

**Anything else you would like to add:**
We see the warning in the GKE regarding the Velero /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions for v1.10. Attached Screenshot. I am specifically looking for how to address the CRD's warning and why is it showing up.

**Environment:**

- Velero version (use `velero version`): v1.10
- Velero features (use `velero client config get features`): Restic (node-agent)
- Kubernetes version (use `kubectl version`): 1.21 (Upgrading to v1.22)
- Kubernetes installer & version: GKE
- Cloud provider or hardware configuration: GCP

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
@study-2023 
https://github.com/vmware-tanzu/velero/issues/5187#issuecomment-1216011712
There was an issue similar to your case.
This is specific to the upgraded v1.22 GKE cluster, and you can safely ignore those warnings because Velero just enumerates all available APIs in the kube-apiserver, and those supposed to be deprecated APIs are still serving in the upgraded v1.22 GKE cluster.

**Comment by winmillwill** [comment]
Sorry to necro, but I have the exact same issue and just ignoring the recommendation isn't a fix: In order to have velero AND automatic GKE upgrades I need to be able to prevent velero from accessing API's that are deprecated and being removed in the next k8s minor version.

I need GKE to not see velero accessing deprecated API's or GKE will halt automatic upgrades until that GKE version is EOL'd, or until 30 days have elapsed since last access (and those days won't elapse without access if velero is accessing those API's).

Is there a way to provide an allow or deny list of specific Group/Version/Kind indentifiers to velero, or provide a target kube version so that it won't try to list resources that are one or more of:
1. not allowed
2. explicitly denied
3. not compatible with the target kube version
?

AFAIK, simply giving it a kube rbac role without list or read access won't work because the apiserver will still see the request and trigger GKE the insight/recommendation and upgrade pause.

**Comment by blackpiglet** [comment]
There is no option that comes to my mind.
If GKE auto version upgrade is blocked by the warning, does the manual upgrade work for you?
