### ISSUE TITLE
Kopia slow restores

### ISSUE THREAD

**Issue by Nicky31** [vmware-tanzu/velero#5920]
**What steps did you take and what happened:**
Restoring a single app (Loki) with a 23GB PVC takes 1hour.  
The volume write throughput quickly reaches 6MB/s for a few seconds at the beginning, and then drops to 5-500 KB/s where it remains until the end.  
CPU usage is 0.3 (max 1), memory 800MB (max 2GB allowed), and I could have 150MB/s random write throughput when testing the disk with fio.    

I observed the same similar behavior with Restic. 

<img width="1614" alt="image" src="https://user-images.githubusercontent.com/2671265/221277890-c004b70d-b910-4d86-a270-a6c3c7698307.png">

I tried to restore Loki's volume directly from kopia CLI, and it succeeded in ~30 min, with an average 15MB/s throughput.  Why that difference ?  By setting `--parallel=32` in `kopia snapshot`, I managed to restore in ~15 min with an average 28MB/s. It looks like the bottleneck is on network side, having too many small files & high S3 download latency.

I also tested snapshotting & restoring a volume with a single 20GB file :  
- Backup took 5min & 20 sec (~70MB/s)
- Restore took 13 min (~30MB/s, still a bit slow, but maybe limited by the download throughput)

If the bottleneck is indeed my download latency & the only solution being higher --parallel, how can I tune this Kopia parameter from `velero restore create` ? From https://github.com/vmware-tanzu/velero/blob/main/pkg/uploader/kopia/snapshot.go#L302, this argument doesn't look configurable.  
Other than that, any thoughts ? 

**What did you expect to happen:**
That pvc would be restored much faster with times closer to https://velero.io/docs/v1.10/performance-guidance/.  

**Environment:**

- Velero version (use `velero version`): v1.10.1
- Velero features (use `velero client config get features`):  NOT SET
- Kubernetes version (use `kubectl version`): Client 1.21 & server on 1.19+
- Kubernetes installer & version: Cloud Container Engine
- Cloud provider or hardware configuration:  OBS
- OS (e.g. from `/etc/os-release`): EulerOS 2.0

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
There are two phenomenons you describe:
1. the volume writes throughput goes to  5-500 KB/s where it remains until the end.
2. Kopia performance has one significant difference with `CLI` and `Pod`

For 1:
I've done the test on the backup procedure,  I've not monitored the `Read/Write throughput`, the CPU and Memory usage seems curves are relatively flat. later I'll do some tests on the restore, and monitor the `Write throughput`

For 2:
we've done some tests on Kopia with `CLI` vs `Pod`, and the time consumption between them is apparent with nearly the same level of data. the difference is due to resource quota constraints in pods. 

**CLI:**
<img width="956" alt="image" src="https://user-images.githubusercontent.com/8985337/221777994-a3a3b0d6-e214-42b3-a0ae-785a642d42c6.png">
**POD:**
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/8985337/221778163-421a93b8-3fdb-4a1f-867a-c4d72179ee77.png">

**Comment by qiuming-best** [comment]
@Nicky31 As we don't have the test data to do the experience. If your backup data is no trade secrets involved could you share your data with us and I will do the restore test?

or could I provide you one image with Parallel configurable to test whether increasing concurrency works?

**Comment by Nicky31** [comment]
Oh, I didn't mention my volume had around 600-700K files

**Comment by Nicky31** [comment]
Any news on the configurable --parallel feature ?
