### ISSUE TITLE
Azure AKS cluster migration to Availability Zones

### ISSUE THREAD

**Issue by dineshlr** [vmware-tanzu/velero#5929]
Our team deployed Azure AKS in UAE North Zone in 2020, this was deployed without using Availability Zones, now part of the enhancements customer wanted this to spread across AZs.

Challenge is Azure AKS does not support migration to AZs without recreating or rebuilding the whole cluster, need to understand possible options for migrating to AZs with No /Minimum downtime.

**Comment by Lyndon-Li** [comment]
You can use Velero to finish one-way cross AZ migration:
1. Backup whatever namespace you want to migrate from the source cluster
2. Create a new cluster in the target AZ manually
3. Restore the namespaces into the new cluster
4. If you have some PVs to back up, just enable Velero file system backup. 
5. Don't use CSI snapshot or Volume snapshot method to backup PVs because Azure doesn't allow to visit the snapshots across AZs. Velero has a plan to support moving data from the snapshots, by then, you will be able to use these methods.
6. If you have some special configurations in the cluster scope, e.g., networks, it is recommended to rebuild them manually since Velero may have some problem to backup some cluster scope workloads

Furthermore, something you must know:
1. Velero is a backup/restore tool, not a DR tool. Therefore, it doesn't help to manage the business continuity, e.g., take over business from the target AZ. Therefore, the downtime (for migration case only) depends on how long time you can finish this manually
2. Velero's backup is not application consistent, therefore, there will some data lose for both the Kubernetes resources and the PV data during the backup

**Comment by anshulahuja98** [comment]
This can be addressed using #5880  where you can change the AZ pinning on your deployment/pvcs

Snapshots I believe are zonal in nature and can be used to restore disk in any zone.

**Comment by ywk253100** [comment]
@dineshlr Could you try the solution mentioned by @Lyndon-Li ?
