### ISSUE TITLE
Not able to restore Incremental Database Data

### ISSUE THREAD

**Issue by Chaitu7416** [vmware-tanzu/velero#6101]
**What steps did you take and what happened:**
Restore not happening properly on databases 

Created a Schedule for taking backups of just pv/pvc backing a postgresql database . 
Cluster Running on GKE 1.24
Created A Backup of the pv/pvc's with volume snapshots being done successfully using
```
velero backup create --from-schedule <Schedule-name> 
```
Altered the database creating some tables and schemas, when a restore happens with existing resource policy as update , it throws that the object is already the same version as the object in cluster , 

```
velero restore create --from-backup <backup-name> --existing-resource-policy update -restore-volumes true
```

when i run the same without the flag , it says object is different from the one in cluster.
```
velero restore create --from-backup <backup-name> 
```
**What did you expect to happen:**
Data in the databases to be restored to the point of backup. but it's not being restoring to the state of backup. 

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Attaching the bundle for both update none restore policies. 
[bundle-2023-04-10-15-35-18.tar.gz](https://github.com/vmware-tanzu/velero/files/11189817/bundle-2023-04-10-15-35-18.tar.gz)
[bundle-2023-04-10-15-46-41.tar.gz](https://github.com/vmware-tanzu/velero/files/11189818/bundle-2023-04-10-15-46-41.tar.gz)

**Anything else you would like to add:**
We just want data to be overridden by the data at the point of backup, we are restoring data from the volume snapshots being taken by the backups , so this backups at the data/filesystem level supported only with restic or can we continue to use the snapshots

when we delete the objects, like pv and pvc's and and restore from the backups able to get the data and all, we are not able to restore just the incremental data itself. 

**Environment:**

- Velero version (use `velero version`): 1.10.1
- Velero features (use `velero client config get features`):  NOT-SET
- Kubernetes version (use `kubectl version`): v1.24.9-gke.3200
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`): Ubuntu

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by sseago** [comment]
The existing resource policy allows for velero to patch the kubernetes resource on update. So a configmap, for example, would get updated since the kubernetes data will have changed. For a PVC, though, the kubernetes data may not have changed. Even it if has, patching the resource metadata won't modify files on disk. If you're using volume snapshots, the only way to get data from the backup into the PV would be to delete the PVC prior to restore, since volume snapshots are used as a source for a new PV, so they won't help you if you already have a PV with data in it. You should be able to use restic to update an existing volume, but only with a new pod, since the restic initcontainer on the mounting pod is needed as part of the restore process, so if you're using restic you probably need to delete the pod prior to restore.

**Comment by qiuming-best** [comment]
I think @sseago has answered your questions, If you have any other questions please add comments
