### ISSUE TITLE
Restore partially fails while restoring ingress

### ISSUE THREAD

**Issue by navilg** [vmware-tanzu/velero#6150]
**What steps did you take and what happened:**

I had a backup. While restoring from backup, Restore is partially failed with error 

time="2023-04-14T11:27:37Z" level=error msg="error restoring <ingress-name>: Ingress.extensions \"<ingress-name>\" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: \"nginx\": can not be set when the class field is also set" logSource="pkg/restore/restore.go:1287" restore=velero/<restore-name>

**What did you expect to happen:**

The backup was successful without any error. Ingress which it tried to restore was already present in cluster. So it should not have tried to restore it.

Also Ingress.extensions api-resource is not present in cluster, neither it can be seen in backups. So, It should not have anyway tried to restore it in cluster.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 1.8.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.23
- Kubernetes installer & version: GKE 1.23
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
@navilg 
The error message `Ingress.extensions "" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "nginx": can not be set when the class field is also set` was generated by Kubernetes not by Velero.
For why Kubernetes generates the error, [see here](https://github.com/kubernetes/kubernetes/blob/53cccbe4f98b9c6086af88954f5c9a77d8e66fc5/pkg/apis/networking/validation/validation.go#L272). 
Briefly, the story is like -- before creating Ingress, the API server validated the fields of the object to be created (the object passed to the api server), it saw the Ingress object is with the` kubernetes.io/ingress.class` annotation and `Ingress.Spec.Spec.IngressClassName` was also set, but the two values doesn't match, then it reported the error and blocked the creation so further blocked Velero restore.

Above is the direct cause. I am not sure if it is due to restoring on an existing resource.
Anyway, as Velero's restore policy, if there is an existing resource, the same resource should be be restored. And the error related to the create operation should not be regarded as a restore error. As @sseago mentioned, from v1.9, we have enhanced the method to check the already existing resource, so please try with v1.9 or above.

Conclusively, please verify if the error is due to the existing resource by deleting the existing resource and do a fresh restore. If so, the problem could be solved by upgrading to v1.9 or above.
Otherwise, if the error also happens to a fresh restore, let's further check the values mentioned above the` kubernetes.io/ingress.class` annotation and `Ingress.Spec.Spec.IngressClassName` field.

**Comment by brysk** [comment]
hello @Lyndon-Li 

I'm facing the same issue during Velero restore. My ingress doesn't have `kubernetes.io/ingress.class` annotation specified, only `IngressClassName`. Here's the error I got:

```
time="2023-06-05T15:42:32Z" level=error msg="Namespace default, resource restore error: error restoring ingresses.networking.k8s.io/default/sonarqube: Ingress.extensions \"sonarqube\" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: \"nginx\": can not be set when the class field is also set" logSource="pkg/controller/restore_controller.go:504" restore=velero/restore-1
```

**Comment by Lyndon-Li** [comment]
Closing as no further request, feel free to reopen it if required.
