### ISSUE TITLE
velero not restoring volumes with longhorn csi

### ISSUE THREAD

**Issue by kub3let** [vmware-tanzu/velero#6172]
**What steps did you take and what happened:**

I have setup velero using aws s3 and csi plugin to backup apps including longhorn volumes to s3.

While there is no error and backup shows as complete it does not include the volumes for some reason in the backup.

It does create volume snapshots but these are not restored by velero automatically.

This results in the restored pods being stuck in `ContainerCreating` due to `AttachVolume.Attach failed for volume rpc error: code = NotFound desc = volume pvc-xxxx not found` and ending in `Unable to attach or mount volumes: timed out waiting for the condition`

pv & pvc have been restored but volume is missing.

---

**What did you expect to happen:**

Velero restore should include the volumes.

I tried specifing `--snapshot-volumes` during backup and `--restore-volumes` during restore but that makes no difference.

---

**The following information will help us better understand what's going on**:

commands run: 
```
velero -n velero-system backup create sample-backup --csi-snapshot-timeout=20m --include-namespaces pyload --snapshot-volumes

# on fresh cluster
velero -n velero-system restore create --from-backup sample-backup --restore-volumes

velero -n velero-system debug --backup sample-backup --restore sample-backup-20230422204354 
```

[bundle-2023-04-22-21-02-10.tar.gz](https://github.com/vmware-tanzu/velero/files/11302285/bundle-2023-04-22-21-02-10.tar.gz)

**Anything else you would like to add:**

After a while i figured out I can still fully restore by doing the following

- delete the namespace that should be restored, otherwise velero won't override stuff
- manually restore the snapshot via longhorn which automatically got created by velero, this will restore the volume
- then run velero restore, pvc pv will be mapped to the volume that longhorn has restored and the pods succeed to start

**Environment:**

- Velero version (use `velero version`): v1.10.2
- Velero features (use `velero client config get features`): Not Set
- Kubernetes version (use `kubectl version`): v1.26.3+k3s1
- Kubernetes installer & version: k3s v1.26.3
- Cloud provider or hardware configuration: kvm testlab running debian cloud image
- OS (e.g. from `/etc/os-release`): Debian 11 (bullseye)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
Below error is reported by Kubernetes:
`AttachVolume.Attach failed for volume rpc error: code = NotFound desc = volume pvc-xxxx not found`

Looks like the CSI external attacher failed to find the volume that should have provisioned by the longhorn CSI driver.

This may be due to a misconfiguration of the longhorn storage, please try to create CSI VolumeSnapshot object manually in your env and then restore a PV from it, see if you could make it or not.
On the other hand, Velero CSI snapshot feature has not officially verified against longhorn, so not sure it is a common problem or not, though it is not likely possible since Velero is using the standard CSI API to create the request.
Finally, what you mentioned `backup apps including longhorn volumes to s3` cannot happen under the current version of Velero, because Velero doesn't support to move the CSI snapshot to S3 at present, in future releases, this will be implemented.

**Comment by kub3let** [comment]
Thanks @Lyndon-Li

This was more of a disaster recovery scenario (on a new cluster), longhorn is configured to save the snapshot automatically on s3. I did expect it to handle volume snapshots the same way but apparently it doesn't.

Velero restores on the same cluster work just fine.

And in case of disaster recovery you just have to restore the volume beforehand using longhorn like i wrote, so closing this.
