### ISSUE TITLE
Velero restore not restoring any data in persistent volumes

### ISSUE THREAD

**Issue by Hannessi** [vmware-tanzu/velero#6304]
**What steps did you take and what happened:**
I tried to do a backup and restore of a helm release of a self-managed gitlab instance. The backup and restore jobs completed successfully and all the resources (deployments, pvc and pv etc.) were indeed recreated. However, the persistent volumes were just "new" empty volumes and no data was restored.

**Backup command**
`velero backup create velero-gitlab-20230521-223002 -l "release=gitlab" --snapshot-volumes --ttl 168h --volume-snapshot-locations minio --include-namespaces cicd --default-volumes-to-fs-backup`

**Restore command**
`velero restore create velero-gitlab-restore-5 --from-backup velero-gitlab-20230521-223002 --restore-volumes=true --include-cluster-resources`

**What did you expect to happen:**
I expected the data within each persistent volume to be restored as well. 

**The following information will help us better understand what's going on**:

**Velero backup logs**
https://gist.github.com/Hannessi/d20e4f023de6aef19f9f4ab0f1859e2b

**Velero backup describe**
https://gist.github.com/Hannessi/8a9d6a6a15650edaee111efc0e18a659

**Velero restore logs**
https://gist.github.com/Hannessi/b28b1078d71c5a5c39e80fdf6321ba46

**Velero restore describe**
https://gist.github.com/Hannessi/55d3303330b773fe21311ea0796ab03b

**Anything else you would like to add:**
I attempted the restore a couple of times with different configurations, hence the warnings about some resource already existing.
Using node-agent (restic) daemon-set.
Restore is attempted on a different cluster with the same specs. 
OpenEBS 3.3.0 cStor is used as underlying storage for persistent volumes.

**Environment:**

- Velero version (use `velero version`): 
```
➜  ~ velero version
Client:
	Version: v1.11.0
	Git commit: -
Server:
	Version: v1.11.0
```

- Velero features (use `velero client config get features`): 
```
➜  ~ velero client config get features
features: <NOT SET>
```

- Kubernetes version (use `kubectl version`):
```
➜  ~ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.9
Kustomize Version: v4.5.7
Server Version: v1.21.6+b4b4813
```

- Cloud provider or hardware configuration:
Azure ARO cluster 4.8

- OS (e.g. from `/etc/os-release`):
```
sh-4.4# cat os-release
NAME="Red Hat Enterprise Linux CoreOS"
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by danfengliu** [comment]
Can you share you node agent log  with `kubectl logs  node-agent-xxxxx -n velero` ?

**Comment by Hannessi** [comment]
@danfengliu Sure, note I redacted the backup location URL and grep for the backup,

I also noted there's no reference to the restore in any of the node-agent pods, is this expected?
 
Pod 1
https://gist.github.com/Hannessi/83ae98ab0ee7d8ae8eb7863799716c55
Pod 2
https://gist.github.com/Hannessi/c89aa55f68fdcba088d4fbef2d3f137b
Pod 3
https://gist.github.com/Hannessi/9dccd1852e1fd9e9d19c0817992dc66c
Pod 4
https://gist.github.com/Hannessi/7e21a3026594b241901baca76e1f4ef3

**Comment by danfengliu** [comment]
Hi @Hannessi, no restore logs in node-agent pod logs is not expected, from restore logs you provided, it looks like pod volume restore returned immediately,   I tried to reproduce this issue, and it's not reproducible , except for label of target resource, other configuration of backup/restore is the same. In your logs, I saw a Openshit plugin involved, could you provide the velero install CLI configuration, openshift-velero-plugin is not in our maintaining scope, so we might need more information to identify the root cause.


If you can provide information below, it would be helpful:
- velero install cli
- velero describe backup backup-xxx --details
- velero describe restore restore-xxx --details


```
time="2023-05-22T12:20:53Z" level=info msg="Waiting for all pod volume restores to complete" logSource="pkg/restore/restore.go:551" restore=velero/velero-gitlab-restore-5
time="2023-05-22T12:20:53Z" level=info msg="Done waiting for all pod volume restores to complete" logSource="pkg/restore/restore.go:567" restore=velero/velero-gitlab-restore-5
 
```

**Comment by qiuming-best** [comment]
@Hannessi What  I noticed it's the output of this log `sg="Dynamically re-provisioning persistent volume because it has a pod volume backup to be restored." logSource="pkg/restore/restore.go:1146" restore=velero/velero-gitlab-restore-5`

The related codes is [here](https://github.com/vmware-tanzu/velero/blob/main/pkg/restore/restore.go#L1150), which means the pv could not be restored by velero even using Restic, we only re-provisioning persistent volume with empty dir.

[Here](https://github.com/vmware-tanzu/velero/discussions/3905) the related issues. 

```
		case hasPodVolumeBackup(obj, ctx):
			ctx.log.Infof("Dynamically re-provisioning persistent volume because it has a pod volume backup to be restored.")
			ctx.pvsToProvision.Insert(name)

			// Return early because we don't want to restore the PV itself, we
			// want to dynamically re-provision it.
			return warnings, errs, itemExists
```

**Comment by qiuming-best** [comment]
@Hannessi what's the detail type of your PV, maybe we need to add one warning for the unsupported PV.

**Comment by Hannessi** [comment]
Hi @danfengliu and @qiuming-best. That OpenShift plugin was indeed the culprit. Removing the Openshift plugin for Velero resulted in the pod volumes being restored. (I guess the OpenEBS plugin for Velero is now being used) We now see a "restore-wait" init-container being added to each pod that waits for the volumes to be restored. 

And the data within the volumes are indeed restored successfully!
