### ISSUE TITLE
Failed to make automatic prune operation

### ISSUE THREAD

**Issue by sherlant** [vmware-tanzu/velero#6360]
Hi,
i have a problem with my velero installation. The automatic prune action failed on my restic repo, and a lock still present.
This cause that the newest backups failed (partially failed).
I have try to run the prune command, and it works. I have also show the daemonset's pods, and i have no OOM. But in the velero's deploy logs, i show a signal kill when the maintenance task run.

velero version : 1.10
Kubernetes version : 1.21
[bundle-2023-06-06-08-52-46.tar.gz](https://github.com/vmware-tanzu/velero/files/11660908/bundle-2023-06-06-08-52-46.tar.gz)

Installation type : kubeadm on virtual machines
Os : Ubuntu 20.04

Thx for help !

**Comment by Lyndon-Li** [comment]
At present, Velero does restic prune in Velero server pod, that is why you saw oom of the Velero deploy pod.
Therefore, to solve the problem, you need to increase the memory limit for Velero deployment

**Comment by sherlant** [comment]
I have increase the ram, it seems to work. Thx.
But i see that the running maintenance run every 5 minutes. It's normal ? 
there is a way to modify this ?

**Comment by Lyndon-Li** [comment]
@sherlant 
Normally this should not happen, because the default maintenance period for Restic is 1 week.
Could you check below things:
1. Are all the maintenance for one repo? If you have multiple repos, each repo will have a maintenance task
2. Have the maintenance succeeded? If one maintenance fails, it will be relaunched after 5 min, the 5 min is the reconcile period of maintenance, or it means repo is checked for maintenance every 5 min
