### ISSUE TITLE
upgrade from 1.0.9 to 1.11.0: exclude volume from restic backup

### ISSUE THREAD

**Issue by r10r** [vmware-tanzu/velero#6378]
**What steps did you take and what happened:**

I've annotated some local caching volumes with the annotation `velero.io/exclude-from-backup=true` 
to exclude them from restic backups. This worked fine with velero v1.0.9. 

But after upgrading to 1.11.0 the volumes are included in backups again.

See also https://velero.io/docs/v1.9/resource-filtering/#excludes   
See also https://velero.io/docs/v1.11/resource-filtering/#excludes

**Comment by Lyndon-Li** [comment]
`velero.io/exclude-from-backup` cannot be used to exclude volumes during file system backup, because `velero.io/exclude-from-backup `is a resource level filter and file system backup is based on pods, so you can only exclude pod by this annotation, which means, all the volumes of the pod will be excluded.

Could you double check if there is any other filters applied during your running with 1.9?

**Comment by r10r** [comment]
@Lyndon-Li  Thanks for your response. I'll double check it with a test case later this day.

My initial goal was to exclude volumes from a storage class that provides node local storage.
Maybe you can take a look at the following discussion https://github.com/vmware-tanzu/velero/discussions/6379. Thanks!

**Comment by qiuming-best** [comment]
@r10r If you want to skip the backup of one specific storage class, maybe you could use [resource policies](https://velero.io/docs/v1.11/resource-filtering/#resource-policies), which is one new feature in v1.10 that could meet your requirement
