### ISSUE TITLE
When restoring with --include-cluster-resources=true, it will skip the PV restoring

### ISSUE THREAD

**Issue by iamjackhu** [vmware-tanzu/velero#6388]
**What steps did you take and what happened:**

The restoring will not work as expected, when --include-cluster-resources=true

**What did you expect to happen:**
All the resources in the backup file xxx.tar.gz should be restored 

**The following information will help us better understand what's going on**:

time="2023-06-13T06:35:32Z" level=info msg="Processing item" backup=velero-09ad8e66-1841-4933-ad50-162170ed0ae7/nginc-with-cluster-resource logSource="pkg/backup/backup.go:348" name=nginx-pv namespace= progress= resource=persistentvolumes
time="2023-06-13T06:35:32Z" level=info msg="Skipping item because it's already been backed up." backup=velero-09ad8e66-1841-4933-ad50-162170ed0ae7/nginc-with-cluster-resource logSource="pkg/backup/item_backupper.go:126" name=nginx-pv namespace= resource=persistentvolumes 

_If you are using velero v1.7.0+:_  v1.10
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

velero -n velero-09ad8e66-1841-4933-ad50-162170ed0ae7 restore describe
Name:         nginc-with-cluster-resource-20230613t063659826z
Namespace:    velero-09ad8e66-1841-4933-ad50-162170ed0ae7
Labels:       <none>
Annotations:  <none>

Phase:                                 InProgress
Estimated total items to be restored:  192
Items restored so far:                 192

Started:    2023-06-13 14:36:59 +0800 CST
Completed:  <n/a>

Backup:  nginc-with-cluster-resource

Namespaces:
  Included:  all namespaces found in the backup
  Excluded:  velero-09ad8e66-1841-4933-ad50-162170ed0ae7

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io, csinodes.storage.k8s.io, volumeattachments.storage.k8s.io, backuprepositories.velero.io
  Cluster-scoped:  included

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  true

kopia Restores (specify --details for more information):
  New:  1

Existing Resource Policy:   update

Preserve Service NodePorts:  auto

More detial, please refer the backup/restore log in the attachments:
[backup-cluster-resource.log](https://github.com/vmware-tanzu/velero/files/11731549/backup-cluster-resource.log)
[restore-cluster-resource.log](https://github.com/vmware-tanzu/velero/files/11731548/restore-cluster-resource.log)

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): v1.10
- Velero features (use `velero client config get features`): v1.10
- Kubernetes version (use `kubectl version`): v1.22.2
- Kubernetes installer & version: v1.22.2
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): CentOS7

The follow is the Nginx App yaml file:
[nginx-pv.yaml.txt](https://github.com/vmware-tanzu/velero/files/11731564/nginx-pv.yaml.txt)

Backup file .tar.gz, which contained the resource PV 'nginx-pv'
[nginc-with-cluster-resource.tar.gz](https://github.com/vmware-tanzu/velero/files/11731628/nginc-with-cluster-resource.tar.gz)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
According to the output of the `velero restore describe`, the PV is not restored because the restore is still in-progress, you can see the `kopia Restores` section contains 1 `New` item. You can check the status of `PodVolumeRestore` CR and the logs of `node-agent` pod if the `Kopia Restores` hang in `New`.
```
velero -n velero-09ad8e66-1841-4933-ad50-162170ed0ae7 restore describe
...
Phase: InProgress
...
Started: 2023-06-13 14:36:59 +0800 CST
Completed: <n/a>
...
kopia Restores (specify --details for more information):
New: 1
...
```

The following log could be ignored:
`time="2023-06-13T06:37:05Z" level=info msg="Skipping persistentvolumes/nginx-pv because it's already been restored." logSource="pkg/restore/restore.go:1015" restore=velero-09ad8e66-1841-4933-ad50-162170ed0ae7/nginc-with-cluster-resource-20230613t063659826z
`
The PV resource is put into the [restoredItems](https://github.com/vmware-tanzu/velero/blob/v1.10.0/pkg/restore/restore.go#L1018) map, but [it is not restored directly if filesystem backup is enabled](https://github.com/vmware-tanzu/velero/blob/v1.10.0/pkg/restore/restore.go#L1115), this why the PV is not restored yet but reported already restored.

The PV is restored when handling the pods.

**Comment by Lyndon-Li** [comment]
@iamjackhu 
Please check @ywk253100's update for why the PV was not created and why the `Skipping persistentvolumes/nginx-pv because it's already been restored` log could be ignored. And also, we have some other plan, with which, the log will be eliminated, so we will keep this issue open to track it.

For the problem as you mentioned that the restore was stuck, please help to upload the Velero log bundle when the problem happens, so that we could further troubleshoot it.

**Comment by Lyndon-Li** [comment]
The current focus is the below log:
`Skipping persistentvolumes/nginx-pv because it's already been restored`

This logic is expected since for fs-backup, volumes are restored along with pod object instead of PV object. However, the log is somehow confusing, since users may think the restore for the volume has been skipped.

As the previous discussion, in order to eliminate this log confusion, we need to:

- Either we add a filtering logics when collecting items to be restored, if a volume is processed by PVR, its PV/PVC object will not be collected. However, this will need to change the core logic of the restore item collection
- Or add the logics to remove the PV/PVC objects from the restore item collection when we are sure the volumes have been restored by PVR. This also needs to change the core logic of PVR

Let's discuss its value to make these changes.

**Comment by reasonerjt** [comment]
Per discussion, this may be a misunderstanding from the author as to why the PV is not restored.

I don't think we wanna change the current behavior and log messages.

Let's keep this in the backlog and wait for the input of the author.
