### ISSUE TITLE
add storage classes mapping when create a restore

### ISSUE THREAD

**Issue by wgkingk** [vmware-tanzu/velero#6390]
**Describe the problem/challenge you have**
I know that we can create a configmap to configure storageclasses mapping , but we hope that the storage class mapping will only take effect once in the corresponding restore task, rather than exist in the system for a long time.

**Describe the solution you'd like**
add storage class-es mapping when create a restore like namespace mapping 

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by sseago** [comment]
It sounds like there are two different use cases here:
1) general mapping applicable everywhere: i.e. there are several backups from a cluster with a different set of storage classes than the current cluster, so we need the mapping all the time or restores will fail
2) one-off "I need to change my storage type for this workload" restores.

1) is handled by the current code. This issue is requesting support for 2). If we decide to implement 2), we need to make sure we don't break 1). My suggestion, if we want to do this, would be to add a storage class mapping spec field which points to a *different* configmap from the global one -- the global one is the one with the "velero.io/change-storage-class" label. Then the change storage class plugin would first check for the presence of an explicit mapping configmap for this restore, if not found, looks for one with the change-storage-class label, if none found, then no mapping is applied.

**Comment by ywk253100** [comment]
Seems this use case can be filled if we implement the [JSON Substitutions in Restore workflow](https://github.com/vmware-tanzu/velero/pull/5880), it is more general solution for such cases

**Comment by anshulahuja98** [comment]
Yes it will be addressed as part of impl of https://github.com/vmware-tanzu/velero/pull/5880 which is underway and targeted for 1.12

**Comment by reasonerjt** [comment]
Since JSON substitution has been merged into `main` branch and will be delivered in v1.12.0, I'm closing this issue

**Comment by likku123** [comment]
@anshulahuja98 

Can you please throw some sample around the restore using multiple storage class.

I tried looking into this page https://velero.io/docs/v1.15/restore-reference/ and looking for example on how to create a multiple restore jobs the same time with different storage class

**Comment by anshulahuja98** [comment]
Firstly JSON Substitution is a config map that you create with appropriate settings.

For Restore A
You can create  ConfigMap A -> this can contain mapping of multiple storage classes, 
velero restore create --resource-modifier-configmap ConfigMapA

Similarly you can use a different config map for a different restore job.

For doing multiple storage class mappings in one restore, you can just add more rules in the resourcemodifier payload.
