### ISSUE TITLE
Velero Backups are getting Partially failed

### ISSUE THREAD

**Issue by kkavin** [vmware-tanzu/velero#6413]
**What steps did you take and what happened:**
We are taking daily backups for every 4 hour using Velero and Restic the backup is getting **partially failed** with errors

`time="2023-06-20T22:20:03Z" level=error msg="Error checking repository for stale locks" controller=restic-repo error="error running command=restic unlock --repo=gs:velero-shqm-prod:/restic/velero --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic, stdout=, stderr=Resolving password failed: Fatal: /tmp/credentials/velero/velero-restic-credentials-repository-password does not exist\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/repository_manager.go:276" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*repositoryManager).exec" logSource="pkg/controller/restic_repository_controller.go:144" name=velero-default-mpsl8 namespace=velero

time="2023-06-20T22:20:03Z" level=info msg="1 errors encountered backup up item" backup=velero/sch-backup-shqm-prod-daily-20230620141932 logSource="pkg/backup/backup.go:413" name=indexserver-0

time="2023-06-20T22:20:03Z" level=error msg="Error backing up item" backup=velero/sch-backup-shqm-prod-daily-20230620141932 error="timed out waiting for all PodVolumeBackups to complete" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:177" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:417" name=indexserver-0
`

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):  v1.8.1
- Kubernetes version (use `kubectl version`): 1.23
- Kubernetes installer & version: 1.23
- Cloud provider or hardware configuration: GCP

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
I found several things need note-worthy.
First it's the Restic command failure. Usually, this means Restic DaemonSet or the Velero Server Deployment's memory resource is not enough, and kubelet killed the pods due to OOM, which makes the pod left stale lock behind.
"Error running command=restic backup --repo=gs:velero-shqm-prod:/restic/shqm --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic . --tag=pod-uid=b1d49683-2095-4313-9879-9ff5e6eac2f9 --tag=pvc-uid=3d913cc7-b770-4ce1-84fd-e47dff80e02e --tag=volume=d2classic-vct --tag=backup=sch-backup-shqm-prod-daily-20230413221536 --tag=backup-uid=cec82176-7e68-4582-989b-fb246c16c5e9 --tag=ns=shqm --tag=pod=d2classic-0 --host=velero --json --parent=1af9eb2e, stdout=, stderr=unable to create lock in backend: repository is already locked exclusively by PID 452841 on velero-56468fc46b-q6j89 by nonroot (UID 65532, GID 65532)\nlock was created at 2023-04-14 00:17:48 (1m24.842325082s ago)\nstorage ID 5291ec40\nthe `unlock` command can be used to remove stale locks\n"

Second, there is multiple velero server pods' log found in the bundle. There is only one has log, but that is not a good practice. Please clean the environment.

Third, Restic pods reported several times that they cannot find the pods or the volume directories. Looks like there are several pods changed after Restic backup started.

**Comment by kkavin** [comment]
We are facing the same issue in different cluster I have attached the debug logs below. 
As mentioned, we are in the process of cleaning up the environment. 

[velero-Partiallyfailed.zip](https://github.com/vmware-tanzu/velero/files/11847455/velero-Partiallyfailed.zip)

`time="2023-06-23T02:03:22Z" level=error msg="Error backing up item" backup=velero/sch-backup-renl-prod-daily-20230622220321 error="timed out waiting for all PodVolumeBackups to complete" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:177" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:417" name=velero-595fb46b8-d875x
`

**Comment by kkavin** [comment]
@blackpiglet Any updates on the issue ?

**Comment by noovertime7** [comment]
I have the same problem: unable to create lock in backend: repository is already locked exclusively by PID 1422 on velero-6b95b6bd7b-m2xqz by nonroot (UID 65532, GID 65532)
I have tried restarting node-agent and velero pod in Kubernetes and deleting the locks folder in minio, but the problem is not solved, is there any other method or idea?  @blackpiglet

**Comment by blackpiglet** [comment]
@noovertime7 
The lock is created in the MinIO repository, so restarting Velero doesn't work. 
I think there was another process that also required the lock in the MinIO, and that caused the conflict.
Please check whether this MinIO repository is also shared by other cluster's Velero backup locations or other backup tools.

**Comment by noovertime7** [comment]
Thanks for the reply, I tried once again restarting velero with node-agent and increasing velero's request and limit, the problem was solved and everything is fine now! @blackpiglet
