### ISSUE TITLE
Implement incremental (or differential) backups on the Volume Snapshot Data Mover

### ISSUE THREAD

**Issue by ddomingu** [vmware-tanzu/velero#6526]
**Describe the problem/challenge you have**

I've been having a look at the Volume Snapshot Data Movement Design (https://github.com/vmware-tanzu/velero/blob/main/design/volume-snapshot-data-movement/volume-snapshot-data-movement.md) and I'd like to suggest to ensure incremental or differential backups will be available when implementing the Snapshot Data Mover.

**Describe the solution you'd like**

I'd like to be able to work with incremental or differential backups when working with the Snapshot Data Mover as it is much more efficient than doing full backups every time. When working with incremental or differential backup as you don't need to copy as much data as with full backups the solution is more efficient. You also require less storage space and shorter backup windows.

**Anything else you would like to add:**

If we are currently working on providing incremental or differential backups in the Snapshot Data Mover or this is a duplicate request, sorry for creating a new one and feel free to close it.

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by Lyndon-Li** [comment]
@ddomingu 
If you are talking about file system level incremental & differential backups, here are the details that are already available in v1.12 release:

- Incremental backup: The file system level incremental backup is supported, Kopia uploader has the ability to compare a file's file system attributes by multiple criteria and tell whether the file has been changed since the previous backup, if not, the uploader will skip backing it up. Moreover, Kopia repository's deduplication feature will further reduce the data redundancy in the case that a file is only slightly changed.
- Differential backup: This is not currently supported, this is feasible technically. However, since Velero doesn't support sophisticated retention policies yet, there is no way to implement it from end to end at present. 
- Or in another words, as the current situation, only the 1st backup is full and the followings are all incremental.

Going forwards, various kinds of incremental backup and retention policy are prioritized items in Velero's radar, merely, the functionalities won't go into one single release, they may be delivered gradually according to the plans.
