### ISSUE TITLE
CSI plugin should not be called when CSI feature is not enabled

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#6585]
**Describe the problem/challenge you have**

When the CSI plugin is installed with Velero deployment and the CSI feature is not enabled, the CSI plugin actions are also called.

**Describe the solution you'd like**

Need to check whether the CSI feature is enabled, before calling the CSI plugin actions.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
We should probably favor #6694 and remove EnableCSI feature flag.

**Comment by sseago** [comment]
@draghuram Hmm. I'm not sure about including the plugin by default. Currently installer provides `--plugins` to allow user-desired plugins to be specified. None are included by default because different users have different needs -- i.e. in an azure-only env, no need for gcp object store plugin; if I'm not using CSI storageclasses, I don't need that plugin, etc. And if I am using csi, I might need a different version from any installer-built-in notion of what CSI image to use (i.e. newer patch release, or custom image/tag). If we had a list of plugins/images to install by default, we'd need to parse the user-supplied list of plugins to ensure that we weren't installing two different versions of a default plugin. I think it's easy enough to document (as we should already) that users wanting to use csi plugin -- or datamover -- should include the CSI plugin in the list.

**Comment by sseago** [comment]
Also, if users want to use volume snapshotter plugins for their CSI volumes that support it (i.e. gp2-csi storageclass for aws), they'd need to *not* have the CSI plugin installed, since that causes velero to use CSI and not volume snapshotters.

**Comment by draghuram** [comment]
@sseago, thanks for the detailed explanation. You certainly raise some good points. But considering that CSI is the future of storage in Kubernetes, it would be best to make CSI functionality available by default. I am not saying that backups should automatically take CSI snapshots. That decision should be left to the user while defining backup. But I am fine with clearly documenting the need to install CSI plugin for now.

**Comment by reasonerjt** [comment]
Given we are not likely to remove the feature flag, I'm putting this one into v1.13 milestone.
