### ISSUE TITLE
PVC not getting backed up where storage class name does not exist in PVC but PV has storage class mentioned 

### ISSUE THREAD

**Issue by mayankagg9722** [vmware-tanzu/velero#6596]
**What steps did you take and what happened:**
We have identified that the PVC backups are not happening in cases where storage class name does not exist in PVC yaml but PV YAML has storage class mentioned. This is the scenario of **static persistent volume provisioning** where storage class name is not being provided under the PVC yaml.

**Code**: https://github.com/vmware-tanzu/velero-plugin-for-csi/blob/release-0.5/internal/backup/pvc_action.go#L98C2-L100C3

**What did you expect to happen:**
Instead od fetching the storage class name from PVC, we should fetch it from the PV yaml and should proceed with backups.

**The following information will help us better understand what's going on**:

**Anything else you would like to add:**
Storage Class, PVC and PV Yamls:
![image](https://github.com/vmware-tanzu/velero/assets/17884128/78523b3c-b57f-40ae-95f9-70bdd719ae19)

**Environment:**

- Velero version (use `velero version`): v1.11.0
- velero-plugin-for-csi: v0.5.1
- Kubernetes version (use `kubectl version`): AKS 1.25.6
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.6 LTS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
I'm wondering why PVC doesn't contain the storage class name?

**Comment by mayankagg9722** [comment]
> I'm wondering why PVC doesn't contain the storage class name?

Hi, This is the scenario of static persistent volume provisioning where storage class name is not being provided under the PVC yaml.

**Comment by sseago** [comment]
@mayankagg9722 Normally if there's a default storageclass, a PVC without storageclass gets the default added to the PVC directly. However, it looks like your PVC is using the deprecated beta annotations for storageclass rather than Spec.StorageClassName. That may be why this isn't working with velero. At one point in the past, I had submitted a bug to Velero that things didn't work correctly when using the beta annotations instead of the spec field. However, the maintainers at the time had decided that since this option has been deprecated since Kubernetes 1.9, they didn't want to add special code to deal with it. You might try using storageclassname instead of the annotation and try again.

**Comment by sseago** [comment]
https://github.com/vmware-tanzu/velero/issues/1797
From (then-maintainer) Steve Kriss:
"@sseago thanks for reporting this. I'm personally comfortable saying that we don't support the beta storage class annotation here, given that (a) it's been deprecated since v1.8 and (b) there's an upgrade path for users to switch to using the storageClassName field. Not sure it's worth the time to spend changing/testing here."

**Comment by mayankagg9722** [comment]
Thanks a lot @sseago for helping and pointing out the fix for this issue.

**Comment by ywk253100** [comment]
Closing this issue according to the comment.
@mayankagg9722 Feel free to reopen it if you have any further questions
