### ISSUE TITLE
Per {VolumeSnapshot,Storage}class data movers

### ISSUE THREAD

**Issue by shawn-hurley** [vmware-tanzu/velero#6638]
**Describe the problem/challenge you have**

While developing a data mover for say aws-ebs, I would have to re-implement the CSI plugin, and have users replace the CSI plugin with my own aws-ebs/CSI plugin. This will make it nearly impossible for two data movers to live in the same cluster even though the `DataUpload` and `DataDownload` have the ability to have more than one data mover looking for these resources. 

**Describe the solution you'd like**

Initially, I would propose an API that an administrator can set that would map storage classes or snapshot classes to a given data mover. 

Another option is to set this in CLI flags or options to the CSI plugin.

**Anything else you would like to add:**

This is an enhancement for the data mover design to enable the CSI plugin to map these things when it decides to create the `DataUpload` and `DataDownload` CRs.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by shawn-hurley** [comment]
Another option is for the plugins to registry in some way which classes they could support, and then the CSI plugin becomes the fallback/default.

**Comment by sseago** [comment]
I wonder whether the resource filters API could be extended here with a new action to specify a specific datamover for matching volumes, since the ability to match by storageclass, driver, etc. is already here.
https://github.com/vmware-tanzu/velero/blob/main/design/Implemented/handle-backup-of-volumes-by-resources-filters.md

**Comment by draghuram** [comment]
I am curious about the use case. Considering that native data mover works with all CSI plug-ins, what would be the reason for developing a new data mover? Even assuming that there is a case to develop new data mover, why would CSI plug-in need to be re-implemented? 

I am sure I am missing something here.

**Comment by blackpiglet** [comment]
The Velero built-in data mover is a filesystem uploader. Basically, it can work in most cases.
In some scenarios, they may provide a more efficient way to read and upload data from snapshots.
Maybe this is the scenario this issue is trying to address.
https://github.com/vmware-tanzu/velero/blob/main/design/volume-snapshot-data-movement/volume-snapshot-data-movement.md#plugin-data-movers

The Snapshot Data Mover design does consider third-party data movers. May need to implement the exposer and data mover to create a new third-party data mover.

**Comment by Lyndon-Li** [comment]
I am also curious when a customized data mover plugin, or CMP for short, is required (as an replacement of CSI plugin).
As the [designed doc statement](https://github.com/vmware-tanzu/velero/blob/main/design/volume-snapshot-data-movement/volume-snapshot-data-movement.md#:~:text=Theoretically%2C%20replacing%20the%20DMP%20is%20also%20allowed.%20In%20this%20way%2C%20the%20entire%20workflow%20is%20customized%2C%20so%20this%20is%20out%20of%20the%20scope%20of%20this%20design.) , we added this statement for two considerations:
1. A customized CMP is supported, but once a customized CMP is there, a customized data mover counterpart must also be provided
2. A customized CMP is not required in most cases, if the built-in CSI plugin is not generic enough, we should consider to enhance the built-in CSI plugin instead of replacing the entire CSI plugin

Please share any more details behind this.

**Comment by shawn-hurley** [comment]
The most significant use case is developing specific data movers for specific storage systems. For instance, with AWS snapshots, I may want to move the data to, say, a new region. When I want to do this, I can interact with the AWS APIs and will save a ton of money for ingress/egress. Another option, is to enable CBT for a specific data mover. If a storage system exposes the necessary information (say AWS API's for EBS) then I can choose to make that faster/better/more efficient for specific cases. 

Does this make sense?

**Comment by shawn-hurley** [comment]
As for the replacement problem here is the use case:

1. I have EBS volumes and I have local file system volumes
2. For EBS I want to use new data mover X
3. For local file system I want to you use the default data mover.,

Today, AFAICT, CSI when set to data mover, sets the DataDownload or the DataUpload based on a single value. The value in the backup or the default value. There is no way, to use two data movers in a single backup. IF someone really wanted to do this they would HAVE to handle this fallback in their own plugin and turn off CSI plugin. To turn off the CSI plugin, you would then have to re-implement what it does. 

Does that also make sense?

**Comment by sseago** [comment]
@shawn-hurley they could also use label selectors and create multiple backups, but that would also be a clumsy workaround.

 If we use the resource filters feature (adding a new action -- something like setDataMover), we could override the datamover on a per-volume basis using various volume characteristics (provisioner, vol mode, etc.). The selection mechanism is already there, we'd just need to implement the action bit -- similar to what we're proposing to allow volume characteristics to determine whether to use fs backup vs. snapshots.

**Comment by shawn-hurley** [comment]
I agree, @sseago. That is a really good API design to solve this problem.

If we do it this way, would a Data Mover have to create a plugin and a data mover controller?

**Comment by sseago** [comment]
So from a Data Mover implementation point of view, I don't think this new selection process changes much. Basically instead of "find the named datamover for this volume by looking at backup, then default", we've got "find the named datamover for tihs volume by looking at resource filters for backup, then backup datamover spec field, then default". This implementation is part of the datamover selection process rather than in the datamover API itself.

With this approach, the user creating the backup decides how to map volumes to movers. If we wanted the data mover to decide what it matches (rather than using the resource filters), that would require a plugin implementation of some sort with an AppliesTo method taking the backup and volume as input, but then you also have to deal with questions of priority, etc. since multiple datamovers may exist that are able to back up various volumes -- the user-selection approach is probably simpler to implement then. It's unclear which is more user-friendly. Either way, the user either has to generate the selection rules, or the user has to tell Velero the datamover priority order.

**Comment by shawn-hurley** [comment]
@sseago @shubham-pampattiwar We want to fold this into the policies discussion. Do we want to close this, add it to that issue and work on a design together?

**Comment by shawn-hurley** [comment]
Hello,

Had a quick chat with @shubham-pampattiwar, and we did a quick exercise on what it would take design-wise, for the API to be used for this. The quick of it is that:

1. The main velero process is what use's the API, while today, the CSI plugin sets the data mover. If we wanted to change this, we would have to make the main velero process aware of data movement.
2. move some logic out of the CSI plugin. 
3. This would get even more confusing because all data movement has to happen from a snapshot. 

Because of these reasons, we believe that this is not a candidate to be added to the API mentioned above. Instead a new desgin to enhance the CSI plugin to have configuration to do this work will be created and published.


Please let me know if anyone has questions with the thought process

**Comment by sseago** [comment]
@shawn-hurley That makes sense to me. Although even if we did decide to go back and use the volume policies, this would be a completely different action from the one proposed to allow snapshot vs. fs backup based on volume characteristics, so it would still be a mostly-unrelated discussion to the other policy action addition. In any case, we're not going that direction, so this will be considered (and designed) independently of that other feature.

**Comment by shawn-hurley** [comment]
@shubham-pampattiwar @sseago @weshayutin 

Do we agree on

> Because of these reasons, we believe that this is not a candidate to be added to the API mentioned above. Instead, a new design to enhance the CSI plugin to have the configuration to do this work will be created and published.

if so, I believe that this can be closed if we are tracking that work. If this is tracking that work, then someone else needs to drive it.
