### ISSUE TITLE
Extend VolumePolicies feature to support more actions other than just `skip` action

### ISSUE THREAD

**Issue by shubham-pampattiwar** [vmware-tanzu/velero#6640]
**Describe the problem/challenge you have**
Currently, the VolumePolicies feature which can be used to filter/handle volumes during backup only supports the `skip` action on matching conditions. Users need more actions to be supported. eg: opt in for `fs-backup`  action for some volumes and `snapshot` action for some particular type of volumes in the same backup operation can be facilitated via VolumePolicies feature if these actions are supported.

**Describe the solution you'd like**

Add support for more actions like `fs-backup` , `snapshot` etc

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by sseago** [comment]
Here's a concrete use case for this feature. A user wants to use datamover for all supported volumes and fs backup for the rest, without having to annotate the pods explicitly for which volumes to include (or exclude) from fs backup. 

To support this, the new `fs-backup` policy would be equivalent to listing all matching volumes in the "backup.velero.io/backup-volumes" annotation on the mounting pod, and the new `snapshot` policy would be equivalent to listing all matching volumes in the "backup.velero.io/backup-volumes-excludes" annotation on the mounted pod.

Then a user who wants to use VBDM for everything they can and fs backup for the rest would set `--snapshot-move-data` and `--default-volumes-to-fs-backup` on their backup, and then specify a policy of `snapshot` for CSI volumes.

**Comment by blackpiglet** [comment]
Agree this is a reasonable scenario. 

```
1. the new fs-backup policy would be equivalent to listing all matching volumes in the "backup.velero.io/backup-volumes" annotation on the mounting pod.
2. And the new snapshot policy would be equivalent to listing all matching volumes in the "backup.velero.io/backup-volumes-excludes" annotation on the mounted pod.
```

This should be achieved without manually adding the annotations on the pods, am I understanding it right?
Are there any thoughts about how to implement the filtering?

**Comment by ddl-kfrench** [comment]
also worth noting that the documentation currently (mistakenly) indicates support for more than just 'skip':

https://github.com/vmware-tanzu/velero/blob/bdbe7eb242b0f64d5b04a7fea86d1edbb3a3587c/design/Implemented/handle-backup-of-volumes-by-resources-filters.md?plain=1#L53

though if you try to use either `file-system-backup` or `volume-snapshot` action types the backup will fail:

```
Validation errors:  resource policies xxx/velero-resource-policy: invalid action type file-system-backup
```

`skip` is indeed the only action defined (as of 1.11.1):

https://github.com/vmware-tanzu/velero/blob/bdbe7eb242b0f64d5b04a7fea86d1edbb3a3587c/internal/resourcepolicies/resource_policies.go#L16

**Comment by sseago** [comment]
@blackpiglet "This should be achieved without manually adding the annotations on the pods, am I understanding it right?"
I would hope so, yes. I haven't looked at the code that reads those annotations in a while, but I imagine that in the same place we currently read those annotations we could also pull in the policy data here. Not sure whether we'd want to parse at that point, or when we process the policy for skipping volumes, we also generate a list of volumes for these new policies which could be used at Pod backup time to determine whether or not to create a PodVolumeBackup, etc.

When I said "equivalent to adding the annotations" I meant the same effect on the backup (i.e. when to use fs backup vs. snapshot), not the same effect on the annotation list.

**Comment by qiuming-best** [comment]
@sseago The related filter for the `skip` action currently applied for every PV or PVC is the last rule after our 'include-xxx' or `exclude-xxx` filters the remaining eligible objects. which is easy to be implemented without considering the conflict with current complexity filters.

For the extend `VolumePolicies`, it's more complicated than `skip`, we may need to consider:
- The priority of current filters with `VolumePolicies` in case of confliction
- How to classify which volume belongs to which Policy or one specific volume should apply which Policy(fs-backup, CSI, Snapshot DataMover, etc)

**Comment by sseago** [comment]
@qiuming-best I guess part of the design work will be to determine whether we need to determine priority, or whether that's a non-goal and it's fine for multiple filters to match (with rules determine for what that means).

For example, with this proposal we only have 2 new rules: fs-backup and snapshot, along with the existing skip. So the simpler approach would be to declare priority rules out-of-scope. Currently, all 3 of these rules duplicate actions that also exist elsewhere  (i.e. matching a skip rule is equivalent to a volume excluded by other means, matching fs-backup is equivalent to the fs backup annotation, snapshot is equivalent to the fs-backup exclude annotation). It's entirely possible for all 3 of these to be set independently for a volume -- but if a volume is excluded, the annotations won't matter since it won't be backed up. Likewise for snapshot/fs-backup annotations, only one is meaningful for a given backup, depending on whether we're using opt-in or opt-out. So these new fs-backup and snapshot rules only have an effect in those specific fs backup opt-in or opt-out scenarios. I think we can probably hold off on developing priority rules util we have a defined action that actually needs them set.

**Comment by sseago** [comment]
So to take the above example use case and extend it to see what should happen with skip rules, we can see that we probably don't need to worry about priority rules at least with these defined actions. "I want to use datamover for all volumes that support it, fs backup for the rest, and don't back up volumes larger than 100Gi"
To do this, the user would set defaultVolumesToFsBackup=true, snapshotMoveData=true, then define a volume policy with the "snapshot" action for all volumes with CSI, and define another volume policy with the "skip" action for all volumes larger than 100Gi.

All large volumes will be excluded, so since they're excluded, the snapshot vs. fs backup decision is irrelevant. Of the non-skipped volumes, CSI volumes will use VBDM, the rest fs backup.

**Comment by Lyndon-Li** [comment]
FYI, as the discussion, an issue #6658 is opened for verification of the usage that data mover and fs-backup are included in one backup/restore.

**Comment by reasonerjt** [comment]
I think this is valuable enhancement, and it's intuitive to introduce it in the volume-policy configmap, but:

- Currently velero has a number of ways to switch between volumesnapshot and podvolume via CR, annotations,etc. in the design we should clearly define the priority if the setting in the volume-policy conflicts with the settings in other places.
- This may require heavy rework in backup workflow, is it possible we deliver it partially if we can't make the e2e flow work reliably in v1.13 timeframe?

**Comment by shawn-hurley** [comment]
I could not agree more that this is something that needed!

**Comment by shubham-pampattiwar** [comment]
This issue is not stale, the design PR is up for this: https://github.com/vmware-tanzu/velero/pull/6956
