### ISSUE TITLE
PodVolumeBackup is a multiple of velero deployment replicas

### ISSUE THREAD

**Issue by poneding** [vmware-tanzu/velero#6888]
I scale the deployment replicas to 3, and then create backup, found 3 PodVolumeBackup created.
This should not happen and the number of PodVolumeBackup created should be limited by the controller

**Comment by blackpiglet** [comment]
Thanks for reporting this issue, but this looks like a behavior by design to me.
PodVolumeBackup is created according to the pod. By far, there is no way to remove duplicated volumes.

May I ask why scale a deployment with more than one replica, and all replicas mount the same volume? 
Is it a PVC that can be mounted multiple times, or it's an ephemeral volume, such as emptyDir?

**Comment by poneding** [comment]
This is because I once found that the deletion of Backup was stuck, and the other Backup was not able to perform the normal backup work quickly. I wondered if the efficiency of a single controller was too slow, so I scaled the replicas and the problem was solved amicably.

**Comment by blackpiglet** [comment]
I misunderstood your scenario. 
You scaled the Velero deployment to replica 3, right?
By far, the Velero server doesn't parallel yet.
Both handling multiple backups at the same time and splitting one backup's work into several minions ways are not supported by now.
Multiple instances of Velero couldn't work together. It doesn't have a mechanism to select the leader. They may all start to process the backup request at the same time.

**Comment by poneding** [comment]
我印象已经不是很深了，我当时使用的版本是 v1.11.x，我记得当时我删除 Restore 这个资源，但是一直无法删掉。这是新建 Backup 也会一直处于 Progress 的状态。我感觉是不是由于什么原因，当前控制器卡住了。所以我伸缩了副本数，神奇的事，新建的 Backup 立马就完成了，并且我继续新建 Backup 也能很快完成。
我现在已经无法复现了，但是我仍然会习惯的将控制器副本扩上来。。。🤣

**Comment by blackpiglet** [comment]
Hard to explain how that worked. Scaling the Velero deployment is not encouraged.
