### ISSUE TITLE
PVCs used to mount static PVs are skipped because they don't have a storageClass defined

### ISSUE THREAD

**Issue by kxs-jnadeau** [vmware-tanzu/velero#7139]
**What steps did you take and what happened:**
Create a backup that include namespaces with PVCs used to mount static PV (we use the SMB CSI driver to mount existing CIFS volumes)

They are skipped because there is no storage class defined in the PVC as described in the error.

`
name: /pvc-smb-name error: /error executing custom action (groupResource=persistentvolumeclaims, namespace=qa001, name=pvc-smb-name): rpc error: code = Unknown desc = error getting storage class: resource name may not be empty
`

This also marks the backup as PartiallyFailed with an error for every PVC of this type being skipped. 

**What did you expect to happen:**

PVC resources with no storage class should still be included in the backup,  as they are a valuable asset to restore even if static PVs are used.   

**Environment:**

Velero v1.12.1 on GKE 1.24 using CSI driver for dynamic PV snapshoting.
Storing manifests in GCS.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by anshulahuja98** [comment]
Please refer to discussion here. 
https://github.com/vmware-tanzu/velero/issues/6596

Suggestion would be to add a storage class to the PVC. PVCs for static PVs can still have StorageClass specified even if not used.

**Comment by kxs-jnadeau** [comment]
Understood, and I agree the storageClass  should be defined regardless.  But sadly the spec allows it.  I was looking for an alternative which do not involve user changes and redeployment.

**Comment by reasonerjt** [comment]
Please refer to https://github.com/vmware-tanzu/velero/issues/6596#issuecomment-1664038979

For storage clasee annotation in PVC there was decision made years ago that velero would not support it.

**Comment by sseago** [comment]
Beta annotation is not used anymore, however, one use  case for no storageclass is NFS volumes. NFS volumes will generally not have a storageclass defined (unless you happen to be using a dynamic NFS provisioner). @anshulahuja98 For the static NFS use case, adding a storageclass to the PVC would be wrong, because the PVs are pre-created without using a dynamic provisioner. Of course, you can't snapshot non-storageclass NFS volumes, so fs backup is your only option.

@kxs-jnadeau are you using fs backup with your statically-provisioned volumes? If so, this should work. But snapshotting will not work for this sort of volume.
