### ISSUE TITLE
filter the additionalItem before getting it from backup tarball

### ISSUE THREAD

**Issue by 27149chen** [vmware-tanzu/velero#7181]
**What steps did you take and what happened:**

When an additionalItem returns from a RestoreItemAction, velero will first try to get its content from backup tarball, and then do the following (filter, process, ...)
But if this item is excluded in backup, a warning "unable to restore additional item" will be recorded

for example:
a backup includes pvcs but excludes pvs, when restoring it, the pvc plugin will put pv in additionalItems

**What did you expect to happen:**

do not report the "unable to restore additional item" warning if an additionalItem is excluded in backup

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

we can filter the additionalItem before getting it from backup tarball, including the backup filter and the restore filter

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by sseago** [comment]
Actually, the case you mentioned (can't restore additional item because it's excluded from backup) is one of the primary cases where this warning is useful. A plugin indicates "this other item must be in the cluster before the current item is restored", so if that's been excluded from the backup, we should warn the user about it, as it could result in things not working properly post-restore. The user might see the missing PV warning and realize that they needed to *not* exclude them from backup, or in other cases they might conclude that the missing item is harmless and doesn't warrant additional actions.

But hiding the warning from the user is potentially harmful, as it might prevent the user from realizing that the backup was missing something essential. Lets keep the warning, since 1) it doesn't fail the backup (it's a warning, not an error), and 2) it provides potentially valuable information that some users may need to act on.

**Comment by 27149chen** [comment]
But I think if a user already excluded pvs in backup, but still see the warning "unable to restore pvs" in restore, it is too confusing

**Comment by reasonerjt** [comment]
I tend to agree with @sseago
