### ISSUE TITLE
Got backup PartiallyFailed result when backing up PVCs which are not used by any pod

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero#7233]
**Describe the problem/challenge you have**

Backup namespace contains PVCs which not in used by any pod, then got PartiallyFailed result.
```
k get pvc -n azure-csi-test
NAME               STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
nginx-logs-e2e-1   Bound     pvc-e4dda753-8c88-4194-93b5-959a01be1de4   1Gi        RWO            managed-csi    16h
nginx-logs-e2e-2   Pending                                                                        managed-csi    16h
nginx-logs-e2e-3   Pending                                                                        managed-csi    16h
nginx-logs-e2e-4   Pending                                                                        managed-csi    16h
nginx-logs-e2e-5   Pending                                                                        managed-csi    16h

velero describe backup backup-csi-6 --details
Name:         backup-csi-6
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/resource-timeout=10m0s
              velero.io/source-cluster-k8s-gitversion=v1.28.0
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=28

Phase:  PartiallyFailed (run `velero backup logs backup-csi-6` for more information)


Errors:
  Velero:    name: /nginx-logs-e2e-2 message: /Error backing up item error: /error executing custom action (groupResource=persistentvolumeclaims, namespace=azure-csi-test, name=nginx-logs-e2e-2): rpc error: code = Unknown desc = PVC azure-csi-test/nginx-logs-e2e-2 has no volume backing this claim
             name: /nginx-logs-e2e-3 message: /Error backing up item error: /error executing custom action (groupResource=persistentvolumeclaims, namespace=azure-csi-test, name=nginx-logs-e2e-3): rpc error: code = Unknown desc = PVC azure-csi-test/nginx-logs-e2e-3 has no volume backing this claim
             name: /nginx-logs-e2e-4 message: /Error backing up item error: /error executing custom action (groupResource=persistentvolumeclaims, namespace=azure-csi-test, name=nginx-logs-e2e-4): rpc error: code = Unknown desc = PVC azure-csi-test/nginx-logs-e2e-4 has no volume backing this claim
             name: /nginx-logs-e2e-5 message: /Error backing up item error: /error executing custom action (groupResource=persistentvolumeclaims, namespace=azure-csi-test, name=nginx-logs-e2e-5): rpc error: code = Unknown desc = PVC azure-csi-test/nginx-logs-e2e-5 has no volume backing this claim
```

**Describe the solution you'd like**
Warning should be enough to let user notice this workload might have issue or not.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by blackpiglet** [comment]
I agree we should do better in this scenario.
There are some similar cases to this. Let's settle on a unified solution to all of them.
IMO, we should consider the k8s resources as crucial for the Velero, such as Pod, PV, and PVC.

**Comment by hsinhoyeh** [comment]
hi team, thanks for creating this backup/restore tooling. Unfortunately, we encountered this issue when our serverless applications relied on an RWX mode PVC. We choose to do a backup at midnight, where the traffic is low and it also keeps the running pod minimized to zero. But, the backup didn't cover our PVCs for serverless :(

**Comment by blackpiglet** [comment]
@hsinhoyeh 
Could you give more information about your scenario?
Do you know if you use the Filesystem or volume snapshot backup?
Is the PVC mounted by multiple pods when the backup is in progress?

**Comment by hsinhoyeh** [comment]
> @hsinhoyeh Could you give more information about your scenario? Do you know if you use the Filesystem or volume snapshot backup? Is the PVC mounted by multiple pods when the backup is in progress?

Hi @blackpiglet we use file system for backup. the PVC is supposed to be mounted by multiple pods (with mode: RWM). having say that, our multiple pods are mostly read from the PVC (during backup), not writing it.

**Comment by blackpiglet** [comment]
@hsinhoyeh 
Thanks for the feedback.
Could you share the backup command or the backup CR YAML?

**Comment by blackpiglet** [comment]
If there is no pod mounting the PVC when a backup is ongoing, the file-system backup cannot cover the PVC, because the file-system uploader needs to read the PVC's volume data by the mounting directory for the pod on the k8s node. 
Please read the PodVolumeBackup description to understand how it works: https://velero.io/docs/v1.13/file-system-backup/#custom-resource-and-controllers.

For your scenario, if the PVC's volume supports the snapshot function, then we can use snapshot to back up the data.

**Comment by reasonerjt** [comment]
This is working as expected I don't think we wanna change the error into a warning, which will be a breakchange.

**Comment by stp-bsh** [comment]
Is there any way to exclude PVCs with unbound PVs? As long as this is not the case I would see this as as a Warning and not as Error.

**Comment by Varjoissa** [comment]
Yes, even though this issue is closed, I think it should be re-opened.
PVC's can still be in Pending state for several reasons. And if so, it should either warn or skip snapshotting the data, since there is no PV. 
It sounds out-of-scope for Velero to judge whether a PVC should be provisioned. If it is not provisioned with a PV there is just simply no PV to backup/snapshot.

Is there no possibility to add a pre-backup hook or add a `status` filter to the resource-policy configmap?

**Comment by kaovilai** [comment]
> Is there no possibility to add a pre-backup hook or add a status filter to the resource-policy configmap?

Can you clarify what is needed here?

**Comment by kaovilai** [comment]
> Is there any way to exclude PVCs with unbound PVs? As long as this is not the case I would see this as as a Warning and not as Error.

@stp-bsh That could be a separate new issue if you want to open. Unbound =/= not used by any pod (ie. this issue.)

**Comment by stp-bsh** [comment]
@kaovilai Happy to open a new issue, but I don't understand why. The new issue would be a duplictae ot that one as the underlying problem is 1:1 the same. Frankly speaking, personally I would kindly ask to re-open this one and to work within this context.

**Comment by kaovilai** [comment]
After reviewing the discussion and considering the different use cases, I think there's room for a nuanced approach that addresses both scenarios without introducing breaking changes:

**For PVCs with no backing volume (Pending state):**
- If a PVC is known to never be bound (e.g., due to storage class issues, quota limits, etc.), it should ideally be excluded from backup entirely
- If a PVC will eventually be bound but the backup happens to start before binding occurs, an error or warning would be appropriate

**Proposed Solution:**
Per @reasonerjt's concern about avoiding breaking changes, we could introduce **optional configurability** as a feature rather than changing the default behavior. This could include:

1. A feature flag like `--warn-unbound-pvcs` that changes errors to warnings for unbound PVCs
2. Enhanced resource policy support to allow filtering PVCs by status (e.g., `spec.phase != "Pending"`)
3. Better documentation on backup timing strategies for dynamic environments

This approach would:
- ✅ Maintain backward compatibility (no breaking changes)
- ✅ Address real-world scenarios like @hsinhoyeh's serverless applications  
- ✅ Give users control over the behavior based on their specific needs
- ✅ Provide a path forward for environments where unbound PVCs are expected

**Next Steps:**
As @reasonerjt suggested, introducing **more configurability** as a feature could be discussed in a separate issue. This would allow us to:
1. Design the configuration API carefully
2. Consider integration with existing resource policies
3. Maintain the current strict behavior as default while offering flexibility

**Comment by kaovilai** [comment]
The requests to ignore unbound status can fit under https://velero.io/docs/main/resource-filtering/#supported-volumepolicy-actions

**Comment by kaovilai** [comment]
ok I'll retitle and reopen this issue :D

**Comment by weshayutin** [comment]
@kaovilai @shubham-pampattiwar when we fix this, please consider a backport to velero 1.16.x

**Comment by Lyndon-Li** [comment]
@kaovilai Sorry I missed the question in the meeting, do we need this fix to be in 1.17.1? Looks like it is an enhancement. Or do you see customers from your side reporting this problem? cc @reasonerjt

**Comment by kaovilai** [comment]
Yes there is a customer issue on it. https://issues.redhat.com/browse/OADP-6428

And @weshayutin [want this backported to 1.16](https://github.com/vmware-tanzu/velero/issues/7233#issuecomment-3079685438)

**Comment by kaovilai** [comment]
Doesn't have to be 1.17.1, could be later. But we will try to get it into 1.16.x

**Comment by Lyndon-Li** [comment]
> Doesn't have to be 1.17.1, could be later. But we will try to get it into 1.16.x

Why don't make it in 1.17.1 if this is important to your side? We still have window for 1.17.1, and we don't know the plan for 1.17.2 yet. And I see you also added 1.17.1 tag.
And there is no plan for 1.16.3 either.

**Comment by kaovilai** [comment]
> And there is no plan for 1.16.3 either.

That's ok we can cherry pick downstream if needed, but we would prefer in `release-1.16` branch if that's ok even without a release.

1.17 is not used in our downstream. I am however happy to add cherrypick from main to 1.17. Whether that fit within 1.17.1 or later. Just saying we're flexible w 1.17 release.

Our next version targets 1.18.

**Comment by Lyndon-Li** [comment]
@kaovilai 

Thanks for the clarification!
We discussed this issue and here are the suggestion:
1. Please cherry-pick the PR to release-1.16 after it is merged to main, so that you can align it from your downstream branch
2. Please also cherry-pick to release-1.17 by the same time. We will see, if it could catch the window for 1.17.1, we bring it in; otherwise, we leave it in 1.17 branch and wait for the next patch, e.g., 1.17.2

cc @reasonerjt
