### ISSUE TITLE
Restore is stuck when enabling the informer cache

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#7263]
When the informer cache is enabled, the restore is stuck if the restore includes `namespace` resource.
Get the following errors in the Velero server logs:
```
W0102 09:48:14.941204       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.6/tools/cache/reflector.go:169: failed to list *unstructured.Unstructured: the server could not find the requested resource
E0102 09:48:14.941248       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.6/tools/cache/reflector.go:169: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: the server could not find the requested resource
```

The cause of the error `the server could not find the requested resource` for `namespace` is that Velero calls list API of `namespace` with namespace added incorrectly

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
The root cause is that in PR #7143 the resource namespace was transformed into restoreableItems and it has the field `targetNamespace` set as the name of the restored namespace, and when the informer cache was added it uses the `targetNamespace` to list the resources.

Adding `targetNamespace` to namespace resoruces may be a bad decision, I'll fix it.
