### ISSUE TITLE
Make kopia repo cache policy configurable

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#7620]
Related to issue #7499. 
The cache policy decides the root file system disk usage in the pod where data movement is running, and on the other hand, it also impact the restore performance significantly.
Therefore, besides the hard-code policy, we should expose some of them to users so that users could decide the cache disk usage.

**Comment by Lyndon-Li** [comment]
@u3813 

> But in my case, it seems that too much data is being restored within these 10 minutes

As the current cache management policy, we only control the living time of the cache data, we don't check the size of the cache in a period of time. Then how much data is cached relies on the total size to be restored, the parallelism of the restore. The larger of the restore size, the more parallelism (by default decided by the CPU cores in the node), the more data will be cached.
Therefore, the final solution is to control the cache by checking the total size, if it exceeds a defined size, delete the oldest data.

> I would rather have more options when it comes to configuring the cache. It should be possible to either set a lower value than 10 minutes or to set a hard GB limit after which the cache is cleared

This will be done in the fix of this issue.
And another issue #7725 gives another option for users to configure a dedicate cache volume then the restore performance will not be compromised.

**Comment by janpipan** [comment]
We also had a problem with disk pressure, which we resolved by adding additional disk capacity, but I think this is not something desirable as the ephemeral storage consumption is basically the same size as the PV being restored. 

> @lyndon-li

> As the current cache management policy, we only control the living time of the cache data, we don't check the size of the cache in a period of time. 

Was this sufficiently tested, as I believe there is also a bug with a cache cleanup, because in our case it didn't execute as expected.

When we restored the PV with around 50 GB for the first time the cache got cleaned up after around 10 mins, but after the second restore the cleanup did not happen automatically. I left the node-agent Pod running for over a day, but the storage consumption on the worker node did not drop as expected, which is why I deleted the Pod manually today which resolved the issue.

**Comment by reasonerjt** [comment]
Combining #7301 we should probably design a consistent way to let user configure the advanced settings for kopia.

But before that, we should consider adjust the default policy to mitigate the risk for restore failure.

**Comment by Lyndon-Li** [comment]
@mpryc Could you comment on #7301 for why compression is important to your case?

**Comment by mpryc** [comment]
@Lyndon-Li For me compression is not important, but the design should cover generic advanced settings for kopia as pointed in the https://github.com/vmware-tanzu/velero/issues/7620#issuecomment-2167502875 comment. That is why I've mentioned it.

**Comment by Lyndon-Li** [comment]
@mpryc Design PR is submitted, feel free to add comments on it.

**Comment by Lyndon-Li** [comment]
> With no mention of AccessModes, I imagine one of the requirements will be for ethe StorageClass to support ReadWriteOnce? Though I don't know of any StorageClass with ReadWriteMany support that doesn't also support ReadWriteOnce.

Added the spec of cache PVC into the design.
