### ISSUE TITLE
velero backup has an warning 'No volume ID returned by volume snapshotter for persistent volume'

### ISSUE THREAD

**Issue by bhavyashree231** [vmware-tanzu/velero#8002]
**What steps did you take and what happened:**
velero backup was taken with respect to the specific namespace which in turn had few of the pod volumes excluded using annotations.
backup was completed successfully with the warnings as below

![image](https://github.com/vmware-tanzu/velero/assets/175309230/398f4ee1-dea6-4dce-ba01-123ff4f9d104)

**What did you expect to happen:**
successful backup without warning & errors since they are already excluded.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 1.14.0 
- Velero features (use `velero client config get features`): NA
- Kubernetes version (use `kubectl version`): 1.28 & 1.30
- Kubernetes installer & version: GKE
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`): NA

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
It is the expected behavior that the native snapshotter takes over the volume backup if no other method is selected, and if the native snapshotter cannot handle the volume, it gives a warning.

For whether it is expected for the native snapshotter to handle the volume, you need to check you backup options which selects the backup method, i.e., fs-backup, CSI snapshot, CSI snapshot data movement, etc.

**Comment by Lyndon-Li** [comment]
It is the expected behavior that the native snapshotter takes over the volume backup if no other method is selected, and if the native snapshotter cannot handle the volume, it gives a warning.

For whether it is expected for the native snapshotter to handle the volume, you need to check you backup options which selects the backup method, i.e., fs-backup, CSI snapshot, CSI snapshot data movement, etc.

**Comment by kaovilai** [comment]
> pod volumes excluded using annotations.

The annotations you used are only processed for file-system-backup currently.

Like Lyndon said, if your environment allows for native snapshotter to take over (perhaps you have created a [VolumeSnapshotLocation](https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/main/volumesnapshotlocation.md))

>> It is possible to exclude volumes from being backed up using the backup.velero.io/backup-volumes-excludes annotation on the pod.

is only mentioned in [File System Backup documentations](https://velero.io/docs/v1.14/file-system-backup/#monitor-backup-annotation:~:text=It%20is%20possible%20to%20exclude%20volumes%20from%20being%20backed%20up%20using%20the%20backup.velero.io/backup%2Dvolumes%2Dexcludes%20annotation%20on%20the%20pod.). It is also [applicable to FSBackups specified via Volume Policy](https://github.com/vmware-tanzu/velero/blob/main/internal/volumehelper/volume_policy_helper.go#L207)

**Comment by ithesadson** [comment]
@bhavyashree231 I recently had such a problem and I'm sharing the url. Maybe it might help you. Issue #7990
