### ISSUE TITLE
Kopia release cadence and compatibility with Velero releases

### ISSUE THREAD

**Issue by mpryc** [vmware-tanzu/velero#8136]
**Describe the problem/challenge you have**

Kopia is a critical tool for backup/restore operations when integrated with Velero. However, the asynchronous release schedules of Kopia and Velero can result in compatibility issues.

While Kopia's compatibility promise ensures that snapshots can be read across versions, users may still face difficulties when writing to or modifying repositories created by previous Kopia versions, which are bundled with earlier Velero releases.

Note that this problem exists *only* on the repositories created by previously installed versions of Velero, due to the fact the repository version is set during it's creation.

Velero uses a forked version of Kopia [project-velero/kopia](https://github.com/project-velero/kopia) that is referenced in Velero using [go.mod pseudo-versions](https://github.com/vmware-tanzu/velero/blob/f63b71448324cf29a5366d365a1ceea900150f23/go.mod#L180), replacing the kopia version that is defined in [go.mod](https://github.com/vmware-tanzu/velero/blob/f63b71448324cf29a5366d365a1ceea900150f23/go.mod#L28)

As of the time of writing this issue [upstream Kopia is at `[v0.17.0]`](https://github.com/kopia/kopia/commit/89c8eb47af2e1d5c1d14fe299a0cf7eaac095abf), while Velero's version of Kopia is using the [project-velero/kopia/commit/e07d5b7de567](https://github.com/project-velero/kopia/commit/e07d5b7de567), that is based on `[v0.17.0]` with additional patches, even if the [go.mod defines `[v0.16.0]`](https://github.com/vmware-tanzu/velero/blob/f63b71448324cf29a5366d365a1ceea900150f23/go.mod#L28). So there is already a bit of confusion / mismatch.

Below is a copy-paste of [Kopia's compatibility document](https://kopia.io/docs/advanced/compatibility/) as of the time of writing this issue, where last released version of Kopia is at `v0.17.0`, which falls into the `major version == v0` category of that document:

```text/plain
Compatibility

Kopia uses semantic versioning.

In order to ensure that snapshots created with Kopia will be available as the project evolves, starting with v0.3.0 release Kopia is offering the following compatibility promise:

1. Each version of Kopia will be able to read snapshots created using current and at least one previous version of the software. The previous version is to be interpreted as:

- for releases with major version == v0 (i.e. v0.x.y), previous version means previous minor version (v0.(x-1).*)
- for releases with major version == v1, previous version is the last minor release of the v0 major version.
- for releases with major version >= v2 (i.e. vx.y.z), previous version means previous major version (v(x-1)).

3. While not explicitly guaranteed, it is possible and likely that Kopia will be able to read (but not necessarily write) snapshots created with even older versions of software than explicitly guaranteed. For example, it’s likely that Kopia v0.6.0 will read snapshots created using v0.3.0, even though it’s three releases behind.

4. In order to avoid corrupting data, Kopia will refuse to mutate repositories it’s not designed to safely handle. That means, it will typically only allow reading, but not writing older versions of repository, unless explicitly documented and tested.

5. Kopia may support for writing old repository formats on a best-effort basis.

- For example Kopia v0.4.x may write using repository format created by v0.3.x in a way that v0.3.x versions will continue to understand it.

6. Each version of Kopia will offer migration mechanism to bring old readable repository format to the current format and thus enable full read-write operation.

7. Kopia will never upgrade old repository format to a new version without explicit human action.
```

Since Kopia was first integrated in Velero, there has been the following releases of Kopia in upstream, based on the compatibility document Velero may find problems on the releases that are `n-1`. The Velero's fork of the Kopia upstream repository was updated with :

```text/plain
Kopia Releases since first integration to Velero:
- May 1, 2023     |    v0.13.0
- Sep 16, 2023    |    v0.14.0
- Oct 22, 2023    |    v0.15.0
- Mar 23, 2024    |    v0.16.0
- Apr 16, 2024    |    v0.17.0
```

Matrix of Kopia versions used by respective Velero versions, we can see that from the Kopia compatibility document none of the Velero versions is in fact compatible with the previous one as the version bump of Kopia is always higher then `n-1`:

```text/plain
Kopia based on v0.17.0:
  - project-velero/kopia   hash: e07d5b7de567 (branch v0.17.0-velero.1)
  - kopia/kopia            hash: 89c8eb4
  - Velero Versions
    - 1.14.0

Kopia based on v0.15.0 (even if the mention in go.mod is v0.14.1):
  - project-velero/kopia   hash: cf7bbc7f8519 (branch v0.15.0-velero-patch)
  - kopia/kopia            hash: dd1ebb1
  - Velero Versions
    - 1.13.0
    - 1.13.1
    - 1.13.2

Kopia based on v0.13.0:
  - project-velero/kopia   hash: 42cd86a (branch v0.13.0-velero.1)
  - kopia/kopia            hash: 7f69502
  - Velero Versions
    - 1.12.0
    - 1.12.1
    - 1.12.2
    - 1.12.3
    - 1.12.4
```

**Describe the solution you'd like**
There are few possible paths going forward:

  1. Improve version synchronization, this however may be problematic as the release cycles of both projects are not aligned.
  2. Implement compatibility layer in Velero, so when the new version of Kopia used in the new version of Velero is trying to be used the upgrade path is executed, similarly to the upgrade path described in the https://kopia.io/docs/upgrade/
  3. Ensure clear compatibility documentation with manual steps to upgrade Kopia repository for existing releases.
  4. Open for discussion...

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by sseago** [comment]
From what is stated above, it sounds like a velero 1.13 install with existing kopia repo and backups, upon upgrade to velero 1.14 will *not* be able to take additional backups into that backup repo, since the version difference is 2. This seems like something people would have hit by now.

**Comment by weshayutin** [comment]
I would think that the kopia upgrade should be run as part of the repo maint job across all the repos to solve this.

**Comment by kaovilai** [comment]
> From what is stated above, it sounds like a velero 1.13 install with existing kopia repo and backups, upon upgrade to velero 1.14 will _not_ be able to take additional backups into that backup repo, since the version difference is 2. This seems like something people would have hit by now.

Not guaranteed to fail either.

> 5. Kopia may support for writing old repository formats on a best-effort basis.

**Comment by Lyndon-Li** [comment]
This is not actually a problem.

Velero is not using the Kopia upstream releases directly, instead, Velero cherry-pick commits that are safe and beneficial(to Velero) to a [forked branch](https://github.com/project-velero/kopia) which is released with Velero.
Velero is not using all the functionalities/code of Kopia, so Velero manages Kopia in a granular manner.

We keep tracking every commit we merged from the upstream and also do sufficient tests so that the new changes won't break any functionalities. And the compatibility is one of the major points we want to guarantee.
Sometimes, we pin the code the a new minor/patch release of Kopia, but before doing that, we've also done enough checks and tests of the new commits.

Conclusively, as for now, the new versions of Velero work with the old repo of 0.13 which is the first Kopia version Velero integrates.

**Comment by sseago** [comment]
Main concern here isn't current compatibility but future compatibility. Currently Kopia only guarantees full read/write compatibilities with backup repositories from version N-1, although they do attempt to preserve the compatibility for longer. With Velero, if a backup is made with 1.12, then if you're using 1.14 now, you may have kopia snapshots from release N-4. Also, due to the incremental nature of backups, you may be dealing with an even larger version skew. Imagine the following scenario:
1) initial backup of volume1 using Velero 1.12/Kopia 0.13
2) upgrade Velero to 1.14
3) Run another backup, so now we have an incremental backup of volume1, using Kopia 0.17, but backup repo is still in the 0.13 version
4) Upgrade velero to 1.16 -- assume that kopia is bumped up again, now to 0.19.
5) Run another backup, also incremental, using Kppia 0.19, but backup repo is still in 0.13 format, or N-6

The issue is that if we keep upgrading velero and making incremental backups (say we have a schedule where we run nightly or weekly backups), we will eventually have a very large version skew between backup repo format and current kopia version, eventually hitting the point of incompatibility -- if not at the level of "repo unreadable", then still maybe at the level of "kopia makes repo read-only", so no more incremental backups.

A solution for this problem would be to have an optional "upgrade backup repository" step in kopia maintenance, which will allow users to configure velero to keep the backuprepository updated to the current version of kopia in use. It's optional, because if a user happens to share a BSL between clusters with different velero versions, we don't want to upgrade the repo to a version *newer* than a version in active use.

**Comment by Lyndon-Li** [comment]
1) Incremental backups are not related to this topic, because both incremental backup data and full backup data are converged and stored in the same format, it cannot be that the incremental data is with one format and the full data is with the other format.
2) Actually, the repo format won't change frequently/dramatically. But once it happens and the repo turns to incompatible, the upgrade is a heavy and dangerous operation because it needs to change the data in the repo dramatically. For example, as for now, Kopia's repo format changes around the Index storage only (`kopia repository upgrade` is for the same purpose). However, even for the current change, the upgrade needs to read all the indexes, reorganize them and store them again. If some more changes happen in future, the upgrade could be even heavier.
3) As mentioned above, for each commit cherry-pick and version bump up, we closely monitor the impact, so the problem that upgrade of Velero breaks the access to the previous backup data won't happen. If we find that the new Kopia version has compatibility issue, we won't bump it up. However, this doesn't mean the Kopia with Velero doesn't evolve, we can still cherry-pick the new commits and/or make necessary modifications so that they could adopt to Velero.
4) If the incompatibility exists for a long time and we have to bump up Kopia to get in important changes, or the incompatibility is acceptable according to Velero's policy, the situation will be that we create a new repo and run full backups for all (because we cannot write the existing repo). That is the most safe choice. Involving the repo upgrade in the scheduled and automatic repo maintenance is not a good choice, because once the upgrade fails, the repo data may be corrupted and users may lose all the backup data. The repo upgrade itself is better to left alone as an advanced option to users.
5) Finally, the question comes down to what is the compatibility policy of Velero. E.g., how many previous versions of Velero are to supported. We actually don't need to consider Kopia's compatibility policy too much, as point 2), we can always guarantee the compatibility for each version of Velero, if it is required. But it is not always required, so we only need to know Velero's own policy so that we know when we can bump up an incompatible Kopia version.

**Comment by Lyndon-Li** [comment]
As mentioned above, when we need to bump up to a Kopia version with break changes, Velero always creates a new repo, so all backups go with a full backup first. We don't rely on users to manually run the repo upgrade. This make Velero's management simple.
It is also fine to run the full backups, as the best practice, full backups should run periodically, e.g., weekly or monthly.
